// Code generated by MockGen. DO NOT EDIT.
// Source: apply_recovery.go
//
// Generated by this command:
//
//	mockgen -source=apply_recovery.go -destination=mock/apply_recovery.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockrecoveryCodesUpdater is a mock of recoveryCodesUpdater interface.
type MockrecoveryCodesUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockrecoveryCodesUpdaterMockRecorder
	isgomock struct{}
}

// MockrecoveryCodesUpdaterMockRecorder is the mock recorder for MockrecoveryCodesUpdater.
type MockrecoveryCodesUpdaterMockRecorder struct {
	mock *MockrecoveryCodesUpdater
}

// NewMockrecoveryCodesUpdater creates a new mock instance.
func NewMockrecoveryCodesUpdater(ctrl *gomock.Controller) *MockrecoveryCodesUpdater {
	mock := &MockrecoveryCodesUpdater{ctrl: ctrl}
	mock.recorder = &MockrecoveryCodesUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecoveryCodesUpdater) EXPECT() *MockrecoveryCodesUpdaterMockRecorder {
	return m.recorder
}

// UpdateRecoveryCodes mocks base method.
func (m *MockrecoveryCodesUpdater) UpdateRecoveryCodes(ctx context.Context, userID uuid.UUID, hashed []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecoveryCodes", ctx, userID, hashed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecoveryCodes indicates an expected call of UpdateRecoveryCodes.
func (mr *MockrecoveryCodesUpdaterMockRecorder) UpdateRecoveryCodes(ctx, userID, hashed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecoveryCodes", reflect.TypeOf((*MockrecoveryCodesUpdater)(nil).UpdateRecoveryCodes), ctx, userID, hashed)
}
