// Code generated by MockGen. DO NOT EDIT.
// Source: apply_operation.go
//
// Generated by this command:
//
//	mockgen -source=apply_operation.go -destination=mock/apply_operation.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	conv "github.com/mondegor/go-core/util/conv"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationDeleter is a mock of operationDeleter interface.
type MockoperationDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockoperationDeleterMockRecorder
	isgomock struct{}
}

// MockoperationDeleterMockRecorder is the mock recorder for MockoperationDeleter.
type MockoperationDeleterMockRecorder struct {
	mock *MockoperationDeleter
}

// NewMockoperationDeleter creates a new mock instance.
func NewMockoperationDeleter(ctrl *gomock.Controller) *MockoperationDeleter {
	mock := &MockoperationDeleter{ctrl: ctrl}
	mock.recorder = &MockoperationDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationDeleter) EXPECT() *MockoperationDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockoperationDeleter) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockoperationDeleterMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockoperationDeleter)(nil).Delete), ctx, token)
}

// FetchOneForUpdate mocks base method.
func (m *MockoperationDeleter) FetchOneForUpdate(ctx context.Context, token string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneForUpdate", ctx, token)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneForUpdate indicates an expected call of FetchOneForUpdate.
func (mr *MockoperationDeleterMockRecorder) FetchOneForUpdate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneForUpdate", reflect.TypeOf((*MockoperationDeleter)(nil).FetchOneForUpdate), ctx, token)
}

// MockoperationLogger is a mock of operationLogger interface.
type MockoperationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLoggerMockRecorder
	isgomock struct{}
}

// MockoperationLoggerMockRecorder is the mock recorder for MockoperationLogger.
type MockoperationLoggerMockRecorder struct {
	mock *MockoperationLogger
}

// NewMockoperationLogger creates a new mock instance.
func NewMockoperationLogger(ctrl *gomock.Controller) *MockoperationLogger {
	mock := &MockoperationLogger{ctrl: ctrl}
	mock.recorder = &MockoperationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogger) EXPECT() *MockoperationLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockoperationLogger) Log(ctx context.Context, entry entity.SecureOperationLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, entry)
}

// Log indicates an expected call of Log.
func (mr *MockoperationLoggerMockRecorder) Log(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockoperationLogger)(nil).Log), ctx, entry)
}

// MockactorPropsBuilder is a mock of actorPropsBuilder interface.
type MockactorPropsBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockactorPropsBuilderMockRecorder
	isgomock struct{}
}

// MockactorPropsBuilderMockRecorder is the mock recorder for MockactorPropsBuilder.
type MockactorPropsBuilderMockRecorder struct {
	mock *MockactorPropsBuilder
}

// NewMockactorPropsBuilder creates a new mock instance.
func NewMockactorPropsBuilder(ctrl *gomock.Controller) *MockactorPropsBuilder {
	mock := &MockactorPropsBuilder{ctrl: ctrl}
	mock.recorder = &MockactorPropsBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactorPropsBuilder) EXPECT() *MockactorPropsBuilderMockRecorder {
	return m.recorder
}

// FormatTime mocks base method.
func (m *MockactorPropsBuilder) FormatTime(actor dto.ActorMeta, tm time.Time) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatTime", actor, tm)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatTime indicates an expected call of FormatTime.
func (mr *MockactorPropsBuilderMockRecorder) FormatTime(actor, tm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatTime", reflect.TypeOf((*MockactorPropsBuilder)(nil).FormatTime), actor, tm)
}

// With mocks base method.
func (m *MockactorPropsBuilder) With(actor dto.ActorMeta, props conv.Group) conv.Group {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "With", actor, props)
	ret0, _ := ret[0].(conv.Group)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockactorPropsBuilderMockRecorder) With(actor, props any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockactorPropsBuilder)(nil).With), actor, props)
}
