// Code generated by MockGen. DO NOT EDIT.
// Source: apply_email.go
//
// Generated by this command:
//
//	mockgen -source=apply_email.go -destination=mock/apply_email.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockchangeEmailCreator is a mock of changeEmailCreator interface.
type MockchangeEmailCreator struct {
	ctrl     *gomock.Controller
	recorder *MockchangeEmailCreatorMockRecorder
	isgomock struct{}
}

// MockchangeEmailCreatorMockRecorder is the mock recorder for MockchangeEmailCreator.
type MockchangeEmailCreatorMockRecorder struct {
	mock *MockchangeEmailCreator
}

// NewMockchangeEmailCreator creates a new mock instance.
func NewMockchangeEmailCreator(ctrl *gomock.Controller) *MockchangeEmailCreator {
	mock := &MockchangeEmailCreator{ctrl: ctrl}
	mock.recorder = &MockchangeEmailCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangeEmailCreator) EXPECT() *MockchangeEmailCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockchangeEmailCreator) Create(userID uuid.UUID, in dto.ChangeEmailOperation) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, in)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockchangeEmailCreatorMockRecorder) Create(userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockchangeEmailCreator)(nil).Create), userID, in)
}
