// Code generated by MockGen. DO NOT EDIT.
// Source: apply_totp.go
//
// Generated by this command:
//
//	mockgen -source=apply_totp.go -destination=mock/apply_totp.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockuser2faBinder is a mock of user2faBinder interface.
type Mockuser2faBinder struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faBinderMockRecorder
	isgomock struct{}
}

// Mockuser2faBinderMockRecorder is the mock recorder for Mockuser2faBinder.
type Mockuser2faBinderMockRecorder struct {
	mock *Mockuser2faBinder
}

// NewMockuser2faBinder creates a new mock instance.
func NewMockuser2faBinder(ctrl *gomock.Controller) *Mockuser2faBinder {
	mock := &Mockuser2faBinder{ctrl: ctrl}
	mock.recorder = &Mockuser2faBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faBinder) EXPECT() *Mockuser2faBinderMockRecorder {
	return m.recorder
}

// InsertOrUpdate mocks base method.
func (m *Mockuser2faBinder) InsertOrUpdate(ctx context.Context, row entity.Auth2FA) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdate", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdate indicates an expected call of InsertOrUpdate.
func (mr *Mockuser2faBinderMockRecorder) InsertOrUpdate(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdate", reflect.TypeOf((*Mockuser2faBinder)(nil).InsertOrUpdate), ctx, row)
}

// MockrecoveryCodesGenerator is a mock of recoveryCodesGenerator interface.
type MockrecoveryCodesGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockrecoveryCodesGeneratorMockRecorder
	isgomock struct{}
}

// MockrecoveryCodesGeneratorMockRecorder is the mock recorder for MockrecoveryCodesGenerator.
type MockrecoveryCodesGeneratorMockRecorder struct {
	mock *MockrecoveryCodesGenerator
}

// NewMockrecoveryCodesGenerator creates a new mock instance.
func NewMockrecoveryCodesGenerator(ctrl *gomock.Controller) *MockrecoveryCodesGenerator {
	mock := &MockrecoveryCodesGenerator{ctrl: ctrl}
	mock.recorder = &MockrecoveryCodesGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecoveryCodesGenerator) EXPECT() *MockrecoveryCodesGeneratorMockRecorder {
	return m.recorder
}

// GenerateRecoveryCodes mocks base method.
func (m *MockrecoveryCodesGenerator) GenerateRecoveryCodes(count int) ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRecoveryCodes", count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRecoveryCodes indicates an expected call of GenerateRecoveryCodes.
func (mr *MockrecoveryCodesGeneratorMockRecorder) GenerateRecoveryCodes(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRecoveryCodes", reflect.TypeOf((*MockrecoveryCodesGenerator)(nil).GenerateRecoveryCodes), count)
}

// MocktotpValidator is a mock of totpValidator interface.
type MocktotpValidator struct {
	ctrl     *gomock.Controller
	recorder *MocktotpValidatorMockRecorder
	isgomock struct{}
}

// MocktotpValidatorMockRecorder is the mock recorder for MocktotpValidator.
type MocktotpValidatorMockRecorder struct {
	mock *MocktotpValidator
}

// NewMocktotpValidator creates a new mock instance.
func NewMocktotpValidator(ctrl *gomock.Controller) *MocktotpValidator {
	mock := &MocktotpValidator{ctrl: ctrl}
	mock.recorder = &MocktotpValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktotpValidator) EXPECT() *MocktotpValidatorMockRecorder {
	return m.recorder
}

// ValidateCode mocks base method.
func (m *MocktotpValidator) ValidateCode(code, secret string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCode", code, secret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateCode indicates an expected call of ValidateCode.
func (mr *MocktotpValidatorMockRecorder) ValidateCode(code, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCode", reflect.TypeOf((*MocktotpValidator)(nil).ValidateCode), code, secret)
}
