// Code generated by MockGen. DO NOT EDIT.
// Source: change_email.go
//
// Generated by this command:
//
//	mockgen -source=change_email.go -destination=mock/change_email.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationCreator is a mock of operationCreator interface.
type MockoperationCreator struct {
	ctrl     *gomock.Controller
	recorder *MockoperationCreatorMockRecorder
	isgomock struct{}
}

// MockoperationCreatorMockRecorder is the mock recorder for MockoperationCreator.
type MockoperationCreatorMockRecorder struct {
	mock *MockoperationCreator
}

// NewMockoperationCreator creates a new mock instance.
func NewMockoperationCreator(ctrl *gomock.Controller) *MockoperationCreator {
	mock := &MockoperationCreator{ctrl: ctrl}
	mock.recorder = &MockoperationCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationCreator) EXPECT() *MockoperationCreatorMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockoperationCreator) Insert(ctx context.Context, row secureoperation.SecureOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockoperationCreatorMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockoperationCreator)(nil).Insert), ctx, row)
}

// MockuserEmailChecker is a mock of userEmailChecker interface.
type MockuserEmailChecker struct {
	ctrl     *gomock.Controller
	recorder *MockuserEmailCheckerMockRecorder
	isgomock struct{}
}

// MockuserEmailCheckerMockRecorder is the mock recorder for MockuserEmailChecker.
type MockuserEmailCheckerMockRecorder struct {
	mock *MockuserEmailChecker
}

// NewMockuserEmailChecker creates a new mock instance.
func NewMockuserEmailChecker(ctrl *gomock.Controller) *MockuserEmailChecker {
	mock := &MockuserEmailChecker{ctrl: ctrl}
	mock.recorder = &MockuserEmailCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserEmailChecker) EXPECT() *MockuserEmailCheckerMockRecorder {
	return m.recorder
}

// CheckAvailabilityEmail mocks base method.
func (m *MockuserEmailChecker) CheckAvailabilityEmail(ctx context.Context, userEmail contactaddress.ContactAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityEmail", ctx, userEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailabilityEmail indicates an expected call of CheckAvailabilityEmail.
func (mr *MockuserEmailCheckerMockRecorder) CheckAvailabilityEmail(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityEmail", reflect.TypeOf((*MockuserEmailChecker)(nil).CheckAvailabilityEmail), ctx, userEmail)
}

// MockfactoryOperationValue2FA is a mock of factoryOperationValue2FA interface.
type MockfactoryOperationValue2FA struct {
	ctrl     *gomock.Controller
	recorder *MockfactoryOperationValue2FAMockRecorder
	isgomock struct{}
}

// MockfactoryOperationValue2FAMockRecorder is the mock recorder for MockfactoryOperationValue2FA.
type MockfactoryOperationValue2FAMockRecorder struct {
	mock *MockfactoryOperationValue2FA
}

// NewMockfactoryOperationValue2FA creates a new mock instance.
func NewMockfactoryOperationValue2FA(ctrl *gomock.Controller) *MockfactoryOperationValue2FA {
	mock := &MockfactoryOperationValue2FA{ctrl: ctrl}
	mock.recorder = &MockfactoryOperationValue2FAMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfactoryOperationValue2FA) EXPECT() *MockfactoryOperationValue2FAMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockfactoryOperationValue2FA) Create(user2FA dto.User2FA, fieldValue string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA, fieldValue)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockfactoryOperationValue2FAMockRecorder) Create(user2FA, fieldValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfactoryOperationValue2FA)(nil).Create), user2FA, fieldValue)
}
