// Code generated by MockGen. DO NOT EDIT.
// Source: change_password.go
//
// Generated by this command:
//
//	mockgen -source=change_password.go -destination=mock/change_password.go -package=mock
//

// Package mock is a generated GoMock package.
package mock
