// Code generated by MockGen. DO NOT EDIT.
// Source: change_phone.go
//
// Generated by this command:
//
//	mockgen -source=change_phone.go -destination=mock/change_phone.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	gomock "go.uber.org/mock/gomock"
)

// MockuserPhoneChecker is a mock of userPhoneChecker interface.
type MockuserPhoneChecker struct {
	ctrl     *gomock.Controller
	recorder *MockuserPhoneCheckerMockRecorder
	isgomock struct{}
}

// MockuserPhoneCheckerMockRecorder is the mock recorder for MockuserPhoneChecker.
type MockuserPhoneCheckerMockRecorder struct {
	mock *MockuserPhoneChecker
}

// NewMockuserPhoneChecker creates a new mock instance.
func NewMockuserPhoneChecker(ctrl *gomock.Controller) *MockuserPhoneChecker {
	mock := &MockuserPhoneChecker{ctrl: ctrl}
	mock.recorder = &MockuserPhoneCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserPhoneChecker) EXPECT() *MockuserPhoneCheckerMockRecorder {
	return m.recorder
}

// CheckAvailabilityPhone mocks base method.
func (m *MockuserPhoneChecker) CheckAvailabilityPhone(ctx context.Context, userPhone contactaddress.ContactAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityPhone", ctx, userPhone)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailabilityPhone indicates an expected call of CheckAvailabilityPhone.
func (mr *MockuserPhoneCheckerMockRecorder) CheckAvailabilityPhone(ctx, userPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityPhone", reflect.TypeOf((*MockuserPhoneChecker)(nil).CheckAvailabilityPhone), ctx, userPhone)
}
