// Code generated by MockGen. DO NOT EDIT.
// Source: change_email.go
//
// Generated by this command:
//
//	mockgen -source=change_email.go -destination=mock/change_email.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	conv "github.com/mondegor/go-core/util/conv"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationOpener is a mock of operationOpener interface.
type MockoperationOpener struct {
	ctrl     *gomock.Controller
	recorder *MockoperationOpenerMockRecorder
	isgomock struct{}
}

// MockoperationOpenerMockRecorder is the mock recorder for MockoperationOpener.
type MockoperationOpenerMockRecorder struct {
	mock *MockoperationOpener
}

// NewMockoperationOpener creates a new mock instance.
func NewMockoperationOpener(ctrl *gomock.Controller) *MockoperationOpener {
	mock := &MockoperationOpener{ctrl: ctrl}
	mock.recorder = &MockoperationOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationOpener) EXPECT() *MockoperationOpenerMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockoperationOpener) Open(ctx context.Context, actor dto.ActorMeta, op secureoperation.SecureOperation, noteName string, noteProps conv.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, actor, op, noteName, noteProps)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockoperationOpenerMockRecorder) Open(ctx, actor, op, noteName, noteProps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockoperationOpener)(nil).Open), ctx, actor, op, noteName, noteProps)
}

// MockuserEmailChecker is a mock of userEmailChecker interface.
type MockuserEmailChecker struct {
	ctrl     *gomock.Controller
	recorder *MockuserEmailCheckerMockRecorder
	isgomock struct{}
}

// MockuserEmailCheckerMockRecorder is the mock recorder for MockuserEmailChecker.
type MockuserEmailCheckerMockRecorder struct {
	mock *MockuserEmailChecker
}

// NewMockuserEmailChecker creates a new mock instance.
func NewMockuserEmailChecker(ctrl *gomock.Controller) *MockuserEmailChecker {
	mock := &MockuserEmailChecker{ctrl: ctrl}
	mock.recorder = &MockuserEmailCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserEmailChecker) EXPECT() *MockuserEmailCheckerMockRecorder {
	return m.recorder
}

// CheckAvailabilityEmail mocks base method.
func (m *MockuserEmailChecker) CheckAvailabilityEmail(ctx context.Context, userEmail contactaddress.ContactAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityEmail", ctx, userEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailabilityEmail indicates an expected call of CheckAvailabilityEmail.
func (mr *MockuserEmailCheckerMockRecorder) CheckAvailabilityEmail(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityEmail", reflect.TypeOf((*MockuserEmailChecker)(nil).CheckAvailabilityEmail), ctx, userEmail)
}

// MockfactoryOperationAddress2FA is a mock of factoryOperationAddress2FA interface.
type MockfactoryOperationAddress2FA struct {
	ctrl     *gomock.Controller
	recorder *MockfactoryOperationAddress2FAMockRecorder
	isgomock struct{}
}

// MockfactoryOperationAddress2FAMockRecorder is the mock recorder for MockfactoryOperationAddress2FA.
type MockfactoryOperationAddress2FAMockRecorder struct {
	mock *MockfactoryOperationAddress2FA
}

// NewMockfactoryOperationAddress2FA creates a new mock instance.
func NewMockfactoryOperationAddress2FA(ctrl *gomock.Controller) *MockfactoryOperationAddress2FA {
	mock := &MockfactoryOperationAddress2FA{ctrl: ctrl}
	mock.recorder = &MockfactoryOperationAddress2FAMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfactoryOperationAddress2FA) EXPECT() *MockfactoryOperationAddress2FAMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockfactoryOperationAddress2FA) Create(user2FA dto.User2FA, fieldValue contactaddress.ContactAddress) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA, fieldValue)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockfactoryOperationAddress2FAMockRecorder) Create(user2FA, fieldValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfactoryOperationAddress2FA)(nil).Create), user2FA, fieldValue)
}
