// Code generated by MockGen. DO NOT EDIT.
// Source: change_totp.go
//
// Generated by this command:
//
//	mockgen -source=change_totp.go -destination=mock/change_totp.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// Mockuser2faOperationCreator is a mock of user2faOperationCreator interface.
type Mockuser2faOperationCreator struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faOperationCreatorMockRecorder
	isgomock struct{}
}

// Mockuser2faOperationCreatorMockRecorder is the mock recorder for Mockuser2faOperationCreator.
type Mockuser2faOperationCreatorMockRecorder struct {
	mock *Mockuser2faOperationCreator
}

// NewMockuser2faOperationCreator creates a new mock instance.
func NewMockuser2faOperationCreator(ctrl *gomock.Controller) *Mockuser2faOperationCreator {
	mock := &Mockuser2faOperationCreator{ctrl: ctrl}
	mock.recorder = &Mockuser2faOperationCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faOperationCreator) EXPECT() *Mockuser2faOperationCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockuser2faOperationCreator) Create(user2FA dto.User2FA) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *Mockuser2faOperationCreatorMockRecorder) Create(user2FA any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockuser2faOperationCreator)(nil).Create), user2FA)
}
