// Code generated by MockGen. DO NOT EDIT.
// Source: get_totp_secret.go
//
// Generated by this command:
//
//	mockgen -source=get_totp_secret.go -destination=mock/get_totp_secret.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktotpURLBuilder is a mock of totpURLBuilder interface.
type MocktotpURLBuilder struct {
	ctrl     *gomock.Controller
	recorder *MocktotpURLBuilderMockRecorder
	isgomock struct{}
}

// MocktotpURLBuilderMockRecorder is the mock recorder for MocktotpURLBuilder.
type MocktotpURLBuilderMockRecorder struct {
	mock *MocktotpURLBuilder
}

// NewMocktotpURLBuilder creates a new mock instance.
func NewMocktotpURLBuilder(ctrl *gomock.Controller) *MocktotpURLBuilder {
	mock := &MocktotpURLBuilder{ctrl: ctrl}
	mock.recorder = &MocktotpURLBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktotpURLBuilder) EXPECT() *MocktotpURLBuilderMockRecorder {
	return m.recorder
}

// OTPAuthURL mocks base method.
func (m *MocktotpURLBuilder) OTPAuthURL(accountName, secret string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OTPAuthURL", accountName, secret)
	ret0, _ := ret[0].(string)
	return ret0
}

// OTPAuthURL indicates an expected call of OTPAuthURL.
func (mr *MocktotpURLBuilderMockRecorder) OTPAuthURL(accountName, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OTPAuthURL", reflect.TypeOf((*MocktotpURLBuilder)(nil).OTPAuthURL), accountName, secret)
}
