// Code generated by MockGen. DO NOT EDIT.
// Source: render_totp_qr.go
//
// Generated by this command:
//
//	mockgen -source=render_totp_qr.go -destination=mock/render_totp_qr.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	image "image"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktotpQRRenderer is a mock of totpQRRenderer interface.
type MocktotpQRRenderer struct {
	ctrl     *gomock.Controller
	recorder *MocktotpQRRendererMockRecorder
	isgomock struct{}
}

// MocktotpQRRendererMockRecorder is the mock recorder for MocktotpQRRenderer.
type MocktotpQRRendererMockRecorder struct {
	mock *MocktotpQRRenderer
}

// NewMocktotpQRRenderer creates a new mock instance.
func NewMocktotpQRRenderer(ctrl *gomock.Controller) *MocktotpQRRenderer {
	mock := &MocktotpQRRenderer{ctrl: ctrl}
	mock.recorder = &MocktotpQRRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktotpQRRenderer) EXPECT() *MocktotpQRRendererMockRecorder {
	return m.recorder
}

// QRImage mocks base method.
func (m *MocktotpQRRenderer) QRImage(accountName, secret string, width, height int) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QRImage", accountName, secret, width, height)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QRImage indicates an expected call of QRImage.
func (mr *MocktotpQRRendererMockRecorder) QRImage(accountName, secret, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QRImage", reflect.TypeOf((*MocktotpQRRenderer)(nil).QRImage), accountName, secret, width, height)
}
