// Code generated by MockGen. DO NOT EDIT.
// Source: security_log.go
//
// Generated by this command:
//
//	mockgen -source=security_log.go -destination=mock/security_log.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	mrstorage "github.com/mondegor/go-core/mrstorage"
	gomock "go.uber.org/mock/gomock"
)

// MocksecurityLogFetcher is a mock of securityLogFetcher interface.
type MocksecurityLogFetcher struct {
	ctrl     *gomock.Controller
	recorder *MocksecurityLogFetcherMockRecorder
	isgomock struct{}
}

// MocksecurityLogFetcherMockRecorder is the mock recorder for MocksecurityLogFetcher.
type MocksecurityLogFetcherMockRecorder struct {
	mock *MocksecurityLogFetcher
}

// NewMocksecurityLogFetcher creates a new mock instance.
func NewMocksecurityLogFetcher(ctrl *gomock.Controller) *MocksecurityLogFetcher {
	mock := &MocksecurityLogFetcher{ctrl: ctrl}
	mock.recorder = &MocksecurityLogFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecurityLogFetcher) EXPECT() *MocksecurityLogFetcherMockRecorder {
	return m.recorder
}

// FetchByUserID mocks base method.
func (m *MocksecurityLogFetcher) FetchByUserID(ctx context.Context, userID uuid.UUID, cursor mrstorage.IDCursor) ([]entity.SecurityLogEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserID", ctx, userID, cursor)
	ret0, _ := ret[0].([]entity.SecurityLogEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchByUserID indicates an expected call of FetchByUserID.
func (mr *MocksecurityLogFetcherMockRecorder) FetchByUserID(ctx, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserID", reflect.TypeOf((*MocksecurityLogFetcher)(nil).FetchByUserID), ctx, userID, cursor)
}
