// Code generated by MockGen. DO NOT EDIT.
// Source: queue_consumer.go
//
// Generated by this command:
//
//	mockgen -source=queue_consumer.go -destination=mock/queue_consumer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrqueue/entity"
	itemstatus "github.com/mondegor/go-components/mrqueue/enum/itemstatus"
	gomock "go.uber.org/mock/gomock"
)

// MockitemStorage is a mock of itemStorage interface.
type MockitemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockitemStorageMockRecorder
	isgomock struct{}
}

// MockitemStorageMockRecorder is the mock recorder for MockitemStorage.
type MockitemStorageMockRecorder struct {
	mock *MockitemStorage
}

// NewMockitemStorage creates a new mock instance.
func NewMockitemStorage(ctrl *gomock.Controller) *MockitemStorage {
	mock := &MockitemStorage{ctrl: ctrl}
	mock.recorder = &MockitemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemStorage) EXPECT() *MockitemStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockitemStorage) Delete(ctx context.Context, rowID uint64, status itemstatus.Enum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, rowID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockitemStorageMockRecorder) Delete(ctx, rowID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockitemStorage)(nil).Delete), ctx, rowID, status)
}

// FetchAndUpdateStatusReadyToProcessing mocks base method.
func (m *MockitemStorage) FetchAndUpdateStatusReadyToProcessing(ctx context.Context, limit int) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndUpdateStatusReadyToProcessing", ctx, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAndUpdateStatusReadyToProcessing indicates an expected call of FetchAndUpdateStatusReadyToProcessing.
func (mr *MockitemStorageMockRecorder) FetchAndUpdateStatusReadyToProcessing(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndUpdateStatusReadyToProcessing", reflect.TypeOf((*MockitemStorage)(nil).FetchAndUpdateStatusReadyToProcessing), ctx, limit)
}

// UpdateStatusProcessingToReady mocks base method.
func (m *MockitemStorage) UpdateStatusProcessingToReady(ctx context.Context, rowsIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusProcessingToReady", ctx, rowsIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusProcessingToReady indicates an expected call of UpdateStatusProcessingToReady.
func (mr *MockitemStorageMockRecorder) UpdateStatusProcessingToReady(ctx, rowsIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusProcessingToReady", reflect.TypeOf((*MockitemStorage)(nil).UpdateStatusProcessingToReady), ctx, rowsIDs)
}

// UpdateStatusProcessingToRetry mocks base method.
func (m *MockitemStorage) UpdateStatusProcessingToRetry(ctx context.Context, rowID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusProcessingToRetry", ctx, rowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusProcessingToRetry indicates an expected call of UpdateStatusProcessingToRetry.
func (mr *MockitemStorageMockRecorder) UpdateStatusProcessingToRetry(ctx, rowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusProcessingToRetry", reflect.TypeOf((*MockitemStorage)(nil).UpdateStatusProcessingToRetry), ctx, rowID)
}

// MockcompletedItemStorage is a mock of completedItemStorage interface.
type MockcompletedItemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockcompletedItemStorageMockRecorder
	isgomock struct{}
}

// MockcompletedItemStorageMockRecorder is the mock recorder for MockcompletedItemStorage.
type MockcompletedItemStorageMockRecorder struct {
	mock *MockcompletedItemStorage
}

// NewMockcompletedItemStorage creates a new mock instance.
func NewMockcompletedItemStorage(ctrl *gomock.Controller) *MockcompletedItemStorage {
	mock := &MockcompletedItemStorage{ctrl: ctrl}
	mock.recorder = &MockcompletedItemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompletedItemStorage) EXPECT() *MockcompletedItemStorageMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockcompletedItemStorage) Insert(ctx context.Context, rowID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockcompletedItemStorageMockRecorder) Insert(ctx, rowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockcompletedItemStorage)(nil).Insert), ctx, rowID)
}

// MockcrashedItemStorage is a mock of crashedItemStorage interface.
type MockcrashedItemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockcrashedItemStorageMockRecorder
	isgomock struct{}
}

// MockcrashedItemStorageMockRecorder is the mock recorder for MockcrashedItemStorage.
type MockcrashedItemStorageMockRecorder struct {
	mock *MockcrashedItemStorage
}

// NewMockcrashedItemStorage creates a new mock instance.
func NewMockcrashedItemStorage(ctrl *gomock.Controller) *MockcrashedItemStorage {
	mock := &MockcrashedItemStorage{ctrl: ctrl}
	mock.recorder = &MockcrashedItemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcrashedItemStorage) EXPECT() *MockcrashedItemStorageMockRecorder {
	return m.recorder
}

// InsertOne mocks base method.
func (m *MockcrashedItemStorage) InsertOne(ctx context.Context, row entity.CrashedItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockcrashedItemStorageMockRecorder) InsertOne(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockcrashedItemStorage)(nil).InsertOne), ctx, row)
}
