// Code generated by MockGen. DO NOT EDIT.
// Source: auth_tokens_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=auth_tokens_cleaner.go -destination=mock/auth_tokens_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthTokenStorage is a mock of AuthTokenStorage interface.
type MockAuthTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenStorageMockRecorder
	isgomock struct{}
}

// MockAuthTokenStorageMockRecorder is the mock recorder for MockAuthTokenStorage.
type MockAuthTokenStorageMockRecorder struct {
	mock *MockAuthTokenStorage
}

// NewMockAuthTokenStorage creates a new mock instance.
func NewMockAuthTokenStorage(ctrl *gomock.Controller) *MockAuthTokenStorage {
	mock := &MockAuthTokenStorage{ctrl: ctrl}
	mock.recorder = &MockAuthTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenStorage) EXPECT() *MockAuthTokenStorageMockRecorder {
	return m.recorder
}

// DeleteExpiredNonRefresh mocks base method.
func (m *MockAuthTokenStorage) DeleteExpiredNonRefresh(ctx context.Context, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredNonRefresh", ctx, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredNonRefresh indicates an expected call of DeleteExpiredNonRefresh.
func (mr *MockAuthTokenStorageMockRecorder) DeleteExpiredNonRefresh(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredNonRefresh", reflect.TypeOf((*MockAuthTokenStorage)(nil).DeleteExpiredNonRefresh), ctx, limit)
}

// DeleteExpiredRefresh mocks base method.
func (m *MockAuthTokenStorage) DeleteExpiredRefresh(ctx context.Context, limit int) ([]entity.SessionPK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredRefresh", ctx, limit)
	ret0, _ := ret[0].([]entity.SessionPK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredRefresh indicates an expected call of DeleteExpiredRefresh.
func (mr *MockAuthTokenStorageMockRecorder) DeleteExpiredRefresh(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredRefresh", reflect.TypeOf((*MockAuthTokenStorage)(nil).DeleteExpiredRefresh), ctx, limit)
}

// MockSessionCleanupQueue is a mock of SessionCleanupQueue interface.
type MockSessionCleanupQueue struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCleanupQueueMockRecorder
	isgomock struct{}
}

// MockSessionCleanupQueueMockRecorder is the mock recorder for MockSessionCleanupQueue.
type MockSessionCleanupQueueMockRecorder struct {
	mock *MockSessionCleanupQueue
}

// NewMockSessionCleanupQueue creates a new mock instance.
func NewMockSessionCleanupQueue(ctrl *gomock.Controller) *MockSessionCleanupQueue {
	mock := &MockSessionCleanupQueue{ctrl: ctrl}
	mock.recorder = &MockSessionCleanupQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCleanupQueue) EXPECT() *MockSessionCleanupQueueMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockSessionCleanupQueue) Enqueue(ctx context.Context, pks []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, pks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockSessionCleanupQueueMockRecorder) Enqueue(ctx, pks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockSessionCleanupQueue)(nil).Enqueue), ctx, pks)
}
