// Code generated by MockGen. DO NOT EDIT.
// Source: auth_tokens_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=auth_tokens_cleaner.go -destination=mock/auth_tokens_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockauthTokenStorage is a mock of authTokenStorage interface.
type MockauthTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockauthTokenStorageMockRecorder
	isgomock struct{}
}

// MockauthTokenStorageMockRecorder is the mock recorder for MockauthTokenStorage.
type MockauthTokenStorageMockRecorder struct {
	mock *MockauthTokenStorage
}

// NewMockauthTokenStorage creates a new mock instance.
func NewMockauthTokenStorage(ctrl *gomock.Controller) *MockauthTokenStorage {
	mock := &MockauthTokenStorage{ctrl: ctrl}
	mock.recorder = &MockauthTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthTokenStorage) EXPECT() *MockauthTokenStorageMockRecorder {
	return m.recorder
}

// DeleteExpiredNonRefresh mocks base method.
func (m *MockauthTokenStorage) DeleteExpiredNonRefresh(ctx context.Context, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredNonRefresh", ctx, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredNonRefresh indicates an expected call of DeleteExpiredNonRefresh.
func (mr *MockauthTokenStorageMockRecorder) DeleteExpiredNonRefresh(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredNonRefresh", reflect.TypeOf((*MockauthTokenStorage)(nil).DeleteExpiredNonRefresh), ctx, limit)
}

// DeleteExpiredRefresh mocks base method.
func (m *MockauthTokenStorage) DeleteExpiredRefresh(ctx context.Context, limit int) ([]entity.SessionPK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredRefresh", ctx, limit)
	ret0, _ := ret[0].([]entity.SessionPK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredRefresh indicates an expected call of DeleteExpiredRefresh.
func (mr *MockauthTokenStorageMockRecorder) DeleteExpiredRefresh(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredRefresh", reflect.TypeOf((*MockauthTokenStorage)(nil).DeleteExpiredRefresh), ctx, limit)
}

// MocksessionCleanupQueue is a mock of sessionCleanupQueue interface.
type MocksessionCleanupQueue struct {
	ctrl     *gomock.Controller
	recorder *MocksessionCleanupQueueMockRecorder
	isgomock struct{}
}

// MocksessionCleanupQueueMockRecorder is the mock recorder for MocksessionCleanupQueue.
type MocksessionCleanupQueueMockRecorder struct {
	mock *MocksessionCleanupQueue
}

// NewMocksessionCleanupQueue creates a new mock instance.
func NewMocksessionCleanupQueue(ctrl *gomock.Controller) *MocksessionCleanupQueue {
	mock := &MocksessionCleanupQueue{ctrl: ctrl}
	mock.recorder = &MocksessionCleanupQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionCleanupQueue) EXPECT() *MocksessionCleanupQueueMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MocksessionCleanupQueue) Enqueue(ctx context.Context, pks []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, pks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MocksessionCleanupQueueMockRecorder) Enqueue(ctx, pks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MocksessionCleanupQueue)(nil).Enqueue), ctx, pks)
}
