// Code generated by MockGen. DO NOT EDIT.
// Source: operation_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=operation_cleaner.go -destination=mock/operation_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockoperationStorage is a mock of operationStorage interface.
type MockoperationStorage struct {
	ctrl     *gomock.Controller
	recorder *MockoperationStorageMockRecorder
	isgomock struct{}
}

// MockoperationStorageMockRecorder is the mock recorder for MockoperationStorage.
type MockoperationStorageMockRecorder struct {
	mock *MockoperationStorage
}

// NewMockoperationStorage creates a new mock instance.
func NewMockoperationStorage(ctrl *gomock.Controller) *MockoperationStorage {
	mock := &MockoperationStorage{ctrl: ctrl}
	mock.recorder = &MockoperationStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationStorage) EXPECT() *MockoperationStorageMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockoperationStorage) DeleteExpired(ctx context.Context, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockoperationStorageMockRecorder) DeleteExpired(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockoperationStorage)(nil).DeleteExpired), ctx, limit)
}

// MockoperationLogStorage is a mock of operationLogStorage interface.
type MockoperationLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLogStorageMockRecorder
	isgomock struct{}
}

// MockoperationLogStorageMockRecorder is the mock recorder for MockoperationLogStorage.
type MockoperationLogStorageMockRecorder struct {
	mock *MockoperationLogStorage
}

// NewMockoperationLogStorage creates a new mock instance.
func NewMockoperationLogStorage(ctrl *gomock.Controller) *MockoperationLogStorage {
	mock := &MockoperationLogStorage{ctrl: ctrl}
	mock.recorder = &MockoperationLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogStorage) EXPECT() *MockoperationLogStorageMockRecorder {
	return m.recorder
}

// DeleteBeforeDate mocks base method.
func (m *MockoperationLogStorage) DeleteBeforeDate(ctx context.Context, datetime time.Time, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeforeDate", ctx, datetime, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBeforeDate indicates an expected call of DeleteBeforeDate.
func (mr *MockoperationLogStorageMockRecorder) DeleteBeforeDate(ctx, datetime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeforeDate", reflect.TypeOf((*MockoperationLogStorage)(nil).DeleteBeforeDate), ctx, datetime, limit)
}
