// Code generated by MockGen. DO NOT EDIT.
// Source: security_log_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=security_log_cleaner.go -destination=mock/security_log_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSecurityLogStorage is a mock of SecurityLogStorage interface.
type MockSecurityLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityLogStorageMockRecorder
	isgomock struct{}
}

// MockSecurityLogStorageMockRecorder is the mock recorder for MockSecurityLogStorage.
type MockSecurityLogStorageMockRecorder struct {
	mock *MockSecurityLogStorage
}

// NewMockSecurityLogStorage creates a new mock instance.
func NewMockSecurityLogStorage(ctrl *gomock.Controller) *MockSecurityLogStorage {
	mock := &MockSecurityLogStorage{ctrl: ctrl}
	mock.recorder = &MockSecurityLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityLogStorage) EXPECT() *MockSecurityLogStorageMockRecorder {
	return m.recorder
}

// DeleteBeforeDate mocks base method.
func (m *MockSecurityLogStorage) DeleteBeforeDate(ctx context.Context, datetime time.Time, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeforeDate", ctx, datetime, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBeforeDate indicates an expected call of DeleteBeforeDate.
func (mr *MockSecurityLogStorageMockRecorder) DeleteBeforeDate(ctx, datetime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeforeDate", reflect.TypeOf((*MockSecurityLogStorage)(nil).DeleteBeforeDate), ctx, datetime, limit)
}
