// Code generated by MockGen. DO NOT EDIT.
// Source: session_excess_trimmer.go
//
// Generated by this command:
//
//	mockgen -source=session_excess_trimmer.go -destination=mock/session_excess_trimmer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionExcessQueueConsumer is a mock of SessionExcessQueueConsumer interface.
type MockSessionExcessQueueConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionExcessQueueConsumerMockRecorder
	isgomock struct{}
}

// MockSessionExcessQueueConsumerMockRecorder is the mock recorder for MockSessionExcessQueueConsumer.
type MockSessionExcessQueueConsumerMockRecorder struct {
	mock *MockSessionExcessQueueConsumer
}

// NewMockSessionExcessQueueConsumer creates a new mock instance.
func NewMockSessionExcessQueueConsumer(ctrl *gomock.Controller) *MockSessionExcessQueueConsumer {
	mock := &MockSessionExcessQueueConsumer{ctrl: ctrl}
	mock.recorder = &MockSessionExcessQueueConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionExcessQueueConsumer) EXPECT() *MockSessionExcessQueueConsumerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionExcessQueueConsumer) Delete(ctx context.Context, keys []entity.SessionExcessPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionExcessQueueConsumerMockRecorder) Delete(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionExcessQueueConsumer)(nil).Delete), ctx, keys)
}

// Fetch mocks base method.
func (m *MockSessionExcessQueueConsumer) Fetch(ctx context.Context, limit int) ([]entity.SessionExcessItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, limit)
	ret0, _ := ret[0].([]entity.SessionExcessItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSessionExcessQueueConsumerMockRecorder) Fetch(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSessionExcessQueueConsumer)(nil).Fetch), ctx, limit)
}

// MockOpenSessionFetcher is a mock of OpenSessionFetcher interface.
type MockOpenSessionFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockOpenSessionFetcherMockRecorder
	isgomock struct{}
}

// MockOpenSessionFetcherMockRecorder is the mock recorder for MockOpenSessionFetcher.
type MockOpenSessionFetcherMockRecorder struct {
	mock *MockOpenSessionFetcher
}

// NewMockOpenSessionFetcher creates a new mock instance.
func NewMockOpenSessionFetcher(ctrl *gomock.Controller) *MockOpenSessionFetcher {
	mock := &MockOpenSessionFetcher{ctrl: ctrl}
	mock.recorder = &MockOpenSessionFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenSessionFetcher) EXPECT() *MockOpenSessionFetcherMockRecorder {
	return m.recorder
}

// FetchOpenSessionIDs mocks base method.
func (m *MockOpenSessionFetcher) FetchOpenSessionIDs(ctx context.Context, userID uuid.UUID, realmID uint16) ([]uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOpenSessionIDs", ctx, userID, realmID)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOpenSessionIDs indicates an expected call of FetchOpenSessionIDs.
func (mr *MockOpenSessionFetcherMockRecorder) FetchOpenSessionIDs(ctx, userID, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOpenSessionIDs", reflect.TypeOf((*MockOpenSessionFetcher)(nil).FetchOpenSessionIDs), ctx, userID, realmID)
}

// MockSessionLister is a mock of SessionLister interface.
type MockSessionLister struct {
	ctrl     *gomock.Controller
	recorder *MockSessionListerMockRecorder
	isgomock struct{}
}

// MockSessionListerMockRecorder is the mock recorder for MockSessionLister.
type MockSessionListerMockRecorder struct {
	mock *MockSessionLister
}

// NewMockSessionLister creates a new mock instance.
func NewMockSessionLister(ctrl *gomock.Controller) *MockSessionLister {
	mock := &MockSessionLister{ctrl: ctrl}
	mock.recorder = &MockSessionListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionLister) EXPECT() *MockSessionListerMockRecorder {
	return m.recorder
}

// FetchOrderedListByUserIDAndSessionIDs mocks base method.
func (m *MockSessionLister) FetchOrderedListByUserIDAndSessionIDs(ctx context.Context, userID uuid.UUID, sessionIDs []uint32, limit int) ([]entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrderedListByUserIDAndSessionIDs", ctx, userID, sessionIDs, limit)
	ret0, _ := ret[0].([]entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrderedListByUserIDAndSessionIDs indicates an expected call of FetchOrderedListByUserIDAndSessionIDs.
func (mr *MockSessionListerMockRecorder) FetchOrderedListByUserIDAndSessionIDs(ctx, userID, sessionIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrderedListByUserIDAndSessionIDs", reflect.TypeOf((*MockSessionLister)(nil).FetchOrderedListByUserIDAndSessionIDs), ctx, userID, sessionIDs, limit)
}

// MockSessionCloser is a mock of SessionCloser interface.
type MockSessionCloser struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCloserMockRecorder
	isgomock struct{}
}

// MockSessionCloserMockRecorder is the mock recorder for MockSessionCloser.
type MockSessionCloserMockRecorder struct {
	mock *MockSessionCloser
}

// NewMockSessionCloser creates a new mock instance.
func NewMockSessionCloser(ctrl *gomock.Controller) *MockSessionCloser {
	mock := &MockSessionCloser{ctrl: ctrl}
	mock.recorder = &MockSessionCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCloser) EXPECT() *MockSessionCloserMockRecorder {
	return m.recorder
}

// RevokeTokensBySessionIDs mocks base method.
func (m *MockSessionCloser) RevokeTokensBySessionIDs(ctx context.Context, userID uuid.UUID, sessionIDs []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokensBySessionIDs", ctx, userID, sessionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokensBySessionIDs indicates an expected call of RevokeTokensBySessionIDs.
func (mr *MockSessionCloserMockRecorder) RevokeTokensBySessionIDs(ctx, userID, sessionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokensBySessionIDs", reflect.TypeOf((*MockSessionCloser)(nil).RevokeTokensBySessionIDs), ctx, userID, sessionIDs)
}
