// Code generated by MockGen. DO NOT EDIT.
// Source: session_drainer.go
//
// Generated by this command:
//
//	mockgen -source=session_drainer.go -destination=mock/session_drainer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionCleanupQueueConsumer is a mock of sessionCleanupQueueConsumer interface.
type MocksessionCleanupQueueConsumer struct {
	ctrl     *gomock.Controller
	recorder *MocksessionCleanupQueueConsumerMockRecorder
	isgomock struct{}
}

// MocksessionCleanupQueueConsumerMockRecorder is the mock recorder for MocksessionCleanupQueueConsumer.
type MocksessionCleanupQueueConsumerMockRecorder struct {
	mock *MocksessionCleanupQueueConsumer
}

// NewMocksessionCleanupQueueConsumer creates a new mock instance.
func NewMocksessionCleanupQueueConsumer(ctrl *gomock.Controller) *MocksessionCleanupQueueConsumer {
	mock := &MocksessionCleanupQueueConsumer{ctrl: ctrl}
	mock.recorder = &MocksessionCleanupQueueConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionCleanupQueueConsumer) EXPECT() *MocksessionCleanupQueueConsumerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocksessionCleanupQueueConsumer) Delete(ctx context.Context, pks []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocksessionCleanupQueueConsumerMockRecorder) Delete(ctx, pks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocksessionCleanupQueueConsumer)(nil).Delete), ctx, pks)
}

// Fetch mocks base method.
func (m *MocksessionCleanupQueueConsumer) Fetch(ctx context.Context, limit int) ([]entity.SessionPK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, limit)
	ret0, _ := ret[0].([]entity.SessionPK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MocksessionCleanupQueueConsumerMockRecorder) Fetch(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MocksessionCleanupQueueConsumer)(nil).Fetch), ctx, limit)
}

// MockorphanSessionDeleter is a mock of orphanSessionDeleter interface.
type MockorphanSessionDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockorphanSessionDeleterMockRecorder
	isgomock struct{}
}

// MockorphanSessionDeleterMockRecorder is the mock recorder for MockorphanSessionDeleter.
type MockorphanSessionDeleterMockRecorder struct {
	mock *MockorphanSessionDeleter
}

// NewMockorphanSessionDeleter creates a new mock instance.
func NewMockorphanSessionDeleter(ctrl *gomock.Controller) *MockorphanSessionDeleter {
	mock := &MockorphanSessionDeleter{ctrl: ctrl}
	mock.recorder = &MockorphanSessionDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorphanSessionDeleter) EXPECT() *MockorphanSessionDeleterMockRecorder {
	return m.recorder
}

// DeleteOrphaned mocks base method.
func (m *MockorphanSessionDeleter) DeleteOrphaned(ctx context.Context, candidates []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphaned", ctx, candidates)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrphaned indicates an expected call of DeleteOrphaned.
func (mr *MockorphanSessionDeleterMockRecorder) DeleteOrphaned(ctx, candidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphaned", reflect.TypeOf((*MockorphanSessionDeleter)(nil).DeleteOrphaned), ctx, candidates)
}
