// Code generated by MockGen. DO NOT EDIT.
// Source: session_drainer.go
//
// Generated by this command:
//
//	mockgen -source=session_drainer.go -destination=mock/session_drainer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionCleanupQueueConsumer is a mock of SessionCleanupQueueConsumer interface.
type MockSessionCleanupQueueConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCleanupQueueConsumerMockRecorder
	isgomock struct{}
}

// MockSessionCleanupQueueConsumerMockRecorder is the mock recorder for MockSessionCleanupQueueConsumer.
type MockSessionCleanupQueueConsumerMockRecorder struct {
	mock *MockSessionCleanupQueueConsumer
}

// NewMockSessionCleanupQueueConsumer creates a new mock instance.
func NewMockSessionCleanupQueueConsumer(ctrl *gomock.Controller) *MockSessionCleanupQueueConsumer {
	mock := &MockSessionCleanupQueueConsumer{ctrl: ctrl}
	mock.recorder = &MockSessionCleanupQueueConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCleanupQueueConsumer) EXPECT() *MockSessionCleanupQueueConsumerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionCleanupQueueConsumer) Delete(ctx context.Context, pks []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionCleanupQueueConsumerMockRecorder) Delete(ctx, pks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionCleanupQueueConsumer)(nil).Delete), ctx, pks)
}

// Fetch mocks base method.
func (m *MockSessionCleanupQueueConsumer) Fetch(ctx context.Context, limit int) ([]entity.SessionPK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, limit)
	ret0, _ := ret[0].([]entity.SessionPK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSessionCleanupQueueConsumerMockRecorder) Fetch(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSessionCleanupQueueConsumer)(nil).Fetch), ctx, limit)
}

// MockOrphanSessionDeleter is a mock of OrphanSessionDeleter interface.
type MockOrphanSessionDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockOrphanSessionDeleterMockRecorder
	isgomock struct{}
}

// MockOrphanSessionDeleterMockRecorder is the mock recorder for MockOrphanSessionDeleter.
type MockOrphanSessionDeleterMockRecorder struct {
	mock *MockOrphanSessionDeleter
}

// NewMockOrphanSessionDeleter creates a new mock instance.
func NewMockOrphanSessionDeleter(ctrl *gomock.Controller) *MockOrphanSessionDeleter {
	mock := &MockOrphanSessionDeleter{ctrl: ctrl}
	mock.recorder = &MockOrphanSessionDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrphanSessionDeleter) EXPECT() *MockOrphanSessionDeleterMockRecorder {
	return m.recorder
}

// DeleteOrphaned mocks base method.
func (m *MockOrphanSessionDeleter) DeleteOrphaned(ctx context.Context, candidates []entity.SessionPK) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphaned", ctx, candidates)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrphaned indicates an expected call of DeleteOrphaned.
func (mr *MockOrphanSessionDeleterMockRecorder) DeleteOrphaned(ctx, candidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphaned", reflect.TypeOf((*MockOrphanSessionDeleter)(nil).DeleteOrphaned), ctx, candidates)
}
