// Code generated by MockGen. DO NOT EDIT.
// Source: user_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=user_cleaner.go -destination=mock/user_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockuserActivityLogStorage is a mock of userActivityLogStorage interface.
type MockuserActivityLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityLogStorageMockRecorder
	isgomock struct{}
}

// MockuserActivityLogStorageMockRecorder is the mock recorder for MockuserActivityLogStorage.
type MockuserActivityLogStorageMockRecorder struct {
	mock *MockuserActivityLogStorage
}

// NewMockuserActivityLogStorage creates a new mock instance.
func NewMockuserActivityLogStorage(ctrl *gomock.Controller) *MockuserActivityLogStorage {
	mock := &MockuserActivityLogStorage{ctrl: ctrl}
	mock.recorder = &MockuserActivityLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityLogStorage) EXPECT() *MockuserActivityLogStorageMockRecorder {
	return m.recorder
}

// DeleteBeforeDate mocks base method.
func (m *MockuserActivityLogStorage) DeleteBeforeDate(ctx context.Context, datetime time.Time, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeforeDate", ctx, datetime, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBeforeDate indicates an expected call of DeleteBeforeDate.
func (mr *MockuserActivityLogStorageMockRecorder) DeleteBeforeDate(ctx, datetime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeforeDate", reflect.TypeOf((*MockuserActivityLogStorage)(nil).DeleteBeforeDate), ctx, datetime, limit)
}
