// Code generated by MockGen. DO NOT EDIT.
// Source: user_cleaner.go
//
// Generated by this command:
//
//	mockgen -source=user_cleaner.go -destination=mock/user_cleaner.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUserActivityLogStorage is a mock of UserActivityLogStorage interface.
type MockUserActivityLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserActivityLogStorageMockRecorder
	isgomock struct{}
}

// MockUserActivityLogStorageMockRecorder is the mock recorder for MockUserActivityLogStorage.
type MockUserActivityLogStorageMockRecorder struct {
	mock *MockUserActivityLogStorage
}

// NewMockUserActivityLogStorage creates a new mock instance.
func NewMockUserActivityLogStorage(ctrl *gomock.Controller) *MockUserActivityLogStorage {
	mock := &MockUserActivityLogStorage{ctrl: ctrl}
	mock.recorder = &MockUserActivityLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserActivityLogStorage) EXPECT() *MockUserActivityLogStorageMockRecorder {
	return m.recorder
}

// DeleteBeforeDate mocks base method.
func (m *MockUserActivityLogStorage) DeleteBeforeDate(ctx context.Context, datetime time.Time, limit int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBeforeDate", ctx, datetime, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBeforeDate indicates an expected call of DeleteBeforeDate.
func (mr *MockUserActivityLogStorageMockRecorder) DeleteBeforeDate(ctx, datetime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBeforeDate", reflect.TypeOf((*MockUserActivityLogStorage)(nil).DeleteBeforeDate), ctx, datetime, limit)
}
