@startuml
!include <C4/C4_Component>

' mrsettings
!include components/c4/mrsettings/mrsettings_cachegetter.iuml
!include components/c4/mrsettings/mrsettings_loader.iuml
!include components/c4/mrsettings/mrsettings_setter.iuml
!include components/c4/containers/infrastructure/db_abstract.iuml

' scheduler
!include components/c4/scheduler/scheduler_task.iuml

' app
!include components/c4/app/app_component.iuml
!include components/c4/app/app_controller.iuml

@enduml
