// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-core/mraccess (interfaces: RightsGetter)
//
// Generated by this command:
//
//	mockgen -destination=mock/mraccess.go -package=mock github.com/mondegor/go-core/mraccess RightsGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	mraccess "github.com/mondegor/go-core/mraccess"
	gomock "go.uber.org/mock/gomock"
)

// MockRightsGetter is a mock of RightsGetter interface.
type MockRightsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockRightsGetterMockRecorder
	isgomock struct{}
}

// MockRightsGetterMockRecorder is the mock recorder for MockRightsGetter.
type MockRightsGetterMockRecorder struct {
	mock *MockRightsGetter
}

// NewMockRightsGetter creates a new mock instance.
func NewMockRightsGetter(ctrl *gomock.Controller) *MockRightsGetter {
	mock := &MockRightsGetter{ctrl: ctrl}
	mock.recorder = &MockRightsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRightsGetter) EXPECT() *MockRightsGetterMockRecorder {
	return m.recorder
}

// Rights mocks base method.
func (m *MockRightsGetter) Rights(group string) mraccess.RightsChecker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rights", group)
	ret0, _ := ret[0].(mraccess.RightsChecker)
	return ret0
}

// Rights indicates an expected call of Rights.
func (mr *MockRightsGetterMockRecorder) Rights(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rights", reflect.TypeOf((*MockRightsGetter)(nil).Rights), group)
}
