// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrauth (interfaces: AuthTokenFetcher)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrauth.go -package=mock github.com/mondegor/go-components/mrauth AuthTokenFetcher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthTokenFetcher is a mock of AuthTokenFetcher interface.
type MockAuthTokenFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenFetcherMockRecorder
	isgomock struct{}
}

// MockAuthTokenFetcherMockRecorder is the mock recorder for MockAuthTokenFetcher.
type MockAuthTokenFetcherMockRecorder struct {
	mock *MockAuthTokenFetcher
}

// NewMockAuthTokenFetcher creates a new mock instance.
func NewMockAuthTokenFetcher(ctrl *gomock.Controller) *MockAuthTokenFetcher {
	mock := &MockAuthTokenFetcher{ctrl: ctrl}
	mock.recorder = &MockAuthTokenFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenFetcher) EXPECT() *MockAuthTokenFetcherMockRecorder {
	return m.recorder
}

// FetchOneByAccessToken mocks base method.
func (m *MockAuthTokenFetcher) FetchOneByAccessToken(ctx context.Context, accessToken string) (dto.UserScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByAccessToken indicates an expected call of FetchOneByAccessToken.
func (mr *MockAuthTokenFetcherMockRecorder) FetchOneByAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByAccessToken", reflect.TypeOf((*MockAuthTokenFetcher)(nil).FetchOneByAccessToken), ctx, accessToken)
}
