// Code generated by MockGen. DO NOT EDIT.
// Source: auth_user.go
//
// Generated by this command:
//
//	mockgen -source=auth_user.go -destination=mock/auth_user.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	gomock "go.uber.org/mock/gomock"
)

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
	isgomock struct{}
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserStorage) FetchOne(ctx context.Context, userID uuid.UUID) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserStorageMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserStorage)(nil).FetchOne), ctx, userID)
}

// FetchOneByLogin mocks base method.
func (m *MockuserStorage) FetchOneByLogin(ctx context.Context, userLogin contactaddress.ContactAddress) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByLogin", ctx, userLogin)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByLogin indicates an expected call of FetchOneByLogin.
func (mr *MockuserStorageMockRecorder) FetchOneByLogin(ctx, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByLogin", reflect.TypeOf((*MockuserStorage)(nil).FetchOneByLogin), ctx, userLogin)
}

// Insert mocks base method.
func (m *MockuserStorage) Insert(ctx context.Context, row entity.ExtendedUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockuserStorageMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockuserStorage)(nil).Insert), ctx, row)
}

// MockuserRealmStorage is a mock of userRealmStorage interface.
type MockuserRealmStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserRealmStorageMockRecorder
	isgomock struct{}
}

// MockuserRealmStorageMockRecorder is the mock recorder for MockuserRealmStorage.
type MockuserRealmStorageMockRecorder struct {
	mock *MockuserRealmStorage
}

// NewMockuserRealmStorage creates a new mock instance.
func NewMockuserRealmStorage(ctrl *gomock.Controller) *MockuserRealmStorage {
	mock := &MockuserRealmStorage{ctrl: ctrl}
	mock.recorder = &MockuserRealmStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRealmStorage) EXPECT() *MockuserRealmStorageMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserRealmStorage) FetchOne(ctx context.Context, userID uuid.UUID, realmID uint16) (entity.UserRealm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID, realmID)
	ret0, _ := ret[0].(entity.UserRealm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserRealmStorageMockRecorder) FetchOne(ctx, userID, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserRealmStorage)(nil).FetchOne), ctx, userID, realmID)
}

// Insert mocks base method.
func (m *MockuserRealmStorage) Insert(ctx context.Context, row entity.UserRealm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockuserRealmStorageMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockuserRealmStorage)(nil).Insert), ctx, row)
}
