-- --------------------------------------------------------------------------------------------------

CREATE TABLE sample_schema.notifier_templates (
    template_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notifier_templates PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    template_group int2 NOT NULL, -- 1=USERS, 2=ADMINS
    template_name character varying(64) NULL,
    lang_code character(5) NOT NULL, -- en_EN, ru_RU
    template_caption character varying(128) NOT NULL,
    notice_props jsonb NOT NULL,
    notice_vars jsonb NOT NULL, -- cache from notice_props
    template_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_notifier_templates_template_name ON sample_schema.notifier_templates (template_name, lang_code) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE sample_schema.notifier_template_vars (
    var_name character varying(32) CONSTRAINT pk_notifier_template_vars PRIMARY KEY,
    default_value character varying(128) NOT NULL,
    var_description character varying(1024) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_notifier_template_vars_var_name ON sample_schema.notifier_template_vars (var_name);
