// Code generated by MockGen. DO NOT EDIT.
// Source: status_changer.go
//
// Generated by this command:
//
//	mockgen -source=status_changer.go -destination=mock/status_changer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/mondegor/go-components/mrqueue/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockItemStorage is a mock of ItemStorage interface.
type MockItemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockItemStorageMockRecorder
	isgomock struct{}
}

// MockItemStorageMockRecorder is the mock recorder for MockItemStorage.
type MockItemStorageMockRecorder struct {
	mock *MockItemStorage
}

// NewMockItemStorage creates a new mock instance.
func NewMockItemStorage(ctrl *gomock.Controller) *MockItemStorage {
	mock := &MockItemStorage{ctrl: ctrl}
	mock.recorder = &MockItemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemStorage) EXPECT() *MockItemStorageMockRecorder {
	return m.recorder
}

// UpdateStatusProcessingToRetryByTimeout mocks base method.
func (m *MockItemStorage) UpdateStatusProcessingToRetryByTimeout(ctx context.Context, timeout time.Duration, limit int) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusProcessingToRetryByTimeout", ctx, timeout, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusProcessingToRetryByTimeout indicates an expected call of UpdateStatusProcessingToRetryByTimeout.
func (mr *MockItemStorageMockRecorder) UpdateStatusProcessingToRetryByTimeout(ctx, timeout, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusProcessingToRetryByTimeout", reflect.TypeOf((*MockItemStorage)(nil).UpdateStatusProcessingToRetryByTimeout), ctx, timeout, limit)
}

// MockcrashedItemStorage is a mock of crashedItemStorage interface.
type MockcrashedItemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockcrashedItemStorageMockRecorder
	isgomock struct{}
}

// MockcrashedItemStorageMockRecorder is the mock recorder for MockcrashedItemStorage.
type MockcrashedItemStorageMockRecorder struct {
	mock *MockcrashedItemStorage
}

// NewMockcrashedItemStorage creates a new mock instance.
func NewMockcrashedItemStorage(ctrl *gomock.Controller) *MockcrashedItemStorage {
	mock := &MockcrashedItemStorage{ctrl: ctrl}
	mock.recorder = &MockcrashedItemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcrashedItemStorage) EXPECT() *MockcrashedItemStorageMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockcrashedItemStorage) Insert(ctx context.Context, rows []entity.CrashedItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockcrashedItemStorageMockRecorder) Insert(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockcrashedItemStorage)(nil).Insert), ctx, rows)
}
