// Code generated by MockGen. DO NOT EDIT.
// Source: auth_token.go
//
// Generated by this command:
//
//	mockgen -source=auth_token.go -destination=mock/auth_token.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockauthTokenStorage is a mock of authTokenStorage interface.
type MockauthTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockauthTokenStorageMockRecorder
	isgomock struct{}
}

// MockauthTokenStorageMockRecorder is the mock recorder for MockauthTokenStorage.
type MockauthTokenStorageMockRecorder struct {
	mock *MockauthTokenStorage
}

// NewMockauthTokenStorage creates a new mock instance.
func NewMockauthTokenStorage(ctrl *gomock.Controller) *MockauthTokenStorage {
	mock := &MockauthTokenStorage{ctrl: ctrl}
	mock.recorder = &MockauthTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthTokenStorage) EXPECT() *MockauthTokenStorageMockRecorder {
	return m.recorder
}

// FetchLastEnabledPairBySessionID mocks base method.
func (m *MockauthTokenStorage) FetchLastEnabledPairBySessionID(ctx context.Context, userID uuid.UUID, sessionID uint32) (entity.AuthToken, entity.AuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLastEnabledPairBySessionID", ctx, userID, sessionID)
	ret0, _ := ret[0].(entity.AuthToken)
	ret1, _ := ret[1].(entity.AuthToken)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchLastEnabledPairBySessionID indicates an expected call of FetchLastEnabledPairBySessionID.
func (mr *MockauthTokenStorageMockRecorder) FetchLastEnabledPairBySessionID(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLastEnabledPairBySessionID", reflect.TypeOf((*MockauthTokenStorage)(nil).FetchLastEnabledPairBySessionID), ctx, userID, sessionID)
}

// Insert mocks base method.
func (m *MockauthTokenStorage) Insert(ctx context.Context, rows []entity.AuthToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockauthTokenStorageMockRecorder) Insert(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockauthTokenStorage)(nil).Insert), ctx, rows)
}

// RevokeRefresh mocks base method.
func (m *MockauthTokenStorage) RevokeRefresh(ctx context.Context, refreshToken string, grace time.Duration) (dto.UserScopes, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefresh", ctx, refreshToken, grace)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RevokeRefresh indicates an expected call of RevokeRefresh.
func (mr *MockauthTokenStorageMockRecorder) RevokeRefresh(ctx, refreshToken, grace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefresh", reflect.TypeOf((*MockauthTokenStorage)(nil).RevokeRefresh), ctx, refreshToken, grace)
}

// RevokeSessionByRefreshToken mocks base method.
func (m *MockauthTokenStorage) RevokeSessionByRefreshToken(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionByRefreshToken indicates an expected call of RevokeSessionByRefreshToken.
func (mr *MockauthTokenStorageMockRecorder) RevokeSessionByRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByRefreshToken", reflect.TypeOf((*MockauthTokenStorage)(nil).RevokeSessionByRefreshToken), ctx, refreshToken)
}
