// Code generated by MockGen. DO NOT EDIT.
// Source: change_email.go
//
// Generated by this command:
//
//	mockgen -source=change_email.go -destination=mock/change_email.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockuserEmailChanger is a mock of userEmailChanger interface.
type MockuserEmailChanger struct {
	ctrl     *gomock.Controller
	recorder *MockuserEmailChangerMockRecorder
	isgomock struct{}
}

// MockuserEmailChangerMockRecorder is the mock recorder for MockuserEmailChanger.
type MockuserEmailChangerMockRecorder struct {
	mock *MockuserEmailChanger
}

// NewMockuserEmailChanger creates a new mock instance.
func NewMockuserEmailChanger(ctrl *gomock.Controller) *MockuserEmailChanger {
	mock := &MockuserEmailChanger{ctrl: ctrl}
	mock.recorder = &MockuserEmailChangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserEmailChanger) EXPECT() *MockuserEmailChangerMockRecorder {
	return m.recorder
}

// UpdateEmail mocks base method.
func (m *MockuserEmailChanger) UpdateEmail(ctx context.Context, userID uuid.UUID, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, userID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockuserEmailChangerMockRecorder) UpdateEmail(ctx, userID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockuserEmailChanger)(nil).UpdateEmail), ctx, userID, value)
}
