// Code generated by MockGen. DO NOT EDIT.
// Source: change_phone.go
//
// Generated by this command:
//
//	mockgen -source=change_phone.go -destination=mock/change_phone.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockuserPhoneChanger is a mock of userPhoneChanger interface.
type MockuserPhoneChanger struct {
	ctrl     *gomock.Controller
	recorder *MockuserPhoneChangerMockRecorder
	isgomock struct{}
}

// MockuserPhoneChangerMockRecorder is the mock recorder for MockuserPhoneChanger.
type MockuserPhoneChangerMockRecorder struct {
	mock *MockuserPhoneChanger
}

// NewMockuserPhoneChanger creates a new mock instance.
func NewMockuserPhoneChanger(ctrl *gomock.Controller) *MockuserPhoneChanger {
	mock := &MockuserPhoneChanger{ctrl: ctrl}
	mock.recorder = &MockuserPhoneChangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserPhoneChanger) EXPECT() *MockuserPhoneChangerMockRecorder {
	return m.recorder
}

// UpdatePhone mocks base method.
func (m *MockuserPhoneChanger) UpdatePhone(ctx context.Context, userID uuid.UUID, value uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePhone", ctx, userID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePhone indicates an expected call of UpdatePhone.
func (mr *MockuserPhoneChangerMockRecorder) UpdatePhone(ctx, userID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePhone", reflect.TypeOf((*MockuserPhoneChanger)(nil).UpdatePhone), ctx, userID, value)
}
