// Code generated by MockGen. DO NOT EDIT.
// Source: disable_2fa.go
//
// Generated by this command:
//
//	mockgen -source=disable_2fa.go -destination=mock/disable_2fa.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// Mockuser2faDisabler is a mock of user2faDisabler interface.
type Mockuser2faDisabler struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faDisablerMockRecorder
	isgomock struct{}
}

// Mockuser2faDisablerMockRecorder is the mock recorder for Mockuser2faDisabler.
type Mockuser2faDisablerMockRecorder struct {
	mock *Mockuser2faDisabler
}

// NewMockuser2faDisabler creates a new mock instance.
func NewMockuser2faDisabler(ctrl *gomock.Controller) *Mockuser2faDisabler {
	mock := &Mockuser2faDisabler{ctrl: ctrl}
	mock.recorder = &Mockuser2faDisablerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faDisabler) EXPECT() *Mockuser2faDisablerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockuser2faDisabler) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *Mockuser2faDisablerMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockuser2faDisabler)(nil).Delete), ctx, userID)
}
