// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock/handler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	logreason "github.com/mondegor/go-components/mrauth/enum/logreason"
	conv "github.com/mondegor/go-core/util/conv"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationRevoker is a mock of operationRevoker interface.
type MockoperationRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockoperationRevokerMockRecorder
	isgomock struct{}
}

// MockoperationRevokerMockRecorder is the mock recorder for MockoperationRevoker.
type MockoperationRevokerMockRecorder struct {
	mock *MockoperationRevoker
}

// NewMockoperationRevoker creates a new mock instance.
func NewMockoperationRevoker(ctrl *gomock.Controller) *MockoperationRevoker {
	mock := &MockoperationRevoker{ctrl: ctrl}
	mock.recorder = &MockoperationRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationRevoker) EXPECT() *MockoperationRevokerMockRecorder {
	return m.recorder
}

// RevokeAll mocks base method.
func (m *MockoperationRevoker) RevokeAll(ctx context.Context, actor dto.ActorMeta, reason logreason.Enum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAll", ctx, actor, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAll indicates an expected call of RevokeAll.
func (mr *MockoperationRevokerMockRecorder) RevokeAll(ctx, actor, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAll", reflect.TypeOf((*MockoperationRevoker)(nil).RevokeAll), ctx, actor, reason)
}

// MocksecurityLogStorage is a mock of securityLogStorage interface.
type MocksecurityLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MocksecurityLogStorageMockRecorder
	isgomock struct{}
}

// MocksecurityLogStorageMockRecorder is the mock recorder for MocksecurityLogStorage.
type MocksecurityLogStorageMockRecorder struct {
	mock *MocksecurityLogStorage
}

// NewMocksecurityLogStorage creates a new mock instance.
func NewMocksecurityLogStorage(ctrl *gomock.Controller) *MocksecurityLogStorage {
	mock := &MocksecurityLogStorage{ctrl: ctrl}
	mock.recorder = &MocksecurityLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecurityLogStorage) EXPECT() *MocksecurityLogStorageMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MocksecurityLogStorage) Insert(ctx context.Context, row entity.SecurityLogEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MocksecurityLogStorageMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MocksecurityLogStorage)(nil).Insert), ctx, row)
}

// MockactorPropsBuilder is a mock of actorPropsBuilder interface.
type MockactorPropsBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockactorPropsBuilderMockRecorder
	isgomock struct{}
}

// MockactorPropsBuilderMockRecorder is the mock recorder for MockactorPropsBuilder.
type MockactorPropsBuilderMockRecorder struct {
	mock *MockactorPropsBuilder
}

// NewMockactorPropsBuilder creates a new mock instance.
func NewMockactorPropsBuilder(ctrl *gomock.Controller) *MockactorPropsBuilder {
	mock := &MockactorPropsBuilder{ctrl: ctrl}
	mock.recorder = &MockactorPropsBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactorPropsBuilder) EXPECT() *MockactorPropsBuilderMockRecorder {
	return m.recorder
}

// With mocks base method.
func (m *MockactorPropsBuilder) With(actor dto.ActorMeta, props conv.Group) conv.Group {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "With", actor, props)
	ret0, _ := ret[0].(conv.Group)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockactorPropsBuilderMockRecorder) With(actor, props any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockactorPropsBuilder)(nil).With), actor, props)
}
