// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrnotifier (interfaces: NoteProducer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrnotifier.go -package=mock github.com/mondegor/go-components/mrnotifier NoteProducer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNoteProducer is a mock of NoteProducer interface.
type MockNoteProducer struct {
	ctrl     *gomock.Controller
	recorder *MockNoteProducerMockRecorder
	isgomock struct{}
}

// MockNoteProducerMockRecorder is the mock recorder for MockNoteProducer.
type MockNoteProducerMockRecorder struct {
	mock *MockNoteProducer
}

// NewMockNoteProducer creates a new mock instance.
func NewMockNoteProducer(ctrl *gomock.Controller) *MockNoteProducer {
	mock := &MockNoteProducer{ctrl: ctrl}
	mock.recorder = &MockNoteProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteProducer) EXPECT() *MockNoteProducerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockNoteProducer) Send(ctx context.Context, key string, props map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, key, props)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNoteProducerMockRecorder) Send(ctx, key, props any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNoteProducer)(nil).Send), ctx, key, props)
}
