// Code generated by MockGen. DO NOT EDIT.
// Source: opener.go
//
// Generated by this command:
//
//	mockgen -source=opener.go -destination=mock/opener.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	operationtype "github.com/mondegor/go-components/mrauth/enum/operationtype"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationOpenerStorage is a mock of operationOpenerStorage interface.
type MockoperationOpenerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockoperationOpenerStorageMockRecorder
	isgomock struct{}
}

// MockoperationOpenerStorageMockRecorder is the mock recorder for MockoperationOpenerStorage.
type MockoperationOpenerStorageMockRecorder struct {
	mock *MockoperationOpenerStorage
}

// NewMockoperationOpenerStorage creates a new mock instance.
func NewMockoperationOpenerStorage(ctrl *gomock.Controller) *MockoperationOpenerStorage {
	mock := &MockoperationOpenerStorage{ctrl: ctrl}
	mock.recorder = &MockoperationOpenerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationOpenerStorage) EXPECT() *MockoperationOpenerStorageMockRecorder {
	return m.recorder
}

// DeleteByUserIDAndTypes mocks base method.
func (m *MockoperationOpenerStorage) DeleteByUserIDAndTypes(ctx context.Context, userID uuid.UUID, types []operationtype.Enum) ([]operationtype.Enum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndTypes", ctx, userID, types)
	ret0, _ := ret[0].([]operationtype.Enum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUserIDAndTypes indicates an expected call of DeleteByUserIDAndTypes.
func (mr *MockoperationOpenerStorageMockRecorder) DeleteByUserIDAndTypes(ctx, userID, types any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndTypes", reflect.TypeOf((*MockoperationOpenerStorage)(nil).DeleteByUserIDAndTypes), ctx, userID, types)
}

// Insert mocks base method.
func (m *MockoperationOpenerStorage) Insert(ctx context.Context, row secureoperation.SecureOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockoperationOpenerStorageMockRecorder) Insert(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockoperationOpenerStorage)(nil).Insert), ctx, row)
}

// MockoperationLogger is a mock of operationLogger interface.
type MockoperationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLoggerMockRecorder
	isgomock struct{}
}

// MockoperationLoggerMockRecorder is the mock recorder for MockoperationLogger.
type MockoperationLoggerMockRecorder struct {
	mock *MockoperationLogger
}

// NewMockoperationLogger creates a new mock instance.
func NewMockoperationLogger(ctrl *gomock.Controller) *MockoperationLogger {
	mock := &MockoperationLogger{ctrl: ctrl}
	mock.recorder = &MockoperationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogger) EXPECT() *MockoperationLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockoperationLogger) Log(ctx context.Context, entry entity.SecureOperationLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, entry)
}

// Log indicates an expected call of Log.
func (mr *MockoperationLoggerMockRecorder) Log(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockoperationLogger)(nil).Log), ctx, entry)
}
