// Code generated by MockGen. DO NOT EDIT.
// Source: revoker.go
//
// Generated by this command:
//
//	mockgen -source=revoker.go -destination=mock/revoker.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	operationtype "github.com/mondegor/go-components/mrauth/enum/operationtype"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationRevokerStorage is a mock of operationRevokerStorage interface.
type MockoperationRevokerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockoperationRevokerStorageMockRecorder
	isgomock struct{}
}

// MockoperationRevokerStorageMockRecorder is the mock recorder for MockoperationRevokerStorage.
type MockoperationRevokerStorageMockRecorder struct {
	mock *MockoperationRevokerStorage
}

// NewMockoperationRevokerStorage creates a new mock instance.
func NewMockoperationRevokerStorage(ctrl *gomock.Controller) *MockoperationRevokerStorage {
	mock := &MockoperationRevokerStorage{ctrl: ctrl}
	mock.recorder = &MockoperationRevokerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationRevokerStorage) EXPECT() *MockoperationRevokerStorageMockRecorder {
	return m.recorder
}

// DeleteByUserID mocks base method.
func (m *MockoperationRevokerStorage) DeleteByUserID(ctx context.Context, userID uuid.UUID) ([]operationtype.Enum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].([]operationtype.Enum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockoperationRevokerStorageMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockoperationRevokerStorage)(nil).DeleteByUserID), ctx, userID)
}
