// Code generated by MockGen. DO NOT EDIT.
// Source: auth_flow.go
//
// Generated by this command:
//
//	mockgen -source=auth_flow.go -destination=mock/auth_flow.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockauthUserService is a mock of authUserService interface.
type MockauthUserService struct {
	ctrl     *gomock.Controller
	recorder *MockauthUserServiceMockRecorder
	isgomock struct{}
}

// MockauthUserServiceMockRecorder is the mock recorder for MockauthUserService.
type MockauthUserServiceMockRecorder struct {
	mock *MockauthUserService
}

// NewMockauthUserService creates a new mock instance.
func NewMockauthUserService(ctrl *gomock.Controller) *MockauthUserService {
	mock := &MockauthUserService{ctrl: ctrl}
	mock.recorder = &MockauthUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthUserService) EXPECT() *MockauthUserServiceMockRecorder {
	return m.recorder
}

// PrepareAuthorization mocks base method.
func (m *MockauthUserService) PrepareAuthorization(ctx context.Context, userID uuid.UUID, in dto.AuthorizeUserOperation) (dto.UserScopes, func(context.Context), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareAuthorization", ctx, userID, in)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(func(context.Context))
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PrepareAuthorization indicates an expected call of PrepareAuthorization.
func (mr *MockauthUserServiceMockRecorder) PrepareAuthorization(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareAuthorization", reflect.TypeOf((*MockauthUserService)(nil).PrepareAuthorization), ctx, userID, in)
}

// ResolveUser mocks base method.
func (m *MockauthUserService) ResolveUser(ctx context.Context, userID uuid.UUID, in dto.CreateUserOperation) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUser", ctx, userID, in)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUser indicates an expected call of ResolveUser.
func (mr *MockauthUserServiceMockRecorder) ResolveUser(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUser", reflect.TypeOf((*MockauthUserService)(nil).ResolveUser), ctx, userID, in)
}
