// Code generated by MockGen. DO NOT EDIT.
// Source: create_session_by_recovery.go
//
// Generated by this command:
//
//	mockgen -source=create_session_by_recovery.go -destination=mock/create_session_by_recovery.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockcreateSessionByRecoveryOperation is a mock of createSessionByRecoveryOperation interface.
type MockcreateSessionByRecoveryOperation struct {
	ctrl     *gomock.Controller
	recorder *MockcreateSessionByRecoveryOperationMockRecorder
	isgomock struct{}
}

// MockcreateSessionByRecoveryOperationMockRecorder is the mock recorder for MockcreateSessionByRecoveryOperation.
type MockcreateSessionByRecoveryOperationMockRecorder struct {
	mock *MockcreateSessionByRecoveryOperation
}

// NewMockcreateSessionByRecoveryOperation creates a new mock instance.
func NewMockcreateSessionByRecoveryOperation(ctrl *gomock.Controller) *MockcreateSessionByRecoveryOperation {
	mock := &MockcreateSessionByRecoveryOperation{ctrl: ctrl}
	mock.recorder = &MockcreateSessionByRecoveryOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateSessionByRecoveryOperation) EXPECT() *MockcreateSessionByRecoveryOperationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcreateSessionByRecoveryOperation) Create(user2FA dto.User2FA, realm, langCode string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA, realm, langCode)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcreateSessionByRecoveryOperationMockRecorder) Create(user2FA, realm, langCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcreateSessionByRecoveryOperation)(nil).Create), user2FA, realm, langCode)
}

// Name mocks base method.
func (m *MockcreateSessionByRecoveryOperation) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockcreateSessionByRecoveryOperationMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockcreateSessionByRecoveryOperation)(nil).Name))
}
