// Code generated by MockGen. DO NOT EDIT.
// Source: create_user.go
//
// Generated by this command:
//
//	mockgen -source=create_user.go -destination=mock/create_user.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	mrtype "github.com/mondegor/go-core/mrtype"
	gomock "go.uber.org/mock/gomock"
)

// MockcreateUserOperation is a mock of createUserOperation interface.
type MockcreateUserOperation struct {
	ctrl     *gomock.Controller
	recorder *MockcreateUserOperationMockRecorder
	isgomock struct{}
}

// MockcreateUserOperationMockRecorder is the mock recorder for MockcreateUserOperation.
type MockcreateUserOperationMockRecorder struct {
	mock *MockcreateUserOperation
}

// NewMockcreateUserOperation creates a new mock instance.
func NewMockcreateUserOperation(ctrl *gomock.Controller) *MockcreateUserOperation {
	mock := &MockcreateUserOperation{ctrl: ctrl}
	mock.recorder = &MockcreateUserOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateUserOperation) EXPECT() *MockcreateUserOperationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcreateUserOperation) Create(user2FA dto.User2FA, langCode, timeZone string, address contactaddress.ContactAddress, registeredIP mrtype.DetailedIP) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA, langCode, timeZone, address, registeredIP)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcreateUserOperationMockRecorder) Create(user2FA, langCode, timeZone, address, registeredIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcreateUserOperation)(nil).Create), user2FA, langCode, timeZone, address, registeredIP)
}

// Name mocks base method.
func (m *MockcreateUserOperation) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockcreateUserOperationMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockcreateUserOperation)(nil).Name))
}

// Mockuser2faActionCreator is a mock of user2faActionCreator interface.
type Mockuser2faActionCreator struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faActionCreatorMockRecorder
	isgomock struct{}
}

// Mockuser2faActionCreatorMockRecorder is the mock recorder for Mockuser2faActionCreator.
type Mockuser2faActionCreatorMockRecorder struct {
	mock *Mockuser2faActionCreator
}

// NewMockuser2faActionCreator creates a new mock instance.
func NewMockuser2faActionCreator(ctrl *gomock.Controller) *Mockuser2faActionCreator {
	mock := &Mockuser2faActionCreator{ctrl: ctrl}
	mock.recorder = &Mockuser2faActionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faActionCreator) EXPECT() *Mockuser2faActionCreatorMockRecorder {
	return m.recorder
}

// CreateByUserLogin mocks base method.
func (m *Mockuser2faActionCreator) CreateByUserLogin(ctx context.Context, userLogin contactaddress.ContactAddress) (dto.User2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateByUserLogin", ctx, userLogin)
	ret0, _ := ret[0].(dto.User2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateByUserLogin indicates an expected call of CreateByUserLogin.
func (mr *Mockuser2faActionCreatorMockRecorder) CreateByUserLogin(ctx, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateByUserLogin", reflect.TypeOf((*Mockuser2faActionCreator)(nil).CreateByUserLogin), ctx, userLogin)
}

// MocktimeZoneResolver is a mock of timeZoneResolver interface.
type MocktimeZoneResolver struct {
	ctrl     *gomock.Controller
	recorder *MocktimeZoneResolverMockRecorder
	isgomock struct{}
}

// MocktimeZoneResolverMockRecorder is the mock recorder for MocktimeZoneResolver.
type MocktimeZoneResolverMockRecorder struct {
	mock *MocktimeZoneResolver
}

// NewMocktimeZoneResolver creates a new mock instance.
func NewMocktimeZoneResolver(ctrl *gomock.Controller) *MocktimeZoneResolver {
	mock := &MocktimeZoneResolver{ctrl: ctrl}
	mock.recorder = &MocktimeZoneResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeZoneResolver) EXPECT() *MocktimeZoneResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MocktimeZoneResolver) Resolve(in dto.TimeZoneInfo) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", in)
	ret0, _ := ret[0].(string)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MocktimeZoneResolverMockRecorder) Resolve(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MocktimeZoneResolver)(nil).Resolve), in)
}

// MockoperationLogger is a mock of operationLogger interface.
type MockoperationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLoggerMockRecorder
	isgomock struct{}
}

// MockoperationLoggerMockRecorder is the mock recorder for MockoperationLogger.
type MockoperationLoggerMockRecorder struct {
	mock *MockoperationLogger
}

// NewMockoperationLogger creates a new mock instance.
func NewMockoperationLogger(ctrl *gomock.Controller) *MockoperationLogger {
	mock := &MockoperationLogger{ctrl: ctrl}
	mock.recorder = &MockoperationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogger) EXPECT() *MockoperationLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockoperationLogger) Log(ctx context.Context, entry entity.SecureOperationLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, entry)
}

// Log indicates an expected call of Log.
func (mr *MockoperationLoggerMockRecorder) Log(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockoperationLogger)(nil).Log), ctx, entry)
}
