// Code generated by MockGen. DO NOT EDIT.
// Source: create_session.go
//
// Generated by this command:
//
//	mockgen -source=create_session.go -destination=mock/create_session.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	conv "github.com/mondegor/go-core/util/conv"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationOpener is a mock of operationOpener interface.
type MockoperationOpener struct {
	ctrl     *gomock.Controller
	recorder *MockoperationOpenerMockRecorder
	isgomock struct{}
}

// MockoperationOpenerMockRecorder is the mock recorder for MockoperationOpener.
type MockoperationOpenerMockRecorder struct {
	mock *MockoperationOpener
}

// NewMockoperationOpener creates a new mock instance.
func NewMockoperationOpener(ctrl *gomock.Controller) *MockoperationOpener {
	mock := &MockoperationOpener{ctrl: ctrl}
	mock.recorder = &MockoperationOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationOpener) EXPECT() *MockoperationOpenerMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockoperationOpener) Open(ctx context.Context, actor dto.ActorMeta, op secureoperation.SecureOperation, noteName string, noteProps conv.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, actor, op, noteName, noteProps)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockoperationOpenerMockRecorder) Open(ctx, actor, op, noteName, noteProps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockoperationOpener)(nil).Open), ctx, actor, op, noteName, noteProps)
}

// MockuserLoginChecker is a mock of userLoginChecker interface.
type MockuserLoginChecker struct {
	ctrl     *gomock.Controller
	recorder *MockuserLoginCheckerMockRecorder
	isgomock struct{}
}

// MockuserLoginCheckerMockRecorder is the mock recorder for MockuserLoginChecker.
type MockuserLoginCheckerMockRecorder struct {
	mock *MockuserLoginChecker
}

// NewMockuserLoginChecker creates a new mock instance.
func NewMockuserLoginChecker(ctrl *gomock.Controller) *MockuserLoginChecker {
	mock := &MockuserLoginChecker{ctrl: ctrl}
	mock.recorder = &MockuserLoginCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLoginChecker) EXPECT() *MockuserLoginCheckerMockRecorder {
	return m.recorder
}

// CheckAvailabilityRealm mocks base method.
func (m *MockuserLoginChecker) CheckAvailabilityRealm(ctx context.Context, realm string, userLogin contactaddress.ContactAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityRealm", ctx, realm, userLogin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailabilityRealm indicates an expected call of CheckAvailabilityRealm.
func (mr *MockuserLoginCheckerMockRecorder) CheckAvailabilityRealm(ctx, realm, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityRealm", reflect.TypeOf((*MockuserLoginChecker)(nil).CheckAvailabilityRealm), ctx, realm, userLogin)
}

// MockcreateSessionOperation is a mock of createSessionOperation interface.
type MockcreateSessionOperation struct {
	ctrl     *gomock.Controller
	recorder *MockcreateSessionOperationMockRecorder
	isgomock struct{}
}

// MockcreateSessionOperationMockRecorder is the mock recorder for MockcreateSessionOperation.
type MockcreateSessionOperationMockRecorder struct {
	mock *MockcreateSessionOperation
}

// NewMockcreateSessionOperation creates a new mock instance.
func NewMockcreateSessionOperation(ctrl *gomock.Controller) *MockcreateSessionOperation {
	mock := &MockcreateSessionOperation{ctrl: ctrl}
	mock.recorder = &MockcreateSessionOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateSessionOperation) EXPECT() *MockcreateSessionOperationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcreateSessionOperation) Create(user2FA dto.User2FA, realm, langCode string, address contactaddress.ContactAddress) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user2FA, realm, langCode, address)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcreateSessionOperationMockRecorder) Create(user2FA, realm, langCode, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcreateSessionOperation)(nil).Create), user2FA, realm, langCode, address)
}

// Name mocks base method.
func (m *MockcreateSessionOperation) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockcreateSessionOperationMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockcreateSessionOperation)(nil).Name))
}
