// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrauth (interfaces: User2FAConfirmActionCreator)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrauth.go -package=mock github.com/mondegor/go-components/mrauth User2FAConfirmActionCreator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	gomock "go.uber.org/mock/gomock"
)

// MockUser2FAConfirmActionCreator is a mock of User2FAConfirmActionCreator interface.
type MockUser2FAConfirmActionCreator struct {
	ctrl     *gomock.Controller
	recorder *MockUser2FAConfirmActionCreatorMockRecorder
	isgomock struct{}
}

// MockUser2FAConfirmActionCreatorMockRecorder is the mock recorder for MockUser2FAConfirmActionCreator.
type MockUser2FAConfirmActionCreatorMockRecorder struct {
	mock *MockUser2FAConfirmActionCreator
}

// NewMockUser2FAConfirmActionCreator creates a new mock instance.
func NewMockUser2FAConfirmActionCreator(ctrl *gomock.Controller) *MockUser2FAConfirmActionCreator {
	mock := &MockUser2FAConfirmActionCreator{ctrl: ctrl}
	mock.recorder = &MockUser2FAConfirmActionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser2FAConfirmActionCreator) EXPECT() *MockUser2FAConfirmActionCreatorMockRecorder {
	return m.recorder
}

// CreateByUserID mocks base method.
func (m *MockUser2FAConfirmActionCreator) CreateByUserID(ctx context.Context, userID uuid.UUID) (dto.User2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateByUserID", ctx, userID)
	ret0, _ := ret[0].(dto.User2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateByUserID indicates an expected call of CreateByUserID.
func (mr *MockUser2FAConfirmActionCreatorMockRecorder) CreateByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateByUserID", reflect.TypeOf((*MockUser2FAConfirmActionCreator)(nil).CreateByUserID), ctx, userID)
}

// CreateByUserLogin mocks base method.
func (m *MockUser2FAConfirmActionCreator) CreateByUserLogin(ctx context.Context, userLogin contactaddress.ContactAddress) (dto.User2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateByUserLogin", ctx, userLogin)
	ret0, _ := ret[0].(dto.User2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateByUserLogin indicates an expected call of CreateByUserLogin.
func (mr *MockUser2FAConfirmActionCreatorMockRecorder) CreateByUserLogin(ctx, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateByUserLogin", reflect.TypeOf((*MockUser2FAConfirmActionCreator)(nil).CreateByUserLogin), ctx, userLogin)
}
