// Code generated by MockGen. DO NOT EDIT.
// Source: user_statistic.go
//
// Generated by this command:
//
//	mockgen -source=user_statistic.go -destination=mock/user_statistic.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockuserActivityStatUpdater is a mock of userActivityStatUpdater interface.
type MockuserActivityStatUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityStatUpdaterMockRecorder
	isgomock struct{}
}

// MockuserActivityStatUpdaterMockRecorder is the mock recorder for MockuserActivityStatUpdater.
type MockuserActivityStatUpdaterMockRecorder struct {
	mock *MockuserActivityStatUpdater
}

// NewMockuserActivityStatUpdater creates a new mock instance.
func NewMockuserActivityStatUpdater(ctrl *gomock.Controller) *MockuserActivityStatUpdater {
	mock := &MockuserActivityStatUpdater{ctrl: ctrl}
	mock.recorder = &MockuserActivityStatUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityStatUpdater) EXPECT() *MockuserActivityStatUpdaterMockRecorder {
	return m.recorder
}

// UpdateLastVisited mocks base method.
func (m *MockuserActivityStatUpdater) UpdateLastVisited(ctx context.Context, rows []dto.UserActivityLastVisited) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastVisited", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastVisited indicates an expected call of UpdateLastVisited.
func (mr *MockuserActivityStatUpdaterMockRecorder) UpdateLastVisited(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastVisited", reflect.TypeOf((*MockuserActivityStatUpdater)(nil).UpdateLastVisited), ctx, rows)
}

// MockuserActivityLogStorage is a mock of userActivityLogStorage interface.
type MockuserActivityLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityLogStorageMockRecorder
	isgomock struct{}
}

// MockuserActivityLogStorageMockRecorder is the mock recorder for MockuserActivityLogStorage.
type MockuserActivityLogStorageMockRecorder struct {
	mock *MockuserActivityLogStorage
}

// NewMockuserActivityLogStorage creates a new mock instance.
func NewMockuserActivityLogStorage(ctrl *gomock.Controller) *MockuserActivityLogStorage {
	mock := &MockuserActivityLogStorage{ctrl: ctrl}
	mock.recorder = &MockuserActivityLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityLogStorage) EXPECT() *MockuserActivityLogStorageMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockuserActivityLogStorage) Insert(ctx context.Context, rows []dto.UserActivityLogMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockuserActivityLogStorageMockRecorder) Insert(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockuserActivityLogStorage)(nil).Insert), ctx, rows)
}

// MocksessionLastActivityUpdater is a mock of sessionLastActivityUpdater interface.
type MocksessionLastActivityUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocksessionLastActivityUpdaterMockRecorder
	isgomock struct{}
}

// MocksessionLastActivityUpdaterMockRecorder is the mock recorder for MocksessionLastActivityUpdater.
type MocksessionLastActivityUpdaterMockRecorder struct {
	mock *MocksessionLastActivityUpdater
}

// NewMocksessionLastActivityUpdater creates a new mock instance.
func NewMocksessionLastActivityUpdater(ctrl *gomock.Controller) *MocksessionLastActivityUpdater {
	mock := &MocksessionLastActivityUpdater{ctrl: ctrl}
	mock.recorder = &MocksessionLastActivityUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionLastActivityUpdater) EXPECT() *MocksessionLastActivityUpdaterMockRecorder {
	return m.recorder
}

// UpdateLastActivity mocks base method.
func (m *MocksessionLastActivityUpdater) UpdateLastActivity(ctx context.Context, rows []dto.SessionLastActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActivity", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActivity indicates an expected call of UpdateLastActivity.
func (mr *MocksessionLastActivityUpdaterMockRecorder) UpdateLastActivity(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActivity", reflect.TypeOf((*MocksessionLastActivityUpdater)(nil).UpdateLastActivity), ctx, rows)
}
