// Code generated by MockGen. DO NOT EDIT.
// Source: confirm_operation.go
//
// Generated by this command:
//
//	mockgen -source=confirm_operation.go -destination=mock/confirm_operation.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationConfirmer is a mock of operationConfirmer interface.
type MockoperationConfirmer struct {
	ctrl     *gomock.Controller
	recorder *MockoperationConfirmerMockRecorder
	isgomock struct{}
}

// MockoperationConfirmerMockRecorder is the mock recorder for MockoperationConfirmer.
type MockoperationConfirmerMockRecorder struct {
	mock *MockoperationConfirmer
}

// NewMockoperationConfirmer creates a new mock instance.
func NewMockoperationConfirmer(ctrl *gomock.Controller) *MockoperationConfirmer {
	mock := &MockoperationConfirmer{ctrl: ctrl}
	mock.recorder = &MockoperationConfirmerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationConfirmer) EXPECT() *MockoperationConfirmerMockRecorder {
	return m.recorder
}

// FetchOneForUpdate mocks base method.
func (m *MockoperationConfirmer) FetchOneForUpdate(ctx context.Context, token string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneForUpdate", ctx, token)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneForUpdate indicates an expected call of FetchOneForUpdate.
func (mr *MockoperationConfirmerMockRecorder) FetchOneForUpdate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneForUpdate", reflect.TypeOf((*MockoperationConfirmer)(nil).FetchOneForUpdate), ctx, token)
}

// Replace mocks base method.
func (m *MockoperationConfirmer) Replace(ctx context.Context, currentToken string, row secureoperation.SecureOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, currentToken, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockoperationConfirmerMockRecorder) Replace(ctx, currentToken, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockoperationConfirmer)(nil).Replace), ctx, currentToken, row)
}

// UpdateFailedAttempt mocks base method.
func (m *MockoperationConfirmer) UpdateFailedAttempt(ctx context.Context, token string) (int16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFailedAttempt", ctx, token)
	ret0, _ := ret[0].(int16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFailedAttempt indicates an expected call of UpdateFailedAttempt.
func (mr *MockoperationConfirmerMockRecorder) UpdateFailedAttempt(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedAttempt", reflect.TypeOf((*MockoperationConfirmer)(nil).UpdateFailedAttempt), ctx, token)
}

// MockconfirmOperationPreparer is a mock of confirmOperationPreparer interface.
type MockconfirmOperationPreparer struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmOperationPreparerMockRecorder
	isgomock struct{}
}

// MockconfirmOperationPreparerMockRecorder is the mock recorder for MockconfirmOperationPreparer.
type MockconfirmOperationPreparerMockRecorder struct {
	mock *MockconfirmOperationPreparer
}

// NewMockconfirmOperationPreparer creates a new mock instance.
func NewMockconfirmOperationPreparer(ctrl *gomock.Controller) *MockconfirmOperationPreparer {
	mock := &MockconfirmOperationPreparer{ctrl: ctrl}
	mock.recorder = &MockconfirmOperationPreparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmOperationPreparer) EXPECT() *MockconfirmOperationPreparerMockRecorder {
	return m.recorder
}

// Prepare mocks base method.
func (m *MockconfirmOperationPreparer) Prepare(ctx context.Context, op secureoperation.SecureOperation, confirmCode string) (secureoperation.SecureOperation, func(context.Context) error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, op, confirmCode)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(func(context.Context) error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Prepare indicates an expected call of Prepare.
func (mr *MockconfirmOperationPreparerMockRecorder) Prepare(ctx, op, confirmCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockconfirmOperationPreparer)(nil).Prepare), ctx, op, confirmCode)
}

// MockoperationLogger is a mock of operationLogger interface.
type MockoperationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLoggerMockRecorder
	isgomock struct{}
}

// MockoperationLoggerMockRecorder is the mock recorder for MockoperationLogger.
type MockoperationLoggerMockRecorder struct {
	mock *MockoperationLogger
}

// NewMockoperationLogger creates a new mock instance.
func NewMockoperationLogger(ctrl *gomock.Controller) *MockoperationLogger {
	mock := &MockoperationLogger{ctrl: ctrl}
	mock.recorder = &MockoperationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogger) EXPECT() *MockoperationLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockoperationLogger) Log(ctx context.Context, entry entity.SecureOperationLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, entry)
}

// Log indicates an expected call of Log.
func (mr *MockoperationLoggerMockRecorder) Log(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockoperationLogger)(nil).Log), ctx, entry)
}
