// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-core/mrstorage (interfaces: DBTxManager)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrstorage.go -package=mock github.com/mondegor/go-core/mrstorage DBTxManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	mrstorage "github.com/mondegor/go-core/mrstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockDBTxManager is a mock of DBTxManager interface.
type MockDBTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockDBTxManagerMockRecorder
	isgomock struct{}
}

// MockDBTxManagerMockRecorder is the mock recorder for MockDBTxManager.
type MockDBTxManagerMockRecorder struct {
	mock *MockDBTxManager
}

// NewMockDBTxManager creates a new mock instance.
func NewMockDBTxManager(ctrl *gomock.Controller) *MockDBTxManager {
	mock := &MockDBTxManager{ctrl: ctrl}
	mock.recorder = &MockDBTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBTxManager) EXPECT() *MockDBTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockDBTxManager) Do(ctx context.Context, job func(context.Context) error, opts ...mrstorage.TxOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, job}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Do", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockDBTxManagerMockRecorder) Do(ctx, job any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, job}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDBTxManager)(nil).Do), varargs...)
}
