// Code generated by MockGen. DO NOT EDIT.
// Source: operation_statistic.go
//
// Generated by this command:
//
//	mockgen -source=operation_statistic.go -destination=mock/operation_statistic.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationLogStorage is a mock of operationLogStorage interface.
type MockoperationLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLogStorageMockRecorder
	isgomock struct{}
}

// MockoperationLogStorageMockRecorder is the mock recorder for MockoperationLogStorage.
type MockoperationLogStorageMockRecorder struct {
	mock *MockoperationLogStorage
}

// NewMockoperationLogStorage creates a new mock instance.
func NewMockoperationLogStorage(ctrl *gomock.Controller) *MockoperationLogStorage {
	mock := &MockoperationLogStorage{ctrl: ctrl}
	mock.recorder = &MockoperationLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogStorage) EXPECT() *MockoperationLogStorageMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockoperationLogStorage) Insert(ctx context.Context, rows []entity.SecureOperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockoperationLogStorageMockRecorder) Insert(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockoperationLogStorage)(nil).Insert), ctx, rows)
}
