// Code generated by MockGen. DO NOT EDIT.
// Source: resend_code.go
//
// Generated by this command:
//
//	mockgen -source=resend_code.go -destination=mock/resend_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationResender is a mock of operationResender interface.
type MockoperationResender struct {
	ctrl     *gomock.Controller
	recorder *MockoperationResenderMockRecorder
	isgomock struct{}
}

// MockoperationResenderMockRecorder is the mock recorder for MockoperationResender.
type MockoperationResenderMockRecorder struct {
	mock *MockoperationResender
}

// NewMockoperationResender creates a new mock instance.
func NewMockoperationResender(ctrl *gomock.Controller) *MockoperationResender {
	mock := &MockoperationResender{ctrl: ctrl}
	mock.recorder = &MockoperationResenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationResender) EXPECT() *MockoperationResenderMockRecorder {
	return m.recorder
}

// FetchOneForUpdate mocks base method.
func (m *MockoperationResender) FetchOneForUpdate(ctx context.Context, token string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneForUpdate", ctx, token)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneForUpdate indicates an expected call of FetchOneForUpdate.
func (mr *MockoperationResenderMockRecorder) FetchOneForUpdate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneForUpdate", reflect.TypeOf((*MockoperationResender)(nil).FetchOneForUpdate), ctx, token)
}

// Replace mocks base method.
func (m *MockoperationResender) Replace(ctx context.Context, currentToken string, row secureoperation.SecureOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, currentToken, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockoperationResenderMockRecorder) Replace(ctx, currentToken, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockoperationResender)(nil).Replace), ctx, currentToken, row)
}

// MockresendOperationPreparer is a mock of resendOperationPreparer interface.
type MockresendOperationPreparer struct {
	ctrl     *gomock.Controller
	recorder *MockresendOperationPreparerMockRecorder
	isgomock struct{}
}

// MockresendOperationPreparerMockRecorder is the mock recorder for MockresendOperationPreparer.
type MockresendOperationPreparerMockRecorder struct {
	mock *MockresendOperationPreparer
}

// NewMockresendOperationPreparer creates a new mock instance.
func NewMockresendOperationPreparer(ctrl *gomock.Controller) *MockresendOperationPreparer {
	mock := &MockresendOperationPreparer{ctrl: ctrl}
	mock.recorder = &MockresendOperationPreparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresendOperationPreparer) EXPECT() *MockresendOperationPreparerMockRecorder {
	return m.recorder
}

// Prepare mocks base method.
func (m *MockresendOperationPreparer) Prepare(op secureoperation.SecureOperation) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", op)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockresendOperationPreparerMockRecorder) Prepare(op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockresendOperationPreparer)(nil).Prepare), op)
}
