// Code generated by MockGen. DO NOT EDIT.
// Source: revoke_operation.go
//
// Generated by this command:
//
//	mockgen -source=revoke_operation.go -destination=mock/revoke_operation.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockoperationRevoker is a mock of operationRevoker interface.
type MockoperationRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockoperationRevokerMockRecorder
	isgomock struct{}
}

// MockoperationRevokerMockRecorder is the mock recorder for MockoperationRevoker.
type MockoperationRevokerMockRecorder struct {
	mock *MockoperationRevoker
}

// NewMockoperationRevoker creates a new mock instance.
func NewMockoperationRevoker(ctrl *gomock.Controller) *MockoperationRevoker {
	mock := &MockoperationRevoker{ctrl: ctrl}
	mock.recorder = &MockoperationRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationRevoker) EXPECT() *MockoperationRevokerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockoperationRevoker) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockoperationRevokerMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockoperationRevoker)(nil).Delete), ctx, token)
}

// FetchOne mocks base method.
func (m *MockoperationRevoker) FetchOne(ctx context.Context, token string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, token)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockoperationRevokerMockRecorder) FetchOne(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockoperationRevoker)(nil).FetchOne), ctx, token)
}
