// Code generated by MockGen. DO NOT EDIT.
// Source: verifier.go
//
// Generated by this command:
//
//	mockgen -source=verifier.go -destination=mock/verifier.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// Mockuser2faSource is a mock of user2faSource interface.
type Mockuser2faSource struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faSourceMockRecorder
	isgomock struct{}
}

// Mockuser2faSourceMockRecorder is the mock recorder for Mockuser2faSource.
type Mockuser2faSourceMockRecorder struct {
	mock *Mockuser2faSource
}

// NewMockuser2faSource creates a new mock instance.
func NewMockuser2faSource(ctrl *gomock.Controller) *Mockuser2faSource {
	mock := &Mockuser2faSource{ctrl: ctrl}
	mock.recorder = &Mockuser2faSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faSource) EXPECT() *Mockuser2faSourceMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *Mockuser2faSource) FetchOne(ctx context.Context, userID uuid.UUID) (entity.Auth2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.Auth2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *Mockuser2faSourceMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*Mockuser2faSource)(nil).FetchOne), ctx, userID)
}

// UpdateRecoveryCode mocks base method.
func (m *Mockuser2faSource) UpdateRecoveryCode(ctx context.Context, userID uuid.UUID, hash string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecoveryCode", ctx, userID, hash)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecoveryCode indicates an expected call of UpdateRecoveryCode.
func (mr *Mockuser2faSourceMockRecorder) UpdateRecoveryCode(ctx, userID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecoveryCode", reflect.TypeOf((*Mockuser2faSource)(nil).UpdateRecoveryCode), ctx, userID, hash)
}

// UpdateTOTPStep mocks base method.
func (m *Mockuser2faSource) UpdateTOTPStep(ctx context.Context, userID uuid.UUID, step int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTOTPStep", ctx, userID, step)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTOTPStep indicates an expected call of UpdateTOTPStep.
func (mr *Mockuser2faSourceMockRecorder) UpdateTOTPStep(ctx, userID, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTOTPStep", reflect.TypeOf((*Mockuser2faSource)(nil).UpdateTOTPStep), ctx, userID, step)
}

// MockpasswordComparer is a mock of passwordComparer interface.
type MockpasswordComparer struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordComparerMockRecorder
	isgomock struct{}
}

// MockpasswordComparerMockRecorder is the mock recorder for MockpasswordComparer.
type MockpasswordComparerMockRecorder struct {
	mock *MockpasswordComparer
}

// NewMockpasswordComparer creates a new mock instance.
func NewMockpasswordComparer(ctrl *gomock.Controller) *MockpasswordComparer {
	mock := &MockpasswordComparer{ctrl: ctrl}
	mock.recorder = &MockpasswordComparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordComparer) EXPECT() *MockpasswordComparerMockRecorder {
	return m.recorder
}

// CompareSecretAndHash mocks base method.
func (m *MockpasswordComparer) CompareSecretAndHash(secret, hashedSecret string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareSecretAndHash", secret, hashedSecret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareSecretAndHash indicates an expected call of CompareSecretAndHash.
func (mr *MockpasswordComparerMockRecorder) CompareSecretAndHash(secret, hashedSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareSecretAndHash", reflect.TypeOf((*MockpasswordComparer)(nil).CompareSecretAndHash), secret, hashedSecret)
}

// MocktotpValidator is a mock of totpValidator interface.
type MocktotpValidator struct {
	ctrl     *gomock.Controller
	recorder *MocktotpValidatorMockRecorder
	isgomock struct{}
}

// MocktotpValidatorMockRecorder is the mock recorder for MocktotpValidator.
type MocktotpValidatorMockRecorder struct {
	mock *MocktotpValidator
}

// NewMocktotpValidator creates a new mock instance.
func NewMocktotpValidator(ctrl *gomock.Controller) *MocktotpValidator {
	mock := &MocktotpValidator{ctrl: ctrl}
	mock.recorder = &MocktotpValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktotpValidator) EXPECT() *MocktotpValidatorMockRecorder {
	return m.recorder
}

// ValidateCode mocks base method.
func (m *MocktotpValidator) ValidateCode(code, secret string) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCode", code, secret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateCode indicates an expected call of ValidateCode.
func (mr *MocktotpValidatorMockRecorder) ValidateCode(code, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCode", reflect.TypeOf((*MocktotpValidator)(nil).ValidateCode), code, secret)
}

// MockrecoveryAlerter is a mock of recoveryAlerter interface.
type MockrecoveryAlerter struct {
	ctrl     *gomock.Controller
	recorder *MockrecoveryAlerterMockRecorder
	isgomock struct{}
}

// MockrecoveryAlerterMockRecorder is the mock recorder for MockrecoveryAlerter.
type MockrecoveryAlerterMockRecorder struct {
	mock *MockrecoveryAlerter
}

// NewMockrecoveryAlerter creates a new mock instance.
func NewMockrecoveryAlerter(ctrl *gomock.Controller) *MockrecoveryAlerter {
	mock := &MockrecoveryAlerter{ctrl: ctrl}
	mock.recorder = &MockrecoveryAlerterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecoveryAlerter) EXPECT() *MockrecoveryAlerterMockRecorder {
	return m.recorder
}

// SendAlert mocks base method.
func (m *MockrecoveryAlerter) SendAlert(ctx context.Context, userID uuid.UUID, codeRemaining int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAlert", ctx, userID, codeRemaining)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAlert indicates an expected call of SendAlert.
func (mr *MockrecoveryAlerterMockRecorder) SendAlert(ctx, userID, codeRemaining any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlert", reflect.TypeOf((*MockrecoveryAlerter)(nil).SendAlert), ctx, userID, codeRemaining)
}
