// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrauth (interfaces: RealmRegistry)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrauth.go -package=mock github.com/mondegor/go-components/mrauth RealmRegistry
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRealmRegistry is a mock of RealmRegistry interface.
type MockRealmRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRealmRegistryMockRecorder
	isgomock struct{}
}

// MockRealmRegistryMockRecorder is the mock recorder for MockRealmRegistry.
type MockRealmRegistryMockRecorder struct {
	mock *MockRealmRegistry
}

// NewMockRealmRegistry creates a new mock instance.
func NewMockRealmRegistry(ctrl *gomock.Controller) *MockRealmRegistry {
	mock := &MockRealmRegistry{ctrl: ctrl}
	mock.recorder = &MockRealmRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealmRegistry) EXPECT() *MockRealmRegistryMockRecorder {
	return m.recorder
}

// IDByName mocks base method.
func (m *MockRealmRegistry) IDByName(name string) (uint16, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IDByName", name)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IDByName indicates an expected call of IDByName.
func (mr *MockRealmRegistryMockRecorder) IDByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IDByName", reflect.TypeOf((*MockRealmRegistry)(nil).IDByName), name)
}

// NameByID mocks base method.
func (m *MockRealmRegistry) NameByID(id uint16) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// NameByID indicates an expected call of NameByID.
func (mr *MockRealmRegistryMockRecorder) NameByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameByID", reflect.TypeOf((*MockRealmRegistry)(nil).NameByID), id)
}
