// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrserver/request (interfaces: ParserUser,ParserClientIP)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrserver.go -package=mock github.com/mondegor/go-webcore/mrserver/request ParserUser,ParserClientIP
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	netip "net/netip"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	mrtype "github.com/mondegor/go-core/mrtype"
	gomock "go.uber.org/mock/gomock"
)

// MockParserUser is a mock of ParserUser interface.
type MockParserUser struct {
	ctrl     *gomock.Controller
	recorder *MockParserUserMockRecorder
	isgomock struct{}
}

// MockParserUserMockRecorder is the mock recorder for MockParserUser.
type MockParserUserMockRecorder struct {
	mock *MockParserUser
}

// NewMockParserUser creates a new mock instance.
func NewMockParserUser(ctrl *gomock.Controller) *MockParserUser {
	mock := &MockParserUser{ctrl: ctrl}
	mock.recorder = &MockParserUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserUser) EXPECT() *MockParserUserMockRecorder {
	return m.recorder
}

// Location mocks base method.
func (m *MockParserUser) Location(r *http.Request) *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Location", r)
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// Location indicates an expected call of Location.
func (mr *MockParserUserMockRecorder) Location(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Location", reflect.TypeOf((*MockParserUser)(nil).Location), r)
}

// SessionID mocks base method.
func (m *MockParserUser) SessionID(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockParserUserMockRecorder) SessionID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockParserUser)(nil).SessionID), r)
}

// UserAndGroup mocks base method.
func (m *MockParserUser) UserAndGroup(r *http.Request) (uuid.UUID, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAndGroup", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// UserAndGroup indicates an expected call of UserAndGroup.
func (mr *MockParserUserMockRecorder) UserAndGroup(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAndGroup", reflect.TypeOf((*MockParserUser)(nil).UserAndGroup), r)
}

// UserID mocks base method.
func (m *MockParserUser) UserID(r *http.Request) uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID", r)
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockParserUserMockRecorder) UserID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockParserUser)(nil).UserID), r)
}

// MockParserClientIP is a mock of ParserClientIP interface.
type MockParserClientIP struct {
	ctrl     *gomock.Controller
	recorder *MockParserClientIPMockRecorder
	isgomock struct{}
}

// MockParserClientIPMockRecorder is the mock recorder for MockParserClientIP.
type MockParserClientIPMockRecorder struct {
	mock *MockParserClientIP
}

// NewMockParserClientIP creates a new mock instance.
func NewMockParserClientIP(ctrl *gomock.Controller) *MockParserClientIP {
	mock := &MockParserClientIP{ctrl: ctrl}
	mock.recorder = &MockParserClientIPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserClientIP) EXPECT() *MockParserClientIPMockRecorder {
	return m.recorder
}

// DetailedIP mocks base method.
func (m *MockParserClientIP) DetailedIP(r *http.Request) mrtype.DetailedIP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedIP", r)
	ret0, _ := ret[0].(mrtype.DetailedIP)
	return ret0
}

// DetailedIP indicates an expected call of DetailedIP.
func (mr *MockParserClientIPMockRecorder) DetailedIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedIP", reflect.TypeOf((*MockParserClientIP)(nil).DetailedIP), r)
}

// RealIP mocks base method.
func (m *MockParserClientIP) RealIP(r *http.Request) netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealIP", r)
	ret0, _ := ret[0].(netip.Addr)
	return ret0
}

// RealIP indicates an expected call of RealIP.
func (mr *MockParserClientIPMockRecorder) RealIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealIP", reflect.TypeOf((*MockParserClientIP)(nil).RealIP), r)
}
