// Code generated by MockGen. DO NOT EDIT.
// Source: user_email.go
//
// Generated by this command:
//
//	mockgen -source=user_email.go -destination=mock/user_email.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserFetcher is a mock of userFetcher interface.
type MockuserFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuserFetcherMockRecorder
	isgomock struct{}
}

// MockuserFetcherMockRecorder is the mock recorder for MockuserFetcher.
type MockuserFetcherMockRecorder struct {
	mock *MockuserFetcher
}

// NewMockuserFetcher creates a new mock instance.
func NewMockuserFetcher(ctrl *gomock.Controller) *MockuserFetcher {
	mock := &MockuserFetcher{ctrl: ctrl}
	mock.recorder = &MockuserFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserFetcher) EXPECT() *MockuserFetcherMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserFetcher) FetchOne(ctx context.Context, userID uuid.UUID) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserFetcherMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserFetcher)(nil).FetchOne), ctx, userID)
}
