// Code generated by MockGen. DO NOT EDIT.
// Source: status_changer.go
//
// Generated by this command:
//
//	mockgen -source=status_changer.go -destination=mock/status_changer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockItemStorage is a mock of ItemStorage interface.
type MockItemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockItemStorageMockRecorder
	isgomock struct{}
}

// MockItemStorageMockRecorder is the mock recorder for MockItemStorage.
type MockItemStorageMockRecorder struct {
	mock *MockItemStorage
}

// NewMockItemStorage creates a new mock instance.
func NewMockItemStorage(ctrl *gomock.Controller) *MockItemStorage {
	mock := &MockItemStorage{ctrl: ctrl}
	mock.recorder = &MockItemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemStorage) EXPECT() *MockItemStorageMockRecorder {
	return m.recorder
}

// UpdateStatusRetryToReady mocks base method.
func (m *MockItemStorage) UpdateStatusRetryToReady(ctx context.Context, delayed time.Duration, limit int) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusRetryToReady", ctx, delayed, limit)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusRetryToReady indicates an expected call of UpdateStatusRetryToReady.
func (mr *MockItemStorageMockRecorder) UpdateStatusRetryToReady(ctx, delayed, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusRetryToReady", reflect.TypeOf((*MockItemStorage)(nil).UpdateStatusRetryToReady), ctx, delayed, limit)
}
