// Code generated by MockGen. DO NOT EDIT.
// Source: confirm_2fa.go
//
// Generated by this command:
//
//	mockgen -source=confirm_2fa.go -destination=mock/confirm_2fa.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	auth2fatype "github.com/mondegor/go-components/mrauth/enum/auth2fatype"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
	isgomock struct{}
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserStorage) FetchOne(ctx context.Context, userID uuid.UUID) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserStorageMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserStorage)(nil).FetchOne), ctx, userID)
}

// FetchOneByLogin mocks base method.
func (m *MockuserStorage) FetchOneByLogin(ctx context.Context, userLogin contactaddress.ContactAddress) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByLogin", ctx, userLogin)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByLogin indicates an expected call of FetchOneByLogin.
func (mr *MockuserStorageMockRecorder) FetchOneByLogin(ctx, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByLogin", reflect.TypeOf((*MockuserStorage)(nil).FetchOneByLogin), ctx, userLogin)
}

// Mockuser2faStorage is a mock of user2faStorage interface.
type Mockuser2faStorage struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faStorageMockRecorder
	isgomock struct{}
}

// Mockuser2faStorageMockRecorder is the mock recorder for Mockuser2faStorage.
type Mockuser2faStorageMockRecorder struct {
	mock *Mockuser2faStorage
}

// NewMockuser2faStorage creates a new mock instance.
func NewMockuser2faStorage(ctrl *gomock.Controller) *Mockuser2faStorage {
	mock := &Mockuser2faStorage{ctrl: ctrl}
	mock.recorder = &Mockuser2faStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faStorage) EXPECT() *Mockuser2faStorageMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *Mockuser2faStorage) FetchOne(ctx context.Context, userID uuid.UUID) (entity.Auth2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.Auth2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *Mockuser2faStorageMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*Mockuser2faStorage)(nil).FetchOne), ctx, userID)
}

// MockfactoryConfirmAction2FA is a mock of factoryConfirmAction2FA interface.
type MockfactoryConfirmAction2FA struct {
	ctrl     *gomock.Controller
	recorder *MockfactoryConfirmAction2FAMockRecorder
	isgomock struct{}
}

// MockfactoryConfirmAction2FAMockRecorder is the mock recorder for MockfactoryConfirmAction2FA.
type MockfactoryConfirmAction2FAMockRecorder struct {
	mock *MockfactoryConfirmAction2FA
}

// NewMockfactoryConfirmAction2FA creates a new mock instance.
func NewMockfactoryConfirmAction2FA(ctrl *gomock.Controller) *MockfactoryConfirmAction2FA {
	mock := &MockfactoryConfirmAction2FA{ctrl: ctrl}
	mock.recorder = &MockfactoryConfirmAction2FAMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfactoryConfirmAction2FA) EXPECT() *MockfactoryConfirmAction2FAMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockfactoryConfirmAction2FA) Create(auth2fa auth2fatype.Enum, secret string) (secureoperation.ConfirmAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", auth2fa, secret)
	ret0, _ := ret[0].(secureoperation.ConfirmAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockfactoryConfirmAction2FAMockRecorder) Create(auth2fa, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfactoryConfirmAction2FA)(nil).Create), auth2fa, secret)
}
