// Code generated by MockGen. DO NOT EDIT.
// Source: user_info.go
//
// Generated by this command:
//
//	mockgen -source=user_info.go -destination=mock/user_info.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserFetcher is a mock of userFetcher interface.
type MockuserFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuserFetcherMockRecorder
	isgomock struct{}
}

// MockuserFetcherMockRecorder is the mock recorder for MockuserFetcher.
type MockuserFetcherMockRecorder struct {
	mock *MockuserFetcher
}

// NewMockuserFetcher creates a new mock instance.
func NewMockuserFetcher(ctrl *gomock.Controller) *MockuserFetcher {
	mock := &MockuserFetcher{ctrl: ctrl}
	mock.recorder = &MockuserFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserFetcher) EXPECT() *MockuserFetcherMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserFetcher) FetchOne(ctx context.Context, userID uuid.UUID) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserFetcherMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserFetcher)(nil).FetchOne), ctx, userID)
}

// Mockuser2faFetcher is a mock of user2faFetcher interface.
type Mockuser2faFetcher struct {
	ctrl     *gomock.Controller
	recorder *Mockuser2faFetcherMockRecorder
	isgomock struct{}
}

// Mockuser2faFetcherMockRecorder is the mock recorder for Mockuser2faFetcher.
type Mockuser2faFetcherMockRecorder struct {
	mock *Mockuser2faFetcher
}

// NewMockuser2faFetcher creates a new mock instance.
func NewMockuser2faFetcher(ctrl *gomock.Controller) *Mockuser2faFetcher {
	mock := &Mockuser2faFetcher{ctrl: ctrl}
	mock.recorder = &Mockuser2faFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockuser2faFetcher) EXPECT() *Mockuser2faFetcherMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *Mockuser2faFetcher) FetchOne(ctx context.Context, userID uuid.UUID) (entity.Auth2FA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID)
	ret0, _ := ret[0].(entity.Auth2FA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *Mockuser2faFetcherMockRecorder) FetchOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*Mockuser2faFetcher)(nil).FetchOne), ctx, userID)
}

// MockuserActivityStatFetcher is a mock of userActivityStatFetcher interface.
type MockuserActivityStatFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityStatFetcherMockRecorder
	isgomock struct{}
}

// MockuserActivityStatFetcherMockRecorder is the mock recorder for MockuserActivityStatFetcher.
type MockuserActivityStatFetcherMockRecorder struct {
	mock *MockuserActivityStatFetcher
}

// NewMockuserActivityStatFetcher creates a new mock instance.
func NewMockuserActivityStatFetcher(ctrl *gomock.Controller) *MockuserActivityStatFetcher {
	mock := &MockuserActivityStatFetcher{ctrl: ctrl}
	mock.recorder = &MockuserActivityStatFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityStatFetcher) EXPECT() *MockuserActivityStatFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockuserActivityStatFetcher) Fetch(ctx context.Context, userID uuid.UUID) ([]entity.UserActivityStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, userID)
	ret0, _ := ret[0].([]entity.UserActivityStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockuserActivityStatFetcherMockRecorder) Fetch(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockuserActivityStatFetcher)(nil).Fetch), ctx, userID)
}

// MockuserRealmFetcher is a mock of userRealmFetcher interface.
type MockuserRealmFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuserRealmFetcherMockRecorder
	isgomock struct{}
}

// MockuserRealmFetcherMockRecorder is the mock recorder for MockuserRealmFetcher.
type MockuserRealmFetcherMockRecorder struct {
	mock *MockuserRealmFetcher
}

// NewMockuserRealmFetcher creates a new mock instance.
func NewMockuserRealmFetcher(ctrl *gomock.Controller) *MockuserRealmFetcher {
	mock := &MockuserRealmFetcher{ctrl: ctrl}
	mock.recorder = &MockuserRealmFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRealmFetcher) EXPECT() *MockuserRealmFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockuserRealmFetcher) Fetch(ctx context.Context, userID uuid.UUID) ([]entity.UserRealm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, userID)
	ret0, _ := ret[0].([]entity.UserRealm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockuserRealmFetcherMockRecorder) Fetch(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockuserRealmFetcher)(nil).Fetch), ctx, userID)
}
