// Code generated by MockGen. DO NOT EDIT.
// Source: change_totp.go
//
// Generated by this command:
//
//	mockgen -source=change_totp.go -destination=mock/change_totp.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktotpSecretGenerator is a mock of totpSecretGenerator interface.
type MocktotpSecretGenerator struct {
	ctrl     *gomock.Controller
	recorder *MocktotpSecretGeneratorMockRecorder
	isgomock struct{}
}

// MocktotpSecretGeneratorMockRecorder is the mock recorder for MocktotpSecretGenerator.
type MocktotpSecretGeneratorMockRecorder struct {
	mock *MocktotpSecretGenerator
}

// NewMocktotpSecretGenerator creates a new mock instance.
func NewMocktotpSecretGenerator(ctrl *gomock.Controller) *MocktotpSecretGenerator {
	mock := &MocktotpSecretGenerator{ctrl: ctrl}
	mock.recorder = &MocktotpSecretGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktotpSecretGenerator) EXPECT() *MocktotpSecretGeneratorMockRecorder {
	return m.recorder
}

// GenerateSecret mocks base method.
func (m *MocktotpSecretGenerator) GenerateSecret(accountName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecret", accountName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecret indicates an expected call of GenerateSecret.
func (mr *MocktotpSecretGeneratorMockRecorder) GenerateSecret(accountName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecret", reflect.TypeOf((*MocktotpSecretGenerator)(nil).GenerateSecret), accountName)
}
