// Code generated by MockGen. DO NOT EDIT.
// Source: node_mover.go
//
// Generated by this command:
//
//	mockgen -source=node_mover.go -destination=mock/node_mover.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrordering/entity"
	mrentity "github.com/mondegor/go-core/mrentity"
	mrstorage "github.com/mondegor/go-core/mrstorage"
	gomock "go.uber.org/mock/gomock"
)

// MocknodeStorage is a mock of nodeStorage interface.
type MocknodeStorage struct {
	ctrl     *gomock.Controller
	recorder *MocknodeStorageMockRecorder
	isgomock struct{}
}

// MocknodeStorageMockRecorder is the mock recorder for MocknodeStorage.
type MocknodeStorageMockRecorder struct {
	mock *MocknodeStorage
}

// NewMocknodeStorage creates a new mock instance.
func NewMocknodeStorage(ctrl *gomock.Controller) *MocknodeStorage {
	mock := &MocknodeStorage{ctrl: ctrl}
	mock.recorder = &MocknodeStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknodeStorage) EXPECT() *MocknodeStorageMockRecorder {
	return m.recorder
}

// FetchFirstNode mocks base method.
func (m *MocknodeStorage) FetchFirstNode(ctx context.Context, condition mrstorage.SQLPartFunc) (entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFirstNode", ctx, condition)
	ret0, _ := ret[0].(entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFirstNode indicates an expected call of FetchFirstNode.
func (mr *MocknodeStorageMockRecorder) FetchFirstNode(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFirstNode", reflect.TypeOf((*MocknodeStorage)(nil).FetchFirstNode), ctx, condition)
}

// FetchLastNode mocks base method.
func (m *MocknodeStorage) FetchLastNode(ctx context.Context, condition mrstorage.SQLPartFunc) (entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLastNode", ctx, condition)
	ret0, _ := ret[0].(entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLastNode indicates an expected call of FetchLastNode.
func (mr *MocknodeStorageMockRecorder) FetchLastNode(ctx, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLastNode", reflect.TypeOf((*MocknodeStorage)(nil).FetchLastNode), ctx, condition)
}

// FetchNode mocks base method.
func (m *MocknodeStorage) FetchNode(ctx context.Context, rowID uint64, condition mrstorage.SQLPartFunc) (entity.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNode", ctx, rowID, condition)
	ret0, _ := ret[0].(entity.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNode indicates an expected call of FetchNode.
func (mr *MocknodeStorageMockRecorder) FetchNode(ctx, rowID, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNode", reflect.TypeOf((*MocknodeStorage)(nil).FetchNode), ctx, rowID, condition)
}

// RecalcOrderIndex mocks base method.
func (m *MocknodeStorage) RecalcOrderIndex(ctx context.Context, minBorder, step uint64, condition mrstorage.SQLPartFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalcOrderIndex", ctx, minBorder, step, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalcOrderIndex indicates an expected call of RecalcOrderIndex.
func (mr *MocknodeStorageMockRecorder) RecalcOrderIndex(ctx, minBorder, step, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalcOrderIndex", reflect.TypeOf((*MocknodeStorage)(nil).RecalcOrderIndex), ctx, minBorder, step, condition)
}

// UpdateNode mocks base method.
func (m *MocknodeStorage) UpdateNode(ctx context.Context, row entity.Node, condition mrstorage.SQLPartFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", ctx, row, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MocknodeStorageMockRecorder) UpdateNode(ctx, row, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MocknodeStorage)(nil).UpdateNode), ctx, row, condition)
}

// UpdateNodeNextID mocks base method.
func (m *MocknodeStorage) UpdateNodeNextID(ctx context.Context, rowID uint64, nextID mrentity.ZeronullUint64, condition mrstorage.SQLPartFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeNextID", ctx, rowID, nextID, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodeNextID indicates an expected call of UpdateNodeNextID.
func (mr *MocknodeStorageMockRecorder) UpdateNodeNextID(ctx, rowID, nextID, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeNextID", reflect.TypeOf((*MocknodeStorage)(nil).UpdateNodeNextID), ctx, rowID, nextID, condition)
}

// UpdateNodePrevID mocks base method.
func (m *MocknodeStorage) UpdateNodePrevID(ctx context.Context, rowID uint64, prevID mrentity.ZeronullUint64, condition mrstorage.SQLPartFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodePrevID", ctx, rowID, prevID, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodePrevID indicates an expected call of UpdateNodePrevID.
func (mr *MocknodeStorageMockRecorder) UpdateNodePrevID(ctx, rowID, prevID, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodePrevID", reflect.TypeOf((*MocknodeStorage)(nil).UpdateNodePrevID), ctx, rowID, prevID, condition)
}
