// Code generated by MockGen. DO NOT EDIT.
// Source: session_list.go
//
// Generated by this command:
//
//	mockgen -source=session_list.go -destination=mock/session_list.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionLister is a mock of sessionLister interface.
type MocksessionLister struct {
	ctrl     *gomock.Controller
	recorder *MocksessionListerMockRecorder
	isgomock struct{}
}

// MocksessionListerMockRecorder is the mock recorder for MocksessionLister.
type MocksessionListerMockRecorder struct {
	mock *MocksessionLister
}

// NewMocksessionLister creates a new mock instance.
func NewMocksessionLister(ctrl *gomock.Controller) *MocksessionLister {
	mock := &MocksessionLister{ctrl: ctrl}
	mock.recorder = &MocksessionListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionLister) EXPECT() *MocksessionListerMockRecorder {
	return m.recorder
}

// FetchOrderedListByUserIDAndSessionIDs mocks base method.
func (m *MocksessionLister) FetchOrderedListByUserIDAndSessionIDs(ctx context.Context, userID uuid.UUID, sessionIDs []uint32, limit int) ([]entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOrderedListByUserIDAndSessionIDs", ctx, userID, sessionIDs, limit)
	ret0, _ := ret[0].([]entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOrderedListByUserIDAndSessionIDs indicates an expected call of FetchOrderedListByUserIDAndSessionIDs.
func (mr *MocksessionListerMockRecorder) FetchOrderedListByUserIDAndSessionIDs(ctx, userID, sessionIDs, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOrderedListByUserIDAndSessionIDs", reflect.TypeOf((*MocksessionLister)(nil).FetchOrderedListByUserIDAndSessionIDs), ctx, userID, sessionIDs, limit)
}

// MockopenSessionFetcher is a mock of openSessionFetcher interface.
type MockopenSessionFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockopenSessionFetcherMockRecorder
	isgomock struct{}
}

// MockopenSessionFetcherMockRecorder is the mock recorder for MockopenSessionFetcher.
type MockopenSessionFetcherMockRecorder struct {
	mock *MockopenSessionFetcher
}

// NewMockopenSessionFetcher creates a new mock instance.
func NewMockopenSessionFetcher(ctrl *gomock.Controller) *MockopenSessionFetcher {
	mock := &MockopenSessionFetcher{ctrl: ctrl}
	mock.recorder = &MockopenSessionFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockopenSessionFetcher) EXPECT() *MockopenSessionFetcherMockRecorder {
	return m.recorder
}

// FetchOpenSessionIDs mocks base method.
func (m *MockopenSessionFetcher) FetchOpenSessionIDs(ctx context.Context, userID uuid.UUID, realmID uint16) ([]uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOpenSessionIDs", ctx, userID, realmID)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOpenSessionIDs indicates an expected call of FetchOpenSessionIDs.
func (mr *MockopenSessionFetcherMockRecorder) FetchOpenSessionIDs(ctx, userID, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOpenSessionIDs", reflect.TypeOf((*MockopenSessionFetcher)(nil).FetchOpenSessionIDs), ctx, userID, realmID)
}

// MocksessionCloser is a mock of sessionCloser interface.
type MocksessionCloser struct {
	ctrl     *gomock.Controller
	recorder *MocksessionCloserMockRecorder
	isgomock struct{}
}

// MocksessionCloserMockRecorder is the mock recorder for MocksessionCloser.
type MocksessionCloserMockRecorder struct {
	mock *MocksessionCloser
}

// NewMocksessionCloser creates a new mock instance.
func NewMocksessionCloser(ctrl *gomock.Controller) *MocksessionCloser {
	mock := &MocksessionCloser{ctrl: ctrl}
	mock.recorder = &MocksessionCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionCloser) EXPECT() *MocksessionCloserMockRecorder {
	return m.recorder
}

// RevokeTokensBySessionIDs mocks base method.
func (m *MocksessionCloser) RevokeTokensBySessionIDs(ctx context.Context, userID uuid.UUID, sessionIDs []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokensBySessionIDs", ctx, userID, sessionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokensBySessionIDs indicates an expected call of RevokeTokensBySessionIDs.
func (mr *MocksessionCloserMockRecorder) RevokeTokensBySessionIDs(ctx, userID, sessionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokensBySessionIDs", reflect.TypeOf((*MocksessionCloser)(nil).RevokeTokensBySessionIDs), ctx, userID, sessionIDs)
}

// MocksessionResolver is a mock of sessionResolver interface.
type MocksessionResolver struct {
	ctrl     *gomock.Controller
	recorder *MocksessionResolverMockRecorder
	isgomock struct{}
}

// MocksessionResolverMockRecorder is the mock recorder for MocksessionResolver.
type MocksessionResolverMockRecorder struct {
	mock *MocksessionResolver
}

// NewMocksessionResolver creates a new mock instance.
func NewMocksessionResolver(ctrl *gomock.Controller) *MocksessionResolver {
	mock := &MocksessionResolver{ctrl: ctrl}
	mock.recorder = &MocksessionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionResolver) EXPECT() *MocksessionResolverMockRecorder {
	return m.recorder
}

// FetchOneByAccessToken mocks base method.
func (m *MocksessionResolver) FetchOneByAccessToken(ctx context.Context, accessToken string) (dto.UserScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByAccessToken indicates an expected call of FetchOneByAccessToken.
func (mr *MocksessionResolverMockRecorder) FetchOneByAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByAccessToken", reflect.TypeOf((*MocksessionResolver)(nil).FetchOneByAccessToken), ctx, accessToken)
}

// MockuserRealmFetcher is a mock of userRealmFetcher interface.
type MockuserRealmFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockuserRealmFetcherMockRecorder
	isgomock struct{}
}

// MockuserRealmFetcherMockRecorder is the mock recorder for MockuserRealmFetcher.
type MockuserRealmFetcherMockRecorder struct {
	mock *MockuserRealmFetcher
}

// NewMockuserRealmFetcher creates a new mock instance.
func NewMockuserRealmFetcher(ctrl *gomock.Controller) *MockuserRealmFetcher {
	mock := &MockuserRealmFetcher{ctrl: ctrl}
	mock.recorder = &MockuserRealmFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRealmFetcher) EXPECT() *MockuserRealmFetcherMockRecorder {
	return m.recorder
}

// FetchOne mocks base method.
func (m *MockuserRealmFetcher) FetchOne(ctx context.Context, userID uuid.UUID, realmID uint16) (entity.UserRealm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, userID, realmID)
	ret0, _ := ret[0].(entity.UserRealm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockuserRealmFetcherMockRecorder) FetchOne(ctx, userID, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockuserRealmFetcher)(nil).FetchOne), ctx, userID, realmID)
}
