// Code generated by MockGen. DO NOT EDIT.
// Source: session_list.go
//
// Generated by this command:
//
//	mockgen -source=session_list.go -destination=mock/session_list.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionLister is a mock of sessionLister interface.
type MocksessionLister struct {
	ctrl     *gomock.Controller
	recorder *MocksessionListerMockRecorder
	isgomock struct{}
}

// MocksessionListerMockRecorder is the mock recorder for MocksessionLister.
type MocksessionListerMockRecorder struct {
	mock *MocksessionLister
}

// NewMocksessionLister creates a new mock instance.
func NewMocksessionLister(ctrl *gomock.Controller) *MocksessionLister {
	mock := &MocksessionLister{ctrl: ctrl}
	mock.recorder = &MocksessionListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionLister) EXPECT() *MocksessionListerMockRecorder {
	return m.recorder
}

// FetchListByUserID mocks base method.
func (m *MocksessionLister) FetchListByUserID(ctx context.Context, userID uuid.UUID) ([]entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchListByUserID indicates an expected call of FetchListByUserID.
func (mr *MocksessionListerMockRecorder) FetchListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchListByUserID", reflect.TypeOf((*MocksessionLister)(nil).FetchListByUserID), ctx, userID)
}

// MockopenSessionFetcher is a mock of openSessionFetcher interface.
type MockopenSessionFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockopenSessionFetcherMockRecorder
	isgomock struct{}
}

// MockopenSessionFetcherMockRecorder is the mock recorder for MockopenSessionFetcher.
type MockopenSessionFetcherMockRecorder struct {
	mock *MockopenSessionFetcher
}

// NewMockopenSessionFetcher creates a new mock instance.
func NewMockopenSessionFetcher(ctrl *gomock.Controller) *MockopenSessionFetcher {
	mock := &MockopenSessionFetcher{ctrl: ctrl}
	mock.recorder = &MockopenSessionFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockopenSessionFetcher) EXPECT() *MockopenSessionFetcherMockRecorder {
	return m.recorder
}

// FetchOpenSessionIDs mocks base method.
func (m *MockopenSessionFetcher) FetchOpenSessionIDs(ctx context.Context, userID uuid.UUID) ([]uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOpenSessionIDs", ctx, userID)
	ret0, _ := ret[0].([]uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOpenSessionIDs indicates an expected call of FetchOpenSessionIDs.
func (mr *MockopenSessionFetcherMockRecorder) FetchOpenSessionIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOpenSessionIDs", reflect.TypeOf((*MockopenSessionFetcher)(nil).FetchOpenSessionIDs), ctx, userID)
}

// MocksessionCloser is a mock of sessionCloser interface.
type MocksessionCloser struct {
	ctrl     *gomock.Controller
	recorder *MocksessionCloserMockRecorder
	isgomock struct{}
}

// MocksessionCloserMockRecorder is the mock recorder for MocksessionCloser.
type MocksessionCloserMockRecorder struct {
	mock *MocksessionCloser
}

// NewMocksessionCloser creates a new mock instance.
func NewMocksessionCloser(ctrl *gomock.Controller) *MocksessionCloser {
	mock := &MocksessionCloser{ctrl: ctrl}
	mock.recorder = &MocksessionCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionCloser) EXPECT() *MocksessionCloserMockRecorder {
	return m.recorder
}

// RevokeTokensBySessionIDs mocks base method.
func (m *MocksessionCloser) RevokeTokensBySessionIDs(ctx context.Context, userID uuid.UUID, sessionIDs []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokensBySessionIDs", ctx, userID, sessionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokensBySessionIDs indicates an expected call of RevokeTokensBySessionIDs.
func (mr *MocksessionCloserMockRecorder) RevokeTokensBySessionIDs(ctx, userID, sessionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokensBySessionIDs", reflect.TypeOf((*MocksessionCloser)(nil).RevokeTokensBySessionIDs), ctx, userID, sessionIDs)
}

// MockcurrentSessionResolver is a mock of currentSessionResolver interface.
type MockcurrentSessionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockcurrentSessionResolverMockRecorder
	isgomock struct{}
}

// MockcurrentSessionResolverMockRecorder is the mock recorder for MockcurrentSessionResolver.
type MockcurrentSessionResolverMockRecorder struct {
	mock *MockcurrentSessionResolver
}

// NewMockcurrentSessionResolver creates a new mock instance.
func NewMockcurrentSessionResolver(ctrl *gomock.Controller) *MockcurrentSessionResolver {
	mock := &MockcurrentSessionResolver{ctrl: ctrl}
	mock.recorder = &MockcurrentSessionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcurrentSessionResolver) EXPECT() *MockcurrentSessionResolverMockRecorder {
	return m.recorder
}

// FetchOneByAccessToken mocks base method.
func (m *MockcurrentSessionResolver) FetchOneByAccessToken(ctx context.Context, accessToken string) (dto.UserScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneByAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneByAccessToken indicates an expected call of FetchOneByAccessToken.
func (mr *MockcurrentSessionResolverMockRecorder) FetchOneByAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneByAccessToken", reflect.TypeOf((*MockcurrentSessionResolver)(nil).FetchOneByAccessToken), ctx, accessToken)
}
