// Code generated by MockGen. DO NOT EDIT.
// Source: session_continue.go
//
// Generated by this command:
//
//	mockgen -source=session_continue.go -destination=mock/session_continue.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockauthTokenStorage is a mock of authTokenStorage interface.
type MockauthTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockauthTokenStorageMockRecorder
	isgomock struct{}
}

// MockauthTokenStorageMockRecorder is the mock recorder for MockauthTokenStorage.
type MockauthTokenStorageMockRecorder struct {
	mock *MockauthTokenStorage
}

// NewMockauthTokenStorage creates a new mock instance.
func NewMockauthTokenStorage(ctrl *gomock.Controller) *MockauthTokenStorage {
	mock := &MockauthTokenStorage{ctrl: ctrl}
	mock.recorder = &MockauthTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthTokenStorage) EXPECT() *MockauthTokenStorageMockRecorder {
	return m.recorder
}

// RevokeTokensBySessionID mocks base method.
func (m *MockauthTokenStorage) RevokeTokensBySessionID(ctx context.Context, userID uuid.UUID, sessionID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokensBySessionID", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokensBySessionID indicates an expected call of RevokeTokensBySessionID.
func (mr *MockauthTokenStorageMockRecorder) RevokeTokensBySessionID(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokensBySessionID", reflect.TypeOf((*MockauthTokenStorage)(nil).RevokeTokensBySessionID), ctx, userID, sessionID)
}

// MocktokenRecreator is a mock of tokenRecreator interface.
type MocktokenRecreator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenRecreatorMockRecorder
	isgomock struct{}
}

// MocktokenRecreatorMockRecorder is the mock recorder for MocktokenRecreator.
type MocktokenRecreatorMockRecorder struct {
	mock *MocktokenRecreator
}

// NewMocktokenRecreator creates a new mock instance.
func NewMocktokenRecreator(ctrl *gomock.Controller) *MocktokenRecreator {
	mock := &MocktokenRecreator{ctrl: ctrl}
	mock.recorder = &MocktokenRecreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenRecreator) EXPECT() *MocktokenRecreatorMockRecorder {
	return m.recorder
}

// Recreate mocks base method.
func (m *MocktokenRecreator) Recreate(ctx context.Context, refreshToken string) (dto.AuthTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recreate", ctx, refreshToken)
	ret0, _ := ret[0].(dto.AuthTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recreate indicates an expected call of Recreate.
func (mr *MocktokenRecreatorMockRecorder) Recreate(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recreate", reflect.TypeOf((*MocktokenRecreator)(nil).Recreate), ctx, refreshToken)
}
