// Code generated by MockGen. DO NOT EDIT.
// Source: session_close.go
//
// Generated by this command:
//
//	mockgen -source=session_close.go -destination=mock/session_close.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktokenCloser is a mock of tokenCloser interface.
type MocktokenCloser struct {
	ctrl     *gomock.Controller
	recorder *MocktokenCloserMockRecorder
	isgomock struct{}
}

// MocktokenCloserMockRecorder is the mock recorder for MocktokenCloser.
type MocktokenCloserMockRecorder struct {
	mock *MocktokenCloser
}

// NewMocktokenCloser creates a new mock instance.
func NewMocktokenCloser(ctrl *gomock.Controller) *MocktokenCloser {
	mock := &MocktokenCloser{ctrl: ctrl}
	mock.recorder = &MocktokenCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenCloser) EXPECT() *MocktokenCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocktokenCloser) Close(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocktokenCloserMockRecorder) Close(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocktokenCloser)(nil).Close), ctx, refreshToken)
}
