// Code generated by MockGen. DO NOT EDIT.
// Source: session_open.go
//
// Generated by this command:
//
//	mockgen -source=session_open.go -destination=mock/session_open.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionIssuer is a mock of sessionIssuer interface.
type MocksessionIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocksessionIssuerMockRecorder
	isgomock struct{}
}

// MocksessionIssuerMockRecorder is the mock recorder for MocksessionIssuer.
type MocksessionIssuerMockRecorder struct {
	mock *MocksessionIssuer
}

// NewMocksessionIssuer creates a new mock instance.
func NewMocksessionIssuer(ctrl *gomock.Controller) *MocksessionIssuer {
	mock := &MocksessionIssuer{ctrl: ctrl}
	mock.recorder = &MocksessionIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionIssuer) EXPECT() *MocksessionIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MocksessionIssuer) Issue(ctx context.Context, session entity.Session) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, session)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MocksessionIssuerMockRecorder) Issue(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MocksessionIssuer)(nil).Issue), ctx, session)
}

// MockopenSessionCounter is a mock of openSessionCounter interface.
type MockopenSessionCounter struct {
	ctrl     *gomock.Controller
	recorder *MockopenSessionCounterMockRecorder
	isgomock struct{}
}

// MockopenSessionCounterMockRecorder is the mock recorder for MockopenSessionCounter.
type MockopenSessionCounterMockRecorder struct {
	mock *MockopenSessionCounter
}

// NewMockopenSessionCounter creates a new mock instance.
func NewMockopenSessionCounter(ctrl *gomock.Controller) *MockopenSessionCounter {
	mock := &MockopenSessionCounter{ctrl: ctrl}
	mock.recorder = &MockopenSessionCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockopenSessionCounter) EXPECT() *MockopenSessionCounterMockRecorder {
	return m.recorder
}

// FetchOpenSessionCount mocks base method.
func (m *MockopenSessionCounter) FetchOpenSessionCount(ctx context.Context, userID uuid.UUID, realmID uint16) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOpenSessionCount", ctx, userID, realmID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOpenSessionCount indicates an expected call of FetchOpenSessionCount.
func (mr *MockopenSessionCounterMockRecorder) FetchOpenSessionCount(ctx, userID, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOpenSessionCount", reflect.TypeOf((*MockopenSessionCounter)(nil).FetchOpenSessionCount), ctx, userID, realmID)
}

// MockuserActivityStatCreator is a mock of userActivityStatCreator interface.
type MockuserActivityStatCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityStatCreatorMockRecorder
	isgomock struct{}
}

// MockuserActivityStatCreatorMockRecorder is the mock recorder for MockuserActivityStatCreator.
type MockuserActivityStatCreatorMockRecorder struct {
	mock *MockuserActivityStatCreator
}

// NewMockuserActivityStatCreator creates a new mock instance.
func NewMockuserActivityStatCreator(ctrl *gomock.Controller) *MockuserActivityStatCreator {
	mock := &MockuserActivityStatCreator{ctrl: ctrl}
	mock.recorder = &MockuserActivityStatCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityStatCreator) EXPECT() *MockuserActivityStatCreatorMockRecorder {
	return m.recorder
}

// InsertOrUpdate mocks base method.
func (m *MockuserActivityStatCreator) InsertOrUpdate(ctx context.Context, row entity.UserActivityStat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdate", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdate indicates an expected call of InsertOrUpdate.
func (mr *MockuserActivityStatCreatorMockRecorder) InsertOrUpdate(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdate", reflect.TypeOf((*MockuserActivityStatCreator)(nil).InsertOrUpdate), ctx, row)
}

// MockexcessQueueProducer is a mock of excessQueueProducer interface.
type MockexcessQueueProducer struct {
	ctrl     *gomock.Controller
	recorder *MockexcessQueueProducerMockRecorder
	isgomock struct{}
}

// MockexcessQueueProducerMockRecorder is the mock recorder for MockexcessQueueProducer.
type MockexcessQueueProducerMockRecorder struct {
	mock *MockexcessQueueProducer
}

// NewMockexcessQueueProducer creates a new mock instance.
func NewMockexcessQueueProducer(ctrl *gomock.Controller) *MockexcessQueueProducer {
	mock := &MockexcessQueueProducer{ctrl: ctrl}
	mock.recorder = &MockexcessQueueProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexcessQueueProducer) EXPECT() *MockexcessQueueProducerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockexcessQueueProducer) Enqueue(ctx context.Context, userID uuid.UUID, realmID uint16, sessionMax int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, userID, realmID, sessionMax)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockexcessQueueProducerMockRecorder) Enqueue(ctx, userID, realmID, sessionMax any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockexcessQueueProducer)(nil).Enqueue), ctx, userID, realmID, sessionMax)
}

// MockauthFlowHandler is a mock of authFlowHandler interface.
type MockauthFlowHandler struct {
	ctrl     *gomock.Controller
	recorder *MockauthFlowHandlerMockRecorder
	isgomock struct{}
}

// MockauthFlowHandlerMockRecorder is the mock recorder for MockauthFlowHandler.
type MockauthFlowHandlerMockRecorder struct {
	mock *MockauthFlowHandler
}

// NewMockauthFlowHandler creates a new mock instance.
func NewMockauthFlowHandler(ctrl *gomock.Controller) *MockauthFlowHandler {
	mock := &MockauthFlowHandler{ctrl: ctrl}
	mock.recorder = &MockauthFlowHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthFlowHandler) EXPECT() *MockauthFlowHandlerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockauthFlowHandler) Execute(ctx context.Context, op secureoperation.SecureOperation) (dto.UserScopes, func(context.Context), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, op)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(func(context.Context))
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockauthFlowHandlerMockRecorder) Execute(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockauthFlowHandler)(nil).Execute), ctx, op)
}

// MocktokenCreator is a mock of tokenCreator interface.
type MocktokenCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenCreatorMockRecorder
	isgomock struct{}
}

// MocktokenCreatorMockRecorder is the mock recorder for MocktokenCreator.
type MocktokenCreatorMockRecorder struct {
	mock *MocktokenCreator
}

// NewMocktokenCreator creates a new mock instance.
func NewMocktokenCreator(ctrl *gomock.Controller) *MocktokenCreator {
	mock := &MocktokenCreator{ctrl: ctrl}
	mock.recorder = &MocktokenCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenCreator) EXPECT() *MocktokenCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktokenCreator) Create(ctx context.Context, userScopes dto.UserScopes) (dto.AuthTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userScopes)
	ret0, _ := ret[0].(dto.AuthTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktokenCreatorMockRecorder) Create(ctx, userScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktokenCreator)(nil).Create), ctx, userScopes)
}

// MockoperationConsumer is a mock of operationConsumer interface.
type MockoperationConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockoperationConsumerMockRecorder
	isgomock struct{}
}

// MockoperationConsumerMockRecorder is the mock recorder for MockoperationConsumer.
type MockoperationConsumerMockRecorder struct {
	mock *MockoperationConsumer
}

// NewMockoperationConsumer creates a new mock instance.
func NewMockoperationConsumer(ctrl *gomock.Controller) *MockoperationConsumer {
	mock := &MockoperationConsumer{ctrl: ctrl}
	mock.recorder = &MockoperationConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationConsumer) EXPECT() *MockoperationConsumerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockoperationConsumer) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockoperationConsumerMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockoperationConsumer)(nil).Delete), ctx, token)
}

// MockoperationLogger is a mock of operationLogger interface.
type MockoperationLogger struct {
	ctrl     *gomock.Controller
	recorder *MockoperationLoggerMockRecorder
	isgomock struct{}
}

// MockoperationLoggerMockRecorder is the mock recorder for MockoperationLogger.
type MockoperationLoggerMockRecorder struct {
	mock *MockoperationLogger
}

// NewMockoperationLogger creates a new mock instance.
func NewMockoperationLogger(ctrl *gomock.Controller) *MockoperationLogger {
	mock := &MockoperationLogger{ctrl: ctrl}
	mock.recorder = &MockoperationLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationLogger) EXPECT() *MockoperationLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockoperationLogger) Log(ctx context.Context, entry entity.SecureOperationLog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", ctx, entry)
}

// Log indicates an expected call of Log.
func (mr *MockoperationLoggerMockRecorder) Log(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockoperationLogger)(nil).Log), ctx, entry)
}
