// Code generated by MockGen. DO NOT EDIT.
// Source: session_open.go
//
// Generated by this command:
//
//	mockgen -source=session_open.go -destination=mock/session_open.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionIssuer is a mock of sessionIssuer interface.
type MocksessionIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocksessionIssuerMockRecorder
	isgomock struct{}
}

// MocksessionIssuerMockRecorder is the mock recorder for MocksessionIssuer.
type MocksessionIssuerMockRecorder struct {
	mock *MocksessionIssuer
}

// NewMocksessionIssuer creates a new mock instance.
func NewMocksessionIssuer(ctrl *gomock.Controller) *MocksessionIssuer {
	mock := &MocksessionIssuer{ctrl: ctrl}
	mock.recorder = &MocksessionIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionIssuer) EXPECT() *MocksessionIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MocksessionIssuer) Issue(ctx context.Context, session entity.Session) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, session)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MocksessionIssuerMockRecorder) Issue(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MocksessionIssuer)(nil).Issue), ctx, session)
}

// MockuserActivityStatCreator is a mock of userActivityStatCreator interface.
type MockuserActivityStatCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserActivityStatCreatorMockRecorder
	isgomock struct{}
}

// MockuserActivityStatCreatorMockRecorder is the mock recorder for MockuserActivityStatCreator.
type MockuserActivityStatCreatorMockRecorder struct {
	mock *MockuserActivityStatCreator
}

// NewMockuserActivityStatCreator creates a new mock instance.
func NewMockuserActivityStatCreator(ctrl *gomock.Controller) *MockuserActivityStatCreator {
	mock := &MockuserActivityStatCreator{ctrl: ctrl}
	mock.recorder = &MockuserActivityStatCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserActivityStatCreator) EXPECT() *MockuserActivityStatCreatorMockRecorder {
	return m.recorder
}

// InsertOrUpdate mocks base method.
func (m *MockuserActivityStatCreator) InsertOrUpdate(ctx context.Context, row entity.UserActivityStat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdate", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdate indicates an expected call of InsertOrUpdate.
func (mr *MockuserActivityStatCreatorMockRecorder) InsertOrUpdate(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdate", reflect.TypeOf((*MockuserActivityStatCreator)(nil).InsertOrUpdate), ctx, row)
}

// MockoperationHandlerCreateUser is a mock of operationHandlerCreateUser interface.
type MockoperationHandlerCreateUser struct {
	ctrl     *gomock.Controller
	recorder *MockoperationHandlerCreateUserMockRecorder
	isgomock struct{}
}

// MockoperationHandlerCreateUserMockRecorder is the mock recorder for MockoperationHandlerCreateUser.
type MockoperationHandlerCreateUserMockRecorder struct {
	mock *MockoperationHandlerCreateUser
}

// NewMockoperationHandlerCreateUser creates a new mock instance.
func NewMockoperationHandlerCreateUser(ctrl *gomock.Controller) *MockoperationHandlerCreateUser {
	mock := &MockoperationHandlerCreateUser{ctrl: ctrl}
	mock.recorder = &MockoperationHandlerCreateUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationHandlerCreateUser) EXPECT() *MockoperationHandlerCreateUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockoperationHandlerCreateUser) Execute(ctx context.Context, payload []byte) (dto.UserScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, payload)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockoperationHandlerCreateUserMockRecorder) Execute(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockoperationHandlerCreateUser)(nil).Execute), ctx, payload)
}

// MockoperationHandlerBeforeAuthUser is a mock of operationHandlerBeforeAuthUser interface.
type MockoperationHandlerBeforeAuthUser struct {
	ctrl     *gomock.Controller
	recorder *MockoperationHandlerBeforeAuthUserMockRecorder
	isgomock struct{}
}

// MockoperationHandlerBeforeAuthUserMockRecorder is the mock recorder for MockoperationHandlerBeforeAuthUser.
type MockoperationHandlerBeforeAuthUserMockRecorder struct {
	mock *MockoperationHandlerBeforeAuthUser
}

// NewMockoperationHandlerBeforeAuthUser creates a new mock instance.
func NewMockoperationHandlerBeforeAuthUser(ctrl *gomock.Controller) *MockoperationHandlerBeforeAuthUser {
	mock := &MockoperationHandlerBeforeAuthUser{ctrl: ctrl}
	mock.recorder = &MockoperationHandlerBeforeAuthUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoperationHandlerBeforeAuthUser) EXPECT() *MockoperationHandlerBeforeAuthUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockoperationHandlerBeforeAuthUser) Execute(ctx context.Context, userID uuid.UUID, payload []byte) (dto.UserScopes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, payload)
	ret0, _ := ret[0].(dto.UserScopes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockoperationHandlerBeforeAuthUserMockRecorder) Execute(ctx, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockoperationHandlerBeforeAuthUser)(nil).Execute), ctx, userID, payload)
}

// MocktokenCreator is a mock of tokenCreator interface.
type MocktokenCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenCreatorMockRecorder
	isgomock struct{}
}

// MocktokenCreatorMockRecorder is the mock recorder for MocktokenCreator.
type MocktokenCreatorMockRecorder struct {
	mock *MocktokenCreator
}

// NewMocktokenCreator creates a new mock instance.
func NewMocktokenCreator(ctrl *gomock.Controller) *MocktokenCreator {
	mock := &MocktokenCreator{ctrl: ctrl}
	mock.recorder = &MocktokenCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenCreator) EXPECT() *MocktokenCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktokenCreator) Create(ctx context.Context, userScopes dto.UserScopes) (dto.AuthTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userScopes)
	ret0, _ := ret[0].(dto.AuthTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktokenCreatorMockRecorder) Create(ctx, userScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktokenCreator)(nil).Create), ctx, userScopes)
}
