-- //-- +++1. один процесс ставит сообщения в очередь item_queue + item_queue_body в статусе READY/DELAYED (в одной транзакции с основным запросом)
-- //
-- //-- +++2. один процесс переводит запросы из READY в PROCESSING + уменьшает remaining_attempts (через LOCK rows) и
-- //--    выполняет эти процессы (обратившись к item_queue_body),
-- //--   +++????UseCase после успешного выполнения удаляет из item_queue и пишет в item_queue_completed (не обязательно),
-- //--   +++????UseCase если произошла ошибка, то пишет в item_queue_error, меняет статус на RETRY
-- //
-- //-- +++3. один процесс следит, в чтобы в item_queue дата (NOW() - updated_at) было меньше timeout,
-- //--  +++  иначе вылет по таймауту и есть попытки, то пишет в item_queue_error, меняет статус на RETRY
-- //
-- //--+++ 4. один процесс переводит запросы из RETRY item_queue в READY
-- //-  +++  если попыток нет, то удаляет из item_queue
-- //
-- //-- 5. один процесс чистит item_queue_error + item_queue_body по created_at + item_id
-- //
-- //-- 6. один процесс чистит item_queue_completed + item_queue_body по created_at + item_id (если item_queue_completed выключена, то просто по item_id)



-- --------------------------------------------------------------------------------------------------

-- 1. один процесс ставит сообщения в очередь message_inbox

-- for insert, read, delete (фоном)
CREATE TABLE printshop_global.message_inbox (
    message_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_message_inbox PRIMARY KEY,
    message_key uuid NOT NULL,
    message_topic character varying(128) NOT NULL,
    message_payload bytea NOT NULL,
    message_payload_json jsonb NOT NULL,
    retry_attempts int2 NOT NULL,
    retry_delayed int2 NOT NULL,
    dt_start timestamp with time zone NOT NULL DEFAULT NOW(),
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);


-- for insert, read, delete (фоновый)
CREATE TABLE printshop_global.item_queue_body (
    item_id int8 NOT NULL CONSTRAINT pk_item_queue_body PRIMARY KEY,
    item_key character varying(64) NOT NULL, -- can by ID + VERSION
    retry_attempts int2 NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_message_inbox_message_key ON printshop_global.message_inbox (message_key);
CREATE INDEX ix_message_inbox_dt_start ON printshop_global.message_inbox (dt_start);

-- 2. один процесс (N воркеров) ставит в очередь message_inbox_processing (читает из message_inbox) и выполняет эти процессы,
--    после успешного выполнения удаляет из message_inbox_processing и пишет в message_inbox_success,
--    если произошла ошибка, то пишет в message_inbox_error, удаляет из message_inbox_processing и пишет в message_inbox_retry (если попытки остались)
-- 3. один процесс следит, в message_inbox_processing updated_at было небольшим,
--    иначе вылет по таймауту и запись в message_inbox_retry (если не закончились попытки) и в message_inbox_error

-- for insert, read, delete
CREATE TABLE printshop_global.message_inbox_processing (
    message_id int8 NOT NULL CONSTRAINT pk_message_inbox_processing PRIMARY KEY,
    remaining_attempts int2 NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

-- 4. один процесс удаляет из message_inbox_retry (согласно прописанной паузе) и ставит в очередь message_inbox_processing (с уменьшением 1 попытки, тут попытки не должны закончиться)
--    и выполняет эти процессы, после успешного выполнения удаляет из message_inbox_processing и пишет в message_inbox_success

-- for insert, read, delete
CREATE TABLE printshop_global.message_inbox_retry (
    message_id int8 NOT NULL CONSTRAINT pk_message_inbox_retry PRIMARY KEY,
    remaining_attempts int2 NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

-- 5. один процесс чистит сообщения об ошибках по created_at

-- for insert, read, delete (фоном)
CREATE TABLE printshop_global.message_inbox_error (
    error_message text NOT NULL,
    message_id int8 NOT NULL,
    current_attempt int2 NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_message_inbox_error_message_id ON printshop_global.message_inbox_error (message_id);
CREATE INDEX ix_message_inbox_error_created_at ON printshop_global.message_inbox_error (created_at);

-- for insert, read, delete
CREATE TABLE printshop_global.message_inbox_success (
    message_id int8 NOT NULL CONSTRAINT pk_message_inbox_success PRIMARY KEY,
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

-- 6. один процесс выбирает данные из message_inbox + message_inbox_success + message_inbox_error  и добавляет в message_inbox_archive
--    и удаляет из message_inbox, message_inbox_success и message_inbox_error
-- 7. один процесс удаляет архивные сообщения (по created_at)

-- only for insert (фоном), read, delete (фоном)
CREATE TABLE printshop_global.message_inbox_archive (
    message_key uuid NOT NULL CONSTRAINT pk_message_inbox_archive PRIMARY KEY,
    message_topic character varying(128) NOT NULL,
    message_payload bytea NOT NULL,
    message_payload_json jsonb NOT NULL,
    retry_attempts int2 NOT NULL,
    spent_attempts int2 NOT NULL,
    last_error text NOT NULL,
    message_status int2 NOT NULL, -- 1=SUCCESS, 2=ERROR
    started_at timestamp with time zone NOT NULL DEFAULT NOW(),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_message_inbox_archive_created_at ON printshop_global.message_inbox_archive (created_at);





SELECT template_id as templateId,
       from_name as fromName,
       from_email as senderName,
       to_name as toName,
       to_email as toEmail,
       content_type as contentType,
       notice_subject as noticeSubject,
       notice_preheader as noticePreheader,
       notice_body as noticeBody,
       observers_emails as observersEmails,
       notice_status as noticeStatus
FROM mrcms_notices_templates
WHERE lang_code = ? AND
    notice_key = ? AND
    notice_status <> ?

SELECT mnv.variable_name as variableName,
       mnv.default_value as defaultName
FROM
    mrcms_notices_vars mnv
        JOIN
    mrcms_notices_templates_vars mntv
    ON
        mnv.variable_id = mntv.variable_id
WHERE mntv.template_id = ?



CREATE TABLE `erp_messages` (
                                `message_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
    `datetime_sent` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `from_user_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    `message_type` enum('private','common','system') NOT NULL DEFAULT 'private',
    `message_priority` enum('normal','extra') NOT NULL DEFAULT 'normal',
    `message_text` text NOT NULL,
    PRIMARY KEY (`message_id`),
    KEY `datetime_sent` (`datetime_sent`),
    KEY `from_user_id` (`from_user_id`)
    ) ENGINE=MyISAM AUTO_INCREMENT=207412 DEFAULT CHARSET=cp1251;


CREATE TABLE `erp_messages_groups` (
                                       `group_id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
    `group_name` char(50) NOT NULL DEFAULT '',
    `is_system` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `order_field` tinyint(3) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`group_id`),
    UNIQUE KEY `group_name` (`group_name`),
    KEY `order_field` (`order_field`)
    ) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=cp1251;

CREATE TABLE `erp_messages_groups_users` (
                                             `group_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
    `user_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`group_id`,`user_id`),
    UNIQUE KEY `user_id` (`user_id`,`group_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

CREATE TABLE `erp_messages_notifications` (
                                              `message_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    `user_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    `datetime_read` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY (`user_id`,`message_id`),
    UNIQUE KEY `message_id` (`message_id`,`user_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

CREATE TABLE `erp_messages_recipients` (
                                           `message_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    `user_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`user_id`,`message_id`),
    UNIQUE KEY `message_id` (`message_id`,`user_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=cp1251;

CREATE TABLE `erp_messages_recipients_groups` (
                                                  `message_id` mediumint(8) unsigned NOT NULL DEFAULT '0',
    `group_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`group_id`,`message_id`),
    UNIQUE KEY `message_id` (`message_id`,`group_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=cp1251;