// Code generated by MockGen. DO NOT EDIT.
// Source: build_notice.go
//
// Generated by this command:
//
//	mockgen -source=build_notice.go -destination=mock/build_notice.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrnotifier/notifier/dto"
	dto0 "github.com/mondegor/go-components/mrnotifier/template/dto"
	entity "github.com/mondegor/go-components/mrnotifier/template/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateService is a mock of templateService interface.
type MocktemplateService struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateServiceMockRecorder
	isgomock struct{}
}

// MocktemplateServiceMockRecorder is the mock recorder for MocktemplateService.
type MocktemplateServiceMockRecorder struct {
	mock *MocktemplateService
}

// NewMocktemplateService creates a new mock instance.
func NewMocktemplateService(ctrl *gomock.Controller) *MocktemplateService {
	mock := &MocktemplateService{ctrl: ctrl}
	mock.recorder = &MocktemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateService) EXPECT() *MocktemplateServiceMockRecorder {
	return m.recorder
}

// GetItemByKey mocks base method.
func (m *MocktemplateService) GetItemByKey(ctx context.Context, name, lang string) (dto0.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByKey", ctx, name, lang)
	ret0, _ := ret[0].(dto0.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByKey indicates an expected call of GetItemByKey.
func (mr *MocktemplateServiceMockRecorder) GetItemByKey(ctx, name, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByKey", reflect.TypeOf((*MocktemplateService)(nil).GetItemByKey), ctx, name, lang)
}

// MocknoticeBuilder is a mock of noticeBuilder interface.
type MocknoticeBuilder struct {
	ctrl     *gomock.Controller
	recorder *MocknoticeBuilderMockRecorder
	isgomock struct{}
}

// MocknoticeBuilderMockRecorder is the mock recorder for MocknoticeBuilder.
type MocknoticeBuilderMockRecorder struct {
	mock *MocknoticeBuilder
}

// NewMocknoticeBuilder creates a new mock instance.
func NewMocknoticeBuilder(ctrl *gomock.Controller) *MocknoticeBuilder {
	mock := &MocknoticeBuilder{ctrl: ctrl}
	mock.recorder = &MocknoticeBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknoticeBuilder) EXPECT() *MocknoticeBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MocknoticeBuilder) Build(vars map[string]string, templ entity.TemplateData) ([]dto.Notice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", vars, templ)
	ret0, _ := ret[0].([]dto.Notice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MocknoticeBuilderMockRecorder) Build(vars, templ any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MocknoticeBuilder)(nil).Build), vars, templ)
}
