// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrserver/request (interfaces: ParserUser,ParserClient)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrserver.go -package=mock github.com/mondegor/go-webcore/mrserver/request ParserUser,ParserClient
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	netip "net/netip"
	reflect "reflect"

	uuid "github.com/google/uuid"
	mrtype "github.com/mondegor/go-core/mrtype"
	gomock "go.uber.org/mock/gomock"
)

// MockParserUser is a mock of ParserUser interface.
type MockParserUser struct {
	ctrl     *gomock.Controller
	recorder *MockParserUserMockRecorder
	isgomock struct{}
}

// MockParserUserMockRecorder is the mock recorder for MockParserUser.
type MockParserUserMockRecorder struct {
	mock *MockParserUser
}

// NewMockParserUser creates a new mock instance.
func NewMockParserUser(ctrl *gomock.Controller) *MockParserUser {
	mock := &MockParserUser{ctrl: ctrl}
	mock.recorder = &MockParserUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserUser) EXPECT() *MockParserUserMockRecorder {
	return m.recorder
}

// LangCode mocks base method.
func (m *MockParserUser) LangCode(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LangCode", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// LangCode indicates an expected call of LangCode.
func (mr *MockParserUserMockRecorder) LangCode(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LangCode", reflect.TypeOf((*MockParserUser)(nil).LangCode), r)
}

// SessionID mocks base method.
func (m *MockParserUser) SessionID(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockParserUserMockRecorder) SessionID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockParserUser)(nil).SessionID), r)
}

// TimeZoneName mocks base method.
func (m *MockParserUser) TimeZoneName(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeZoneName", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// TimeZoneName indicates an expected call of TimeZoneName.
func (mr *MockParserUserMockRecorder) TimeZoneName(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeZoneName", reflect.TypeOf((*MockParserUser)(nil).TimeZoneName), r)
}

// UserAndGroup mocks base method.
func (m *MockParserUser) UserAndGroup(r *http.Request) (uuid.UUID, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAndGroup", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// UserAndGroup indicates an expected call of UserAndGroup.
func (mr *MockParserUserMockRecorder) UserAndGroup(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAndGroup", reflect.TypeOf((*MockParserUser)(nil).UserAndGroup), r)
}

// UserID mocks base method.
func (m *MockParserUser) UserID(r *http.Request) uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID", r)
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockParserUserMockRecorder) UserID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockParserUser)(nil).UserID), r)
}

// MockParserClient is a mock of ParserClient interface.
type MockParserClient struct {
	ctrl     *gomock.Controller
	recorder *MockParserClientMockRecorder
	isgomock struct{}
}

// MockParserClientMockRecorder is the mock recorder for MockParserClient.
type MockParserClientMockRecorder struct {
	mock *MockParserClient
}

// NewMockParserClient creates a new mock instance.
func NewMockParserClient(ctrl *gomock.Controller) *MockParserClient {
	mock := &MockParserClient{ctrl: ctrl}
	mock.recorder = &MockParserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserClient) EXPECT() *MockParserClientMockRecorder {
	return m.recorder
}

// DetailedIP mocks base method.
func (m *MockParserClient) DetailedIP(r *http.Request) mrtype.DetailedIP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedIP", r)
	ret0, _ := ret[0].(mrtype.DetailedIP)
	return ret0
}

// DetailedIP indicates an expected call of DetailedIP.
func (mr *MockParserClientMockRecorder) DetailedIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedIP", reflect.TypeOf((*MockParserClient)(nil).DetailedIP), r)
}

// RealIP mocks base method.
func (m *MockParserClient) RealIP(r *http.Request) netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealIP", r)
	ret0, _ := ret[0].(netip.Addr)
	return ret0
}

// RealIP indicates an expected call of RealIP.
func (mr *MockParserClientMockRecorder) RealIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealIP", reflect.TypeOf((*MockParserClient)(nil).RealIP), r)
}

// UserAgent mocks base method.
func (m *MockParserClient) UserAgent(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAgent", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// UserAgent indicates an expected call of UserAgent.
func (mr *MockParserClientMockRecorder) UserAgent(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAgent", reflect.TypeOf((*MockParserClient)(nil).UserAgent), r)
}
