// Code generated by MockGen. DO NOT EDIT.
// Source: secure_operation.go
//
// Generated by this command:
//
//	mockgen -source=secure_operation.go -destination=mock/secure_operation.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MocksecureOperationLogProducer is a mock of secureOperationLogProducer interface.
type MocksecureOperationLogProducer struct {
	ctrl     *gomock.Controller
	recorder *MocksecureOperationLogProducerMockRecorder
	isgomock struct{}
}

// MocksecureOperationLogProducerMockRecorder is the mock recorder for MocksecureOperationLogProducer.
type MocksecureOperationLogProducerMockRecorder struct {
	mock *MocksecureOperationLogProducer
}

// NewMocksecureOperationLogProducer creates a new mock instance.
func NewMocksecureOperationLogProducer(ctrl *gomock.Controller) *MocksecureOperationLogProducer {
	mock := &MocksecureOperationLogProducer{ctrl: ctrl}
	mock.recorder = &MocksecureOperationLogProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecureOperationLogProducer) EXPECT() *MocksecureOperationLogProducerMockRecorder {
	return m.recorder
}

// PushMessage mocks base method.
func (m *MocksecureOperationLogProducer) PushMessage(ctx context.Context, entry entity.SecureOperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMessage", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMessage indicates an expected call of PushMessage.
func (mr *MocksecureOperationLogProducerMockRecorder) PushMessage(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMessage", reflect.TypeOf((*MocksecureOperationLogProducer)(nil).PushMessage), ctx, entry)
}
