// Code generated by MockGen. DO NOT EDIT.
// Source: user_request.go
//
// Generated by this command:
//
//	mockgen -source=user_request.go -destination=mock/user_request.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockuserLogProducer is a mock of userLogProducer interface.
type MockuserLogProducer struct {
	ctrl     *gomock.Controller
	recorder *MockuserLogProducerMockRecorder
	isgomock struct{}
}

// MockuserLogProducerMockRecorder is the mock recorder for MockuserLogProducer.
type MockuserLogProducerMockRecorder struct {
	mock *MockuserLogProducer
}

// NewMockuserLogProducer creates a new mock instance.
func NewMockuserLogProducer(ctrl *gomock.Controller) *MockuserLogProducer {
	mock := &MockuserLogProducer{ctrl: ctrl}
	mock.recorder = &MockuserLogProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserLogProducer) EXPECT() *MockuserLogProducerMockRecorder {
	return m.recorder
}

// PushMessage mocks base method.
func (m *MockuserLogProducer) PushMessage(ctx context.Context, message dto.UserActivityLogMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMessage indicates an expected call of PushMessage.
func (mr *MockuserLogProducerMockRecorder) PushMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMessage", reflect.TypeOf((*MockuserLogProducer)(nil).PushMessage), ctx, message)
}
