// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mock/auth.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	model "github.com/mondegor/go-components/mrauth/infra/pub/controller/httpv1/model"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	mrtype "github.com/mondegor/go-core/mrtype"
	mrresp "github.com/mondegor/go-webcore/mrserver/mrresp"
	gomock "go.uber.org/mock/gomock"
)

// MockcookieValueService is a mock of cookieValueService interface.
type MockcookieValueService struct {
	ctrl     *gomock.Controller
	recorder *MockcookieValueServiceMockRecorder
	isgomock struct{}
}

// MockcookieValueServiceMockRecorder is the mock recorder for MockcookieValueService.
type MockcookieValueServiceMockRecorder struct {
	mock *MockcookieValueService
}

// NewMockcookieValueService creates a new mock instance.
func NewMockcookieValueService(ctrl *gomock.Controller) *MockcookieValueService {
	mock := &MockcookieValueService{ctrl: ctrl}
	mock.recorder = &MockcookieValueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcookieValueService) EXPECT() *MockcookieValueServiceMockRecorder {
	return m.recorder
}

// GetValue mocks base method.
func (m *MockcookieValueService) GetValue(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetValue indicates an expected call of GetValue.
func (mr *MockcookieValueServiceMockRecorder) GetValue(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockcookieValueService)(nil).GetValue), r)
}

// RemoveValue mocks base method.
func (m *MockcookieValueService) RemoveValue(w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveValue", w)
}

// RemoveValue indicates an expected call of RemoveValue.
func (mr *MockcookieValueServiceMockRecorder) RemoveValue(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveValue", reflect.TypeOf((*MockcookieValueService)(nil).RemoveValue), w)
}

// SetValue mocks base method.
func (m *MockcookieValueService) SetValue(w http.ResponseWriter, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetValue", w, value)
}

// SetValue indicates an expected call of SetValue.
func (mr *MockcookieValueServiceMockRecorder) SetValue(w, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValue", reflect.TypeOf((*MockcookieValueService)(nil).SetValue), w, value)
}

// MockcreateUserUseCase is a mock of createUserUseCase interface.
type MockcreateUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcreateUserUseCaseMockRecorder
	isgomock struct{}
}

// MockcreateUserUseCaseMockRecorder is the mock recorder for MockcreateUserUseCase.
type MockcreateUserUseCaseMockRecorder struct {
	mock *MockcreateUserUseCase
}

// NewMockcreateUserUseCase creates a new mock instance.
func NewMockcreateUserUseCase(ctrl *gomock.Controller) *MockcreateUserUseCase {
	mock := &MockcreateUserUseCase{ctrl: ctrl}
	mock.recorder = &MockcreateUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateUserUseCase) EXPECT() *MockcreateUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockcreateUserUseCase) Execute(ctx context.Context, realm, langCode, timeZone, userEmail string, registeredIP mrtype.DetailedIP) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, realm, langCode, timeZone, userEmail, registeredIP)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockcreateUserUseCaseMockRecorder) Execute(ctx, realm, langCode, timeZone, userEmail, registeredIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockcreateUserUseCase)(nil).Execute), ctx, realm, langCode, timeZone, userEmail, registeredIP)
}

// MockauthUserUseCase is a mock of authUserUseCase interface.
type MockauthUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockauthUserUseCaseMockRecorder
	isgomock struct{}
}

// MockauthUserUseCaseMockRecorder is the mock recorder for MockauthUserUseCase.
type MockauthUserUseCaseMockRecorder struct {
	mock *MockauthUserUseCase
}

// NewMockauthUserUseCase creates a new mock instance.
func NewMockauthUserUseCase(ctrl *gomock.Controller) *MockauthUserUseCase {
	mock := &MockauthUserUseCase{ctrl: ctrl}
	mock.recorder = &MockauthUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthUserUseCase) EXPECT() *MockauthUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockauthUserUseCase) Execute(ctx context.Context, actor dto.ActorMeta, realm, langCode, userLogin string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, realm, langCode, userLogin)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockauthUserUseCaseMockRecorder) Execute(ctx, actor, realm, langCode, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockauthUserUseCase)(nil).Execute), ctx, actor, realm, langCode, userLogin)
}

// MockconfirmOperationUseCase is a mock of confirmOperationUseCase interface.
type MockconfirmOperationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmOperationUseCaseMockRecorder
	isgomock struct{}
}

// MockconfirmOperationUseCaseMockRecorder is the mock recorder for MockconfirmOperationUseCase.
type MockconfirmOperationUseCaseMockRecorder struct {
	mock *MockconfirmOperationUseCase
}

// NewMockconfirmOperationUseCase creates a new mock instance.
func NewMockconfirmOperationUseCase(ctrl *gomock.Controller) *MockconfirmOperationUseCase {
	mock := &MockconfirmOperationUseCase{ctrl: ctrl}
	mock.recorder = &MockconfirmOperationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmOperationUseCase) EXPECT() *MockconfirmOperationUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockconfirmOperationUseCase) Execute(ctx context.Context, actor dto.ActorMeta, langCode, operationToken, confirmCode string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, langCode, operationToken, confirmCode)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockconfirmOperationUseCaseMockRecorder) Execute(ctx, actor, langCode, operationToken, confirmCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockconfirmOperationUseCase)(nil).Execute), ctx, actor, langCode, operationToken, confirmCode)
}

// MockopenSessionUseCase is a mock of openSessionUseCase interface.
type MockopenSessionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockopenSessionUseCaseMockRecorder
	isgomock struct{}
}

// MockopenSessionUseCaseMockRecorder is the mock recorder for MockopenSessionUseCase.
type MockopenSessionUseCaseMockRecorder struct {
	mock *MockopenSessionUseCase
}

// NewMockopenSessionUseCase creates a new mock instance.
func NewMockopenSessionUseCase(ctrl *gomock.Controller) *MockopenSessionUseCase {
	mock := &MockopenSessionUseCase{ctrl: ctrl}
	mock.recorder = &MockopenSessionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockopenSessionUseCase) EXPECT() *MockopenSessionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockopenSessionUseCase) Execute(ctx context.Context, meta dto.SessionMeta, op secureoperation.SecureOperation) (dto.AuthTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, meta, op)
	ret0, _ := ret[0].(dto.AuthTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockopenSessionUseCaseMockRecorder) Execute(ctx, meta, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockopenSessionUseCase)(nil).Execute), ctx, meta, op)
}

// MockcontinueSessionUseCase is a mock of continueSessionUseCase interface.
type MockcontinueSessionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcontinueSessionUseCaseMockRecorder
	isgomock struct{}
}

// MockcontinueSessionUseCaseMockRecorder is the mock recorder for MockcontinueSessionUseCase.
type MockcontinueSessionUseCaseMockRecorder struct {
	mock *MockcontinueSessionUseCase
}

// NewMockcontinueSessionUseCase creates a new mock instance.
func NewMockcontinueSessionUseCase(ctrl *gomock.Controller) *MockcontinueSessionUseCase {
	mock := &MockcontinueSessionUseCase{ctrl: ctrl}
	mock.recorder = &MockcontinueSessionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcontinueSessionUseCase) EXPECT() *MockcontinueSessionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockcontinueSessionUseCase) Execute(ctx context.Context, actor dto.ActorMeta, langCode, refreshToken string) (dto.AuthTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, langCode, refreshToken)
	ret0, _ := ret[0].(dto.AuthTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockcontinueSessionUseCaseMockRecorder) Execute(ctx, actor, langCode, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockcontinueSessionUseCase)(nil).Execute), ctx, actor, langCode, refreshToken)
}

// MockcloseSessionUseCase is a mock of closeSessionUseCase interface.
type MockcloseSessionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcloseSessionUseCaseMockRecorder
	isgomock struct{}
}

// MockcloseSessionUseCaseMockRecorder is the mock recorder for MockcloseSessionUseCase.
type MockcloseSessionUseCaseMockRecorder struct {
	mock *MockcloseSessionUseCase
}

// NewMockcloseSessionUseCase creates a new mock instance.
func NewMockcloseSessionUseCase(ctrl *gomock.Controller) *MockcloseSessionUseCase {
	mock := &MockcloseSessionUseCase{ctrl: ctrl}
	mock.recorder = &MockcloseSessionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcloseSessionUseCase) EXPECT() *MockcloseSessionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockcloseSessionUseCase) Execute(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockcloseSessionUseCaseMockRecorder) Execute(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockcloseSessionUseCase)(nil).Execute), ctx, refreshToken)
}

// MockchangeSettingsUseCase is a mock of changeSettingsUseCase interface.
type MockchangeSettingsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockchangeSettingsUseCaseMockRecorder
	isgomock struct{}
}

// MockchangeSettingsUseCaseMockRecorder is the mock recorder for MockchangeSettingsUseCase.
type MockchangeSettingsUseCaseMockRecorder struct {
	mock *MockchangeSettingsUseCase
}

// NewMockchangeSettingsUseCase creates a new mock instance.
func NewMockchangeSettingsUseCase(ctrl *gomock.Controller) *MockchangeSettingsUseCase {
	mock := &MockchangeSettingsUseCase{ctrl: ctrl}
	mock.recorder = &MockchangeSettingsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangeSettingsUseCase) EXPECT() *MockchangeSettingsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockchangeSettingsUseCase) Execute(ctx context.Context, userID uuid.UUID, langCode, timeZone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, langCode, timeZone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockchangeSettingsUseCaseMockRecorder) Execute(ctx, userID, langCode, timeZone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockchangeSettingsUseCase)(nil).Execute), ctx, userID, langCode, timeZone)
}

// MockuserInfoService is a mock of userInfoService interface.
type MockuserInfoService struct {
	ctrl     *gomock.Controller
	recorder *MockuserInfoServiceMockRecorder
	isgomock struct{}
}

// MockuserInfoServiceMockRecorder is the mock recorder for MockuserInfoService.
type MockuserInfoServiceMockRecorder struct {
	mock *MockuserInfoService
}

// NewMockuserInfoService creates a new mock instance.
func NewMockuserInfoService(ctrl *gomock.Controller) *MockuserInfoService {
	mock := &MockuserInfoService{ctrl: ctrl}
	mock.recorder = &MockuserInfoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserInfoService) EXPECT() *MockuserInfoServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockuserInfoService) Get(ctx context.Context, userID uuid.UUID) (dto.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(dto.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockuserInfoServiceMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockuserInfoService)(nil).Get), ctx, userID)
}

// MockconfirmOperationResponse is a mock of confirmOperationResponse interface.
type MockconfirmOperationResponse struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmOperationResponseMockRecorder
	isgomock struct{}
}

// MockconfirmOperationResponseMockRecorder is the mock recorder for MockconfirmOperationResponse.
type MockconfirmOperationResponseMockRecorder struct {
	mock *MockconfirmOperationResponse
}

// NewMockconfirmOperationResponse creates a new mock instance.
func NewMockconfirmOperationResponse(ctrl *gomock.Controller) *MockconfirmOperationResponse {
	mock := &MockconfirmOperationResponse{ctrl: ctrl}
	mock.recorder = &MockconfirmOperationResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmOperationResponse) EXPECT() *MockconfirmOperationResponseMockRecorder {
	return m.recorder
}

// NewConfirmOperation mocks base method.
func (m *MockconfirmOperationResponse) NewConfirmOperation(operation secureoperation.SecureOperation, message string) model.WaitingConfirmOperationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmOperation", operation, message)
	ret0, _ := ret[0].(model.WaitingConfirmOperationResponse)
	return ret0
}

// NewConfirmOperation indicates an expected call of NewConfirmOperation.
func (mr *MockconfirmOperationResponseMockRecorder) NewConfirmOperation(operation, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmOperation", reflect.TypeOf((*MockconfirmOperationResponse)(nil).NewConfirmOperation), operation, message)
}

// NewErrorConfirmOperation mocks base method.
func (m *MockconfirmOperationResponse) NewErrorConfirmOperation(response mrresp.Error400Response, operation secureoperation.SecureOperation) model.ErrorConfirmOperationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewErrorConfirmOperation", response, operation)
	ret0, _ := ret[0].(model.ErrorConfirmOperationResponse)
	return ret0
}

// NewErrorConfirmOperation indicates an expected call of NewErrorConfirmOperation.
func (mr *MockconfirmOperationResponseMockRecorder) NewErrorConfirmOperation(response, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewErrorConfirmOperation", reflect.TypeOf((*MockconfirmOperationResponse)(nil).NewErrorConfirmOperation), response, operation)
}
