// Code generated by MockGen. DO NOT EDIT.
// Source: check.go
//
// Generated by this command:
//
//	mockgen -source=check.go -destination=mock/check.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	passwordacceptstatus "github.com/mondegor/go-components/mrauth/enum/passwordacceptstatus"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	gomock "go.uber.org/mock/gomock"
)

// MockloginService is a mock of loginService interface.
type MockloginService struct {
	ctrl     *gomock.Controller
	recorder *MockloginServiceMockRecorder
	isgomock struct{}
}

// MockloginServiceMockRecorder is the mock recorder for MockloginService.
type MockloginServiceMockRecorder struct {
	mock *MockloginService
}

// NewMockloginService creates a new mock instance.
func NewMockloginService(ctrl *gomock.Controller) *MockloginService {
	mock := &MockloginService{ctrl: ctrl}
	mock.recorder = &MockloginServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockloginService) EXPECT() *MockloginServiceMockRecorder {
	return m.recorder
}

// CheckAvailabilityRealm mocks base method.
func (m *MockloginService) CheckAvailabilityRealm(ctx context.Context, realm string, userLogin contactaddress.ContactAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityRealm", ctx, realm, userLogin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailabilityRealm indicates an expected call of CheckAvailabilityRealm.
func (mr *MockloginServiceMockRecorder) CheckAvailabilityRealm(ctx, realm, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityRealm", reflect.TypeOf((*MockloginService)(nil).CheckAvailabilityRealm), ctx, realm, userLogin)
}

// MockpasswordService is a mock of passwordService interface.
type MockpasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordServiceMockRecorder
	isgomock struct{}
}

// MockpasswordServiceMockRecorder is the mock recorder for MockpasswordService.
type MockpasswordServiceMockRecorder struct {
	mock *MockpasswordService
}

// NewMockpasswordService creates a new mock instance.
func NewMockpasswordService(ctrl *gomock.Controller) *MockpasswordService {
	mock := &MockpasswordService{ctrl: ctrl}
	mock.recorder = &MockpasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordService) EXPECT() *MockpasswordServiceMockRecorder {
	return m.recorder
}

// CalcStrength mocks base method.
func (m *MockpasswordService) CalcStrength(userPassword string) (string, passwordacceptstatus.Enum) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalcStrength", userPassword)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(passwordacceptstatus.Enum)
	return ret0, ret1
}

// CalcStrength indicates an expected call of CalcStrength.
func (mr *MockpasswordServiceMockRecorder) CalcStrength(userPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalcStrength", reflect.TypeOf((*MockpasswordService)(nil).CalcStrength), userPassword)
}

// Generate mocks base method.
func (m *MockpasswordService) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockpasswordServiceMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockpasswordService)(nil).Generate))
}
