// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrcore (interfaces: Localizer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrcore.go -package=mock github.com/mondegor/go-webcore/mrcore Localizer
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalizer is a mock of Localizer interface.
type MockLocalizer struct {
	ctrl     *gomock.Controller
	recorder *MockLocalizerMockRecorder
	isgomock struct{}
}

// MockLocalizerMockRecorder is the mock recorder for MockLocalizer.
type MockLocalizerMockRecorder struct {
	mock *MockLocalizer
}

// NewMockLocalizer creates a new mock instance.
func NewMockLocalizer(ctrl *gomock.Controller) *MockLocalizer {
	mock := &MockLocalizer{ctrl: ctrl}
	mock.recorder = &MockLocalizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalizer) EXPECT() *MockLocalizerMockRecorder {
	return m.recorder
}

// Language mocks base method.
func (m *MockLocalizer) Language() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockLocalizerMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockLocalizer)(nil).Language))
}

// Translate mocks base method.
func (m *MockLocalizer) Translate(message string, args ...any) string {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Translate", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockLocalizerMockRecorder) Translate(message any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockLocalizer)(nil).Translate), varargs...)
}

// TranslateError mocks base method.
func (m *MockLocalizer) TranslateError(err error) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateError", err)
	ret0, _ := ret[0].(string)
	return ret0
}

// TranslateError indicates an expected call of TranslateError.
func (mr *MockLocalizerMockRecorder) TranslateError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateError", reflect.TypeOf((*MockLocalizer)(nil).TranslateError), err)
}

// TranslateInDomain mocks base method.
func (m *MockLocalizer) TranslateInDomain(domain, message string, args ...any) string {
	m.ctrl.T.Helper()
	varargs := []any{domain, message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TranslateInDomain", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// TranslateInDomain indicates an expected call of TranslateInDomain.
func (mr *MockLocalizerMockRecorder) TranslateInDomain(domain, message any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{domain, message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateInDomain", reflect.TypeOf((*MockLocalizer)(nil).TranslateInDomain), varargs...)
}
