// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrserver (interfaces: FileResponseSender)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrserver_file.go -package=mock github.com/mondegor/go-webcore/mrserver FileResponseSender
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	media "github.com/mondegor/go-core/mrmodel/media"
	gomock "go.uber.org/mock/gomock"
)

// MockFileResponseSender is a mock of FileResponseSender interface.
type MockFileResponseSender struct {
	ctrl     *gomock.Controller
	recorder *MockFileResponseSenderMockRecorder
	isgomock struct{}
}

// MockFileResponseSenderMockRecorder is the mock recorder for MockFileResponseSender.
type MockFileResponseSenderMockRecorder struct {
	mock *MockFileResponseSender
}

// NewMockFileResponseSender creates a new mock instance.
func NewMockFileResponseSender(ctrl *gomock.Controller) *MockFileResponseSender {
	mock := &MockFileResponseSender{ctrl: ctrl}
	mock.recorder = &MockFileResponseSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileResponseSender) EXPECT() *MockFileResponseSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockFileResponseSender) Send(w http.ResponseWriter, status int, structure any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", w, status, structure)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockFileResponseSenderMockRecorder) Send(w, status, structure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFileResponseSender)(nil).Send), w, status, structure)
}

// SendAttachmentFile mocks base method.
func (m *MockFileResponseSender) SendAttachmentFile(ctx context.Context, w http.ResponseWriter, file media.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAttachmentFile", ctx, w, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAttachmentFile indicates an expected call of SendAttachmentFile.
func (mr *MockFileResponseSenderMockRecorder) SendAttachmentFile(ctx, w, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAttachmentFile", reflect.TypeOf((*MockFileResponseSender)(nil).SendAttachmentFile), ctx, w, file)
}

// SendBytes mocks base method.
func (m *MockFileResponseSender) SendBytes(w http.ResponseWriter, status int, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBytes", w, status, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBytes indicates an expected call of SendBytes.
func (mr *MockFileResponseSenderMockRecorder) SendBytes(w, status, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBytes", reflect.TypeOf((*MockFileResponseSender)(nil).SendBytes), w, status, body)
}

// SendFile mocks base method.
func (m *MockFileResponseSender) SendFile(ctx context.Context, w http.ResponseWriter, file media.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", ctx, w, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFile indicates an expected call of SendFile.
func (mr *MockFileResponseSenderMockRecorder) SendFile(ctx, w, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockFileResponseSender)(nil).SendFile), ctx, w, file)
}

// SendNoContent mocks base method.
func (m *MockFileResponseSender) SendNoContent(w http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNoContent", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNoContent indicates an expected call of SendNoContent.
func (mr *MockFileResponseSenderMockRecorder) SendNoContent(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNoContent", reflect.TypeOf((*MockFileResponseSender)(nil).SendNoContent), w)
}
