// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-webcore/mrserver (interfaces: ResponseSender)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrserver.go -package=mock github.com/mondegor/go-webcore/mrserver ResponseSender
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResponseSender is a mock of ResponseSender interface.
type MockResponseSender struct {
	ctrl     *gomock.Controller
	recorder *MockResponseSenderMockRecorder
	isgomock struct{}
}

// MockResponseSenderMockRecorder is the mock recorder for MockResponseSender.
type MockResponseSenderMockRecorder struct {
	mock *MockResponseSender
}

// NewMockResponseSender creates a new mock instance.
func NewMockResponseSender(ctrl *gomock.Controller) *MockResponseSender {
	mock := &MockResponseSender{ctrl: ctrl}
	mock.recorder = &MockResponseSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseSender) EXPECT() *MockResponseSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockResponseSender) Send(w http.ResponseWriter, status int, structure any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", w, status, structure)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockResponseSenderMockRecorder) Send(w, status, structure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockResponseSender)(nil).Send), w, status, structure)
}

// SendBytes mocks base method.
func (m *MockResponseSender) SendBytes(w http.ResponseWriter, status int, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBytes", w, status, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBytes indicates an expected call of SendBytes.
func (mr *MockResponseSenderMockRecorder) SendBytes(w, status, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBytes", reflect.TypeOf((*MockResponseSender)(nil).SendBytes), w, status, body)
}

// SendNoContent mocks base method.
func (m *MockResponseSender) SendNoContent(w http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNoContent", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNoContent indicates an expected call of SendNoContent.
func (mr *MockResponseSenderMockRecorder) SendNoContent(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNoContent", reflect.TypeOf((*MockResponseSender)(nil).SendNoContent), w)
}
