// Code generated by MockGen. DO NOT EDIT.
// Source: security.go
//
// Generated by this command:
//
//	mockgen -source=security.go -destination=mock/security.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	contactaddress "github.com/mondegor/go-components/mrauth/model/contactaddress"
	secureoperation "github.com/mondegor/go-components/mrauth/model/secureoperation"
	media "github.com/mondegor/go-core/mrmodel/media"
	gomock "go.uber.org/mock/gomock"
)

// MockchangeEmailUseCase is a mock of changeEmailUseCase interface.
type MockchangeEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockchangeEmailUseCaseMockRecorder
	isgomock struct{}
}

// MockchangeEmailUseCaseMockRecorder is the mock recorder for MockchangeEmailUseCase.
type MockchangeEmailUseCaseMockRecorder struct {
	mock *MockchangeEmailUseCase
}

// NewMockchangeEmailUseCase creates a new mock instance.
func NewMockchangeEmailUseCase(ctrl *gomock.Controller) *MockchangeEmailUseCase {
	mock := &MockchangeEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockchangeEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangeEmailUseCase) EXPECT() *MockchangeEmailUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockchangeEmailUseCase) Execute(ctx context.Context, actor dto.ActorMeta, newEmail contactaddress.ContactAddress) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, newEmail)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockchangeEmailUseCaseMockRecorder) Execute(ctx, actor, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockchangeEmailUseCase)(nil).Execute), ctx, actor, newEmail)
}

// MockchangePhoneUseCase is a mock of changePhoneUseCase interface.
type MockchangePhoneUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockchangePhoneUseCaseMockRecorder
	isgomock struct{}
}

// MockchangePhoneUseCaseMockRecorder is the mock recorder for MockchangePhoneUseCase.
type MockchangePhoneUseCaseMockRecorder struct {
	mock *MockchangePhoneUseCase
}

// NewMockchangePhoneUseCase creates a new mock instance.
func NewMockchangePhoneUseCase(ctrl *gomock.Controller) *MockchangePhoneUseCase {
	mock := &MockchangePhoneUseCase{ctrl: ctrl}
	mock.recorder = &MockchangePhoneUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangePhoneUseCase) EXPECT() *MockchangePhoneUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockchangePhoneUseCase) Execute(ctx context.Context, actor dto.ActorMeta, newPhone contactaddress.ContactAddress) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, newPhone)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockchangePhoneUseCaseMockRecorder) Execute(ctx, actor, newPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockchangePhoneUseCase)(nil).Execute), ctx, actor, newPhone)
}

// MockapplyOperationUseCase is a mock of applyOperationUseCase interface.
type MockapplyOperationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockapplyOperationUseCaseMockRecorder
	isgomock struct{}
}

// MockapplyOperationUseCaseMockRecorder is the mock recorder for MockapplyOperationUseCase.
type MockapplyOperationUseCaseMockRecorder struct {
	mock *MockapplyOperationUseCase
}

// NewMockapplyOperationUseCase creates a new mock instance.
func NewMockapplyOperationUseCase(ctrl *gomock.Controller) *MockapplyOperationUseCase {
	mock := &MockapplyOperationUseCase{ctrl: ctrl}
	mock.recorder = &MockapplyOperationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapplyOperationUseCase) EXPECT() *MockapplyOperationUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockapplyOperationUseCase) Execute(ctx context.Context, actor dto.ActorMeta, operationToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, operationToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockapplyOperationUseCaseMockRecorder) Execute(ctx, actor, operationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockapplyOperationUseCase)(nil).Execute), ctx, actor, operationToken)
}

// MockchangePasswordUseCase is a mock of changePasswordUseCase interface.
type MockchangePasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockchangePasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockchangePasswordUseCaseMockRecorder is the mock recorder for MockchangePasswordUseCase.
type MockchangePasswordUseCaseMockRecorder struct {
	mock *MockchangePasswordUseCase
}

// NewMockchangePasswordUseCase creates a new mock instance.
func NewMockchangePasswordUseCase(ctrl *gomock.Controller) *MockchangePasswordUseCase {
	mock := &MockchangePasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockchangePasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangePasswordUseCase) EXPECT() *MockchangePasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockchangePasswordUseCase) Execute(ctx context.Context, actor dto.ActorMeta, newPassword string) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, newPassword)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockchangePasswordUseCaseMockRecorder) Execute(ctx, actor, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockchangePasswordUseCase)(nil).Execute), ctx, actor, newPassword)
}

// MockapplyPasswordUseCase is a mock of applyPasswordUseCase interface.
type MockapplyPasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockapplyPasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockapplyPasswordUseCaseMockRecorder is the mock recorder for MockapplyPasswordUseCase.
type MockapplyPasswordUseCaseMockRecorder struct {
	mock *MockapplyPasswordUseCase
}

// NewMockapplyPasswordUseCase creates a new mock instance.
func NewMockapplyPasswordUseCase(ctrl *gomock.Controller) *MockapplyPasswordUseCase {
	mock := &MockapplyPasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockapplyPasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapplyPasswordUseCase) EXPECT() *MockapplyPasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockapplyPasswordUseCase) Execute(ctx context.Context, actor dto.ActorMeta, operationToken string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, operationToken)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockapplyPasswordUseCaseMockRecorder) Execute(ctx, actor, operationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockapplyPasswordUseCase)(nil).Execute), ctx, actor, operationToken)
}

// MockchangeTOTPGeneratorUseCase is a mock of changeTOTPGeneratorUseCase interface.
type MockchangeTOTPGeneratorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockchangeTOTPGeneratorUseCaseMockRecorder
	isgomock struct{}
}

// MockchangeTOTPGeneratorUseCaseMockRecorder is the mock recorder for MockchangeTOTPGeneratorUseCase.
type MockchangeTOTPGeneratorUseCaseMockRecorder struct {
	mock *MockchangeTOTPGeneratorUseCase
}

// NewMockchangeTOTPGeneratorUseCase creates a new mock instance.
func NewMockchangeTOTPGeneratorUseCase(ctrl *gomock.Controller) *MockchangeTOTPGeneratorUseCase {
	mock := &MockchangeTOTPGeneratorUseCase{ctrl: ctrl}
	mock.recorder = &MockchangeTOTPGeneratorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchangeTOTPGeneratorUseCase) EXPECT() *MockchangeTOTPGeneratorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockchangeTOTPGeneratorUseCase) Execute(ctx context.Context, actor dto.ActorMeta) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockchangeTOTPGeneratorUseCaseMockRecorder) Execute(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockchangeTOTPGeneratorUseCase)(nil).Execute), ctx, actor)
}

// MockgetTOTPGeneratorSecretUseCase is a mock of getTOTPGeneratorSecretUseCase interface.
type MockgetTOTPGeneratorSecretUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockgetTOTPGeneratorSecretUseCaseMockRecorder
	isgomock struct{}
}

// MockgetTOTPGeneratorSecretUseCaseMockRecorder is the mock recorder for MockgetTOTPGeneratorSecretUseCase.
type MockgetTOTPGeneratorSecretUseCaseMockRecorder struct {
	mock *MockgetTOTPGeneratorSecretUseCase
}

// NewMockgetTOTPGeneratorSecretUseCase creates a new mock instance.
func NewMockgetTOTPGeneratorSecretUseCase(ctrl *gomock.Controller) *MockgetTOTPGeneratorSecretUseCase {
	mock := &MockgetTOTPGeneratorSecretUseCase{ctrl: ctrl}
	mock.recorder = &MockgetTOTPGeneratorSecretUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetTOTPGeneratorSecretUseCase) EXPECT() *MockgetTOTPGeneratorSecretUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockgetTOTPGeneratorSecretUseCase) Execute(ctx context.Context, userID uuid.UUID, operationToken string) (dto.TOTPGeneratorSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, operationToken)
	ret0, _ := ret[0].(dto.TOTPGeneratorSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockgetTOTPGeneratorSecretUseCaseMockRecorder) Execute(ctx, userID, operationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockgetTOTPGeneratorSecretUseCase)(nil).Execute), ctx, userID, operationToken)
}

// MockrenderTOTPGeneratorQRUseCase is a mock of renderTOTPGeneratorQRUseCase interface.
type MockrenderTOTPGeneratorQRUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockrenderTOTPGeneratorQRUseCaseMockRecorder
	isgomock struct{}
}

// MockrenderTOTPGeneratorQRUseCaseMockRecorder is the mock recorder for MockrenderTOTPGeneratorQRUseCase.
type MockrenderTOTPGeneratorQRUseCaseMockRecorder struct {
	mock *MockrenderTOTPGeneratorQRUseCase
}

// NewMockrenderTOTPGeneratorQRUseCase creates a new mock instance.
func NewMockrenderTOTPGeneratorQRUseCase(ctrl *gomock.Controller) *MockrenderTOTPGeneratorQRUseCase {
	mock := &MockrenderTOTPGeneratorQRUseCase{ctrl: ctrl}
	mock.recorder = &MockrenderTOTPGeneratorQRUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrenderTOTPGeneratorQRUseCase) EXPECT() *MockrenderTOTPGeneratorQRUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockrenderTOTPGeneratorQRUseCase) Execute(ctx context.Context, userID uuid.UUID, operationToken string) (media.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, operationToken)
	ret0, _ := ret[0].(media.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockrenderTOTPGeneratorQRUseCaseMockRecorder) Execute(ctx, userID, operationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockrenderTOTPGeneratorQRUseCase)(nil).Execute), ctx, userID, operationToken)
}

// MockapplyTOTPGeneratorUseCase is a mock of applyTOTPGeneratorUseCase interface.
type MockapplyTOTPGeneratorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockapplyTOTPGeneratorUseCaseMockRecorder
	isgomock struct{}
}

// MockapplyTOTPGeneratorUseCaseMockRecorder is the mock recorder for MockapplyTOTPGeneratorUseCase.
type MockapplyTOTPGeneratorUseCaseMockRecorder struct {
	mock *MockapplyTOTPGeneratorUseCase
}

// NewMockapplyTOTPGeneratorUseCase creates a new mock instance.
func NewMockapplyTOTPGeneratorUseCase(ctrl *gomock.Controller) *MockapplyTOTPGeneratorUseCase {
	mock := &MockapplyTOTPGeneratorUseCase{ctrl: ctrl}
	mock.recorder = &MockapplyTOTPGeneratorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapplyTOTPGeneratorUseCase) EXPECT() *MockapplyTOTPGeneratorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockapplyTOTPGeneratorUseCase) Execute(ctx context.Context, actor dto.ActorMeta, operationToken, totpCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, operationToken, totpCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockapplyTOTPGeneratorUseCaseMockRecorder) Execute(ctx, actor, operationToken, totpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockapplyTOTPGeneratorUseCase)(nil).Execute), ctx, actor, operationToken, totpCode)
}

// MockregenerateRecoveryUseCase is a mock of regenerateRecoveryUseCase interface.
type MockregenerateRecoveryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockregenerateRecoveryUseCaseMockRecorder
	isgomock struct{}
}

// MockregenerateRecoveryUseCaseMockRecorder is the mock recorder for MockregenerateRecoveryUseCase.
type MockregenerateRecoveryUseCaseMockRecorder struct {
	mock *MockregenerateRecoveryUseCase
}

// NewMockregenerateRecoveryUseCase creates a new mock instance.
func NewMockregenerateRecoveryUseCase(ctrl *gomock.Controller) *MockregenerateRecoveryUseCase {
	mock := &MockregenerateRecoveryUseCase{ctrl: ctrl}
	mock.recorder = &MockregenerateRecoveryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregenerateRecoveryUseCase) EXPECT() *MockregenerateRecoveryUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockregenerateRecoveryUseCase) Execute(ctx context.Context, actor dto.ActorMeta) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockregenerateRecoveryUseCaseMockRecorder) Execute(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockregenerateRecoveryUseCase)(nil).Execute), ctx, actor)
}

// MockapplyRecoveryUseCase is a mock of applyRecoveryUseCase interface.
type MockapplyRecoveryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockapplyRecoveryUseCaseMockRecorder
	isgomock struct{}
}

// MockapplyRecoveryUseCaseMockRecorder is the mock recorder for MockapplyRecoveryUseCase.
type MockapplyRecoveryUseCaseMockRecorder struct {
	mock *MockapplyRecoveryUseCase
}

// NewMockapplyRecoveryUseCase creates a new mock instance.
func NewMockapplyRecoveryUseCase(ctrl *gomock.Controller) *MockapplyRecoveryUseCase {
	mock := &MockapplyRecoveryUseCase{ctrl: ctrl}
	mock.recorder = &MockapplyRecoveryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockapplyRecoveryUseCase) EXPECT() *MockapplyRecoveryUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockapplyRecoveryUseCase) Execute(ctx context.Context, actor dto.ActorMeta, operationToken string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor, operationToken)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockapplyRecoveryUseCaseMockRecorder) Execute(ctx, actor, operationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockapplyRecoveryUseCase)(nil).Execute), ctx, actor, operationToken)
}

// Mockdisable2FAUseCase is a mock of disable2FAUseCase interface.
type Mockdisable2FAUseCase struct {
	ctrl     *gomock.Controller
	recorder *Mockdisable2FAUseCaseMockRecorder
	isgomock struct{}
}

// Mockdisable2FAUseCaseMockRecorder is the mock recorder for Mockdisable2FAUseCase.
type Mockdisable2FAUseCaseMockRecorder struct {
	mock *Mockdisable2FAUseCase
}

// NewMockdisable2FAUseCase creates a new mock instance.
func NewMockdisable2FAUseCase(ctrl *gomock.Controller) *Mockdisable2FAUseCase {
	mock := &Mockdisable2FAUseCase{ctrl: ctrl}
	mock.recorder = &Mockdisable2FAUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdisable2FAUseCase) EXPECT() *Mockdisable2FAUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *Mockdisable2FAUseCase) Execute(ctx context.Context, actor dto.ActorMeta) (secureoperation.SecureOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, actor)
	ret0, _ := ret[0].(secureoperation.SecureOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *Mockdisable2FAUseCaseMockRecorder) Execute(ctx, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*Mockdisable2FAUseCase)(nil).Execute), ctx, actor)
}
