// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source=session.go -destination=mock/session.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	dto "github.com/mondegor/go-components/mrauth/dto"
	gomock "go.uber.org/mock/gomock"
)

// MocksessionUseCase is a mock of sessionUseCase interface.
type MocksessionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocksessionUseCaseMockRecorder
	isgomock struct{}
}

// MocksessionUseCaseMockRecorder is the mock recorder for MocksessionUseCase.
type MocksessionUseCaseMockRecorder struct {
	mock *MocksessionUseCase
}

// NewMocksessionUseCase creates a new mock instance.
func NewMocksessionUseCase(ctrl *gomock.Controller) *MocksessionUseCase {
	mock := &MocksessionUseCase{ctrl: ctrl}
	mock.recorder = &MocksessionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionUseCase) EXPECT() *MocksessionUseCaseMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocksessionUseCase) Close(ctx context.Context, userID uuid.UUID, sessionIDs []uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, userID, sessionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocksessionUseCaseMockRecorder) Close(ctx, userID, sessionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocksessionUseCase)(nil).Close), ctx, userID, sessionIDs)
}

// GetList mocks base method.
func (m *MocksessionUseCase) GetList(ctx context.Context, userID uuid.UUID, currentAccessToken, realm string) ([]dto.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, userID, currentAccessToken, realm)
	ret0, _ := ret[0].([]dto.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MocksessionUseCaseMockRecorder) GetList(ctx, userID, currentAccessToken, realm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MocksessionUseCase)(nil).GetList), ctx, userID, currentAccessToken, realm)
}
