// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrauth/validate (interfaces: RequestParser)
//
// Generated by this command:
//
//	mockgen -destination=mock/validate.go -package=mock github.com/mondegor/go-components/mrauth/validate RequestParser
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	netip "net/netip"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	mrtype "github.com/mondegor/go-core/mrtype"
	mrcore "github.com/mondegor/go-webcore/mrcore"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestParser is a mock of RequestParser interface.
type MockRequestParser struct {
	ctrl     *gomock.Controller
	recorder *MockRequestParserMockRecorder
	isgomock struct{}
}

// MockRequestParserMockRecorder is the mock recorder for MockRequestParser.
type MockRequestParserMockRecorder struct {
	mock *MockRequestParser
}

// NewMockRequestParser creates a new mock instance.
func NewMockRequestParser(ctrl *gomock.Controller) *MockRequestParser {
	mock := &MockRequestParser{ctrl: ctrl}
	mock.recorder = &MockRequestParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestParser) EXPECT() *MockRequestParserMockRecorder {
	return m.recorder
}

// DetailedIP mocks base method.
func (m *MockRequestParser) DetailedIP(r *http.Request) mrtype.DetailedIP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedIP", r)
	ret0, _ := ret[0].(mrtype.DetailedIP)
	return ret0
}

// DetailedIP indicates an expected call of DetailedIP.
func (mr *MockRequestParserMockRecorder) DetailedIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedIP", reflect.TypeOf((*MockRequestParser)(nil).DetailedIP), r)
}

// FilterInt64 mocks base method.
func (m *MockRequestParser) FilterInt64(r *http.Request, key string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterInt64", r, key)
	ret0, _ := ret[0].(int64)
	return ret0
}

// FilterInt64 indicates an expected call of FilterInt64.
func (mr *MockRequestParserMockRecorder) FilterInt64(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterInt64", reflect.TypeOf((*MockRequestParser)(nil).FilterInt64), r, key)
}

// FilterInt64List mocks base method.
func (m *MockRequestParser) FilterInt64List(r *http.Request, key string) []int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterInt64List", r, key)
	ret0, _ := ret[0].([]int64)
	return ret0
}

// FilterInt64List indicates an expected call of FilterInt64List.
func (mr *MockRequestParserMockRecorder) FilterInt64List(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterInt64List", reflect.TypeOf((*MockRequestParser)(nil).FilterInt64List), r, key)
}

// FilterRangeInt64 mocks base method.
func (m *MockRequestParser) FilterRangeInt64(r *http.Request, key string) mrtype.RangeInt64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRangeInt64", r, key)
	ret0, _ := ret[0].(mrtype.RangeInt64)
	return ret0
}

// FilterRangeInt64 indicates an expected call of FilterRangeInt64.
func (mr *MockRequestParserMockRecorder) FilterRangeInt64(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRangeInt64", reflect.TypeOf((*MockRequestParser)(nil).FilterRangeInt64), r, key)
}

// FilterString mocks base method.
func (m *MockRequestParser) FilterString(r *http.Request, key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterString", r, key)
	ret0, _ := ret[0].(string)
	return ret0
}

// FilterString indicates an expected call of FilterString.
func (mr *MockRequestParserMockRecorder) FilterString(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterString", reflect.TypeOf((*MockRequestParser)(nil).FilterString), r, key)
}

// FilterStringList mocks base method.
func (m *MockRequestParser) FilterStringList(r *http.Request, key string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterStringList", r, key)
	ret0, _ := ret[0].([]string)
	return ret0
}

// FilterStringList indicates an expected call of FilterStringList.
func (mr *MockRequestParserMockRecorder) FilterStringList(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterStringList", reflect.TypeOf((*MockRequestParser)(nil).FilterStringList), r, key)
}

// FilterUUID mocks base method.
func (m *MockRequestParser) FilterUUID(r *http.Request, key string) uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUUID", r, key)
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// FilterUUID indicates an expected call of FilterUUID.
func (mr *MockRequestParserMockRecorder) FilterUUID(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUUID", reflect.TypeOf((*MockRequestParser)(nil).FilterUUID), r, key)
}

// FilterUint64 mocks base method.
func (m *MockRequestParser) FilterUint64(r *http.Request, key string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUint64", r, key)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// FilterUint64 indicates an expected call of FilterUint64.
func (mr *MockRequestParserMockRecorder) FilterUint64(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUint64", reflect.TypeOf((*MockRequestParser)(nil).FilterUint64), r, key)
}

// FilterUint64List mocks base method.
func (m *MockRequestParser) FilterUint64List(r *http.Request, key string) []uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUint64List", r, key)
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// FilterUint64List indicates an expected call of FilterUint64List.
func (mr *MockRequestParserMockRecorder) FilterUint64List(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUint64List", reflect.TypeOf((*MockRequestParser)(nil).FilterUint64List), r, key)
}

// LangCode mocks base method.
func (m *MockRequestParser) LangCode(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LangCode", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// LangCode indicates an expected call of LangCode.
func (mr *MockRequestParserMockRecorder) LangCode(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LangCode", reflect.TypeOf((*MockRequestParser)(nil).LangCode), r)
}

// Language mocks base method.
func (m *MockRequestParser) Language(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockRequestParserMockRecorder) Language(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockRequestParser)(nil).Language), r)
}

// Localizer mocks base method.
func (m *MockRequestParser) Localizer(r *http.Request) mrcore.Localizer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Localizer", r)
	ret0, _ := ret[0].(mrcore.Localizer)
	return ret0
}

// Localizer indicates an expected call of Localizer.
func (mr *MockRequestParserMockRecorder) Localizer(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Localizer", reflect.TypeOf((*MockRequestParser)(nil).Localizer), r)
}

// Location mocks base method.
func (m *MockRequestParser) Location(r *http.Request) *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Location", r)
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// Location indicates an expected call of Location.
func (mr *MockRequestParserMockRecorder) Location(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Location", reflect.TypeOf((*MockRequestParser)(nil).Location), r)
}

// PathParamString mocks base method.
func (m *MockRequestParser) PathParamString(r *http.Request, name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathParamString", r, name)
	ret0, _ := ret[0].(string)
	return ret0
}

// PathParamString indicates an expected call of PathParamString.
func (mr *MockRequestParserMockRecorder) PathParamString(r, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathParamString", reflect.TypeOf((*MockRequestParser)(nil).PathParamString), r, name)
}

// PathParamUUID mocks base method.
func (m *MockRequestParser) PathParamUUID(r *http.Request, name string) uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathParamUUID", r, name)
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// PathParamUUID indicates an expected call of PathParamUUID.
func (mr *MockRequestParserMockRecorder) PathParamUUID(r, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathParamUUID", reflect.TypeOf((*MockRequestParser)(nil).PathParamUUID), r, name)
}

// PathParamUint64 mocks base method.
func (m *MockRequestParser) PathParamUint64(r *http.Request, name string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathParamUint64", r, name)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// PathParamUint64 indicates an expected call of PathParamUint64.
func (mr *MockRequestParserMockRecorder) PathParamUint64(r, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathParamUint64", reflect.TypeOf((*MockRequestParser)(nil).PathParamUint64), r, name)
}

// RawParamString mocks base method.
func (m *MockRequestParser) RawParamString(r *http.Request, key string) *string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawParamString", r, key)
	ret0, _ := ret[0].(*string)
	return ret0
}

// RawParamString indicates an expected call of RawParamString.
func (mr *MockRequestParserMockRecorder) RawParamString(r, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawParamString", reflect.TypeOf((*MockRequestParser)(nil).RawParamString), r, key)
}

// RealIP mocks base method.
func (m *MockRequestParser) RealIP(r *http.Request) netip.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealIP", r)
	ret0, _ := ret[0].(netip.Addr)
	return ret0
}

// RealIP indicates an expected call of RealIP.
func (mr *MockRequestParserMockRecorder) RealIP(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealIP", reflect.TypeOf((*MockRequestParser)(nil).RealIP), r)
}

// SessionID mocks base method.
func (m *MockRequestParser) SessionID(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockRequestParserMockRecorder) SessionID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockRequestParser)(nil).SessionID), r)
}

// TimeZoneName mocks base method.
func (m *MockRequestParser) TimeZoneName(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeZoneName", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// TimeZoneName indicates an expected call of TimeZoneName.
func (mr *MockRequestParserMockRecorder) TimeZoneName(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeZoneName", reflect.TypeOf((*MockRequestParser)(nil).TimeZoneName), r)
}

// UserAndGroup mocks base method.
func (m *MockRequestParser) UserAndGroup(r *http.Request) (uuid.UUID, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAndGroup", r)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// UserAndGroup indicates an expected call of UserAndGroup.
func (mr *MockRequestParserMockRecorder) UserAndGroup(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAndGroup", reflect.TypeOf((*MockRequestParser)(nil).UserAndGroup), r)
}

// UserID mocks base method.
func (m *MockRequestParser) UserID(r *http.Request) uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID", r)
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockRequestParserMockRecorder) UserID(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockRequestParser)(nil).UserID), r)
}

// Validate mocks base method.
func (m *MockRequestParser) Validate(r *http.Request, structPointer any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", r, structPointer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockRequestParserMockRecorder) Validate(r, structPointer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockRequestParser)(nil).Validate), r, structPointer)
}

// ValidateContent mocks base method.
func (m *MockRequestParser) ValidateContent(ctx context.Context, content []byte, structPointer any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContent", ctx, content, structPointer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContent indicates an expected call of ValidateContent.
func (mr *MockRequestParserMockRecorder) ValidateContent(ctx, content, structPointer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContent", reflect.TypeOf((*MockRequestParser)(nil).ValidateContent), ctx, content, structPointer)
}
