// Code generated by MockGen. DO NOT EDIT.
// Source: apply_settings.go
//
// Generated by this command:
//
//	mockgen -source=apply_settings.go -destination=mock/apply_settings.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/mondegor/go-components/mrauth/dto"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserSettingsStorage is a mock of userSettingsStorage interface.
type MockuserSettingsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserSettingsStorageMockRecorder
	isgomock struct{}
}

// MockuserSettingsStorageMockRecorder is the mock recorder for MockuserSettingsStorage.
type MockuserSettingsStorageMockRecorder struct {
	mock *MockuserSettingsStorage
}

// NewMockuserSettingsStorage creates a new mock instance.
func NewMockuserSettingsStorage(ctrl *gomock.Controller) *MockuserSettingsStorage {
	mock := &MockuserSettingsStorage{ctrl: ctrl}
	mock.recorder = &MockuserSettingsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserSettingsStorage) EXPECT() *MockuserSettingsStorageMockRecorder {
	return m.recorder
}

// UpdateSettings mocks base method.
func (m *MockuserSettingsStorage) UpdateSettings(ctx context.Context, row entity.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockuserSettingsStorageMockRecorder) UpdateSettings(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockuserSettingsStorage)(nil).UpdateSettings), ctx, row)
}

// MocklangResolver is a mock of langResolver interface.
type MocklangResolver struct {
	ctrl     *gomock.Controller
	recorder *MocklangResolverMockRecorder
	isgomock struct{}
}

// MocklangResolverMockRecorder is the mock recorder for MocklangResolver.
type MocklangResolverMockRecorder struct {
	mock *MocklangResolver
}

// NewMocklangResolver creates a new mock instance.
func NewMocklangResolver(ctrl *gomock.Controller) *MocklangResolver {
	mock := &MocklangResolver{ctrl: ctrl}
	mock.recorder = &MocklangResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklangResolver) EXPECT() *MocklangResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MocklangResolver) Resolve(lang string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", lang)
	ret0, _ := ret[0].(string)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MocklangResolverMockRecorder) Resolve(lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MocklangResolver)(nil).Resolve), lang)
}

// MocktimeZoneResolver is a mock of timeZoneResolver interface.
type MocktimeZoneResolver struct {
	ctrl     *gomock.Controller
	recorder *MocktimeZoneResolverMockRecorder
	isgomock struct{}
}

// MocktimeZoneResolverMockRecorder is the mock recorder for MocktimeZoneResolver.
type MocktimeZoneResolverMockRecorder struct {
	mock *MocktimeZoneResolver
}

// NewMocktimeZoneResolver creates a new mock instance.
func NewMocktimeZoneResolver(ctrl *gomock.Controller) *MocktimeZoneResolver {
	mock := &MocktimeZoneResolver{ctrl: ctrl}
	mock.recorder = &MocktimeZoneResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeZoneResolver) EXPECT() *MocktimeZoneResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MocktimeZoneResolver) Resolve(in dto.TimeZoneInfo) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", in)
	ret0, _ := ret[0].(string)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MocktimeZoneResolverMockRecorder) Resolve(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MocktimeZoneResolver)(nil).Resolve), in)
}
