// Code generated by MockGen. DO NOT EDIT.
// Source: change_settings.go
//
// Generated by this command:
//
//	mockgen -source=change_settings.go -destination=mock/change_settings.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/mondegor/go-components/mrauth/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockuserSettingsStorage is a mock of userSettingsStorage interface.
type MockuserSettingsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserSettingsStorageMockRecorder
	isgomock struct{}
}

// MockuserSettingsStorageMockRecorder is the mock recorder for MockuserSettingsStorage.
type MockuserSettingsStorageMockRecorder struct {
	mock *MockuserSettingsStorage
}

// NewMockuserSettingsStorage creates a new mock instance.
func NewMockuserSettingsStorage(ctrl *gomock.Controller) *MockuserSettingsStorage {
	mock := &MockuserSettingsStorage{ctrl: ctrl}
	mock.recorder = &MockuserSettingsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserSettingsStorage) EXPECT() *MockuserSettingsStorageMockRecorder {
	return m.recorder
}

// UpdateSettings mocks base method.
func (m *MockuserSettingsStorage) UpdateSettings(ctx context.Context, row entity.UserSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockuserSettingsStorageMockRecorder) UpdateSettings(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockuserSettingsStorage)(nil).UpdateSettings), ctx, row)
}

// MockauthTokenSettingsStorage is a mock of authTokenSettingsStorage interface.
type MockauthTokenSettingsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockauthTokenSettingsStorageMockRecorder
	isgomock struct{}
}

// MockauthTokenSettingsStorageMockRecorder is the mock recorder for MockauthTokenSettingsStorage.
type MockauthTokenSettingsStorageMockRecorder struct {
	mock *MockauthTokenSettingsStorage
}

// NewMockauthTokenSettingsStorage creates a new mock instance.
func NewMockauthTokenSettingsStorage(ctrl *gomock.Controller) *MockauthTokenSettingsStorage {
	mock := &MockauthTokenSettingsStorage{ctrl: ctrl}
	mock.recorder = &MockauthTokenSettingsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthTokenSettingsStorage) EXPECT() *MockauthTokenSettingsStorageMockRecorder {
	return m.recorder
}

// UpdateScopesSettings mocks base method.
func (m *MockauthTokenSettingsStorage) UpdateScopesSettings(ctx context.Context, userID uuid.UUID, langCode, timeZone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScopesSettings", ctx, userID, langCode, timeZone)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScopesSettings indicates an expected call of UpdateScopesSettings.
func (mr *MockauthTokenSettingsStorageMockRecorder) UpdateScopesSettings(ctx, userID, langCode, timeZone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScopesSettings", reflect.TypeOf((*MockauthTokenSettingsStorage)(nil).UpdateScopesSettings), ctx, userID, langCode, timeZone)
}
