// Code generated by MockGen. DO NOT EDIT.
// Source: confirm_code.go
//
// Generated by this command:
//
//	mockgen -source=confirm_code.go -destination=mock/confirm_code.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	confirmmethod "github.com/mondegor/go-components/mrauth/enum/confirmmethod"
	gomock "go.uber.org/mock/gomock"
)

// Mockauth2faVerifier is a mock of auth2faVerifier interface.
type Mockauth2faVerifier struct {
	ctrl     *gomock.Controller
	recorder *Mockauth2faVerifierMockRecorder
	isgomock struct{}
}

// Mockauth2faVerifierMockRecorder is the mock recorder for Mockauth2faVerifier.
type Mockauth2faVerifierMockRecorder struct {
	mock *Mockauth2faVerifier
}

// NewMockauth2faVerifier creates a new mock instance.
func NewMockauth2faVerifier(ctrl *gomock.Controller) *Mockauth2faVerifier {
	mock := &Mockauth2faVerifier{ctrl: ctrl}
	mock.recorder = &Mockauth2faVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauth2faVerifier) EXPECT() *Mockauth2faVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *Mockauth2faVerifier) Verify(ctx context.Context, userID uuid.UUID, method confirmmethod.Enum, code string) (bool, func(context.Context) error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, userID, method, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(func(context.Context) error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Verify indicates an expected call of Verify.
func (mr *Mockauth2faVerifierMockRecorder) Verify(ctx, userID, method, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*Mockauth2faVerifier)(nil).Verify), ctx, userID, method, code)
}
