// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mondegor/go-components/mrauth (interfaces: TokenGenerator,CodeGenerator)
//
// Generated by this command:
//
//	mockgen -destination=mock/mrauth.go -package=mock github.com/mondegor/go-components/mrauth TokenGenerator,CodeGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// GenToken mocks base method.
func (m *MockTokenGenerator) GenToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenToken indicates an expected call of GenToken.
func (mr *MockTokenGeneratorMockRecorder) GenToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenToken", reflect.TypeOf((*MockTokenGenerator)(nil).GenToken))
}

// MockCodeGenerator is a mock of CodeGenerator interface.
type MockCodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCodeGeneratorMockRecorder
	isgomock struct{}
}

// MockCodeGeneratorMockRecorder is the mock recorder for MockCodeGenerator.
type MockCodeGeneratorMockRecorder struct {
	mock *MockCodeGenerator
}

// NewMockCodeGenerator creates a new mock instance.
func NewMockCodeGenerator(ctrl *gomock.Controller) *MockCodeGenerator {
	mock := &MockCodeGenerator{ctrl: ctrl}
	mock.recorder = &MockCodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeGenerator) EXPECT() *MockCodeGeneratorMockRecorder {
	return m.recorder
}

// CompareSecretAndHash mocks base method.
func (m *MockCodeGenerator) CompareSecretAndHash(secret, hashedSecret string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareSecretAndHash", secret, hashedSecret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareSecretAndHash indicates an expected call of CompareSecretAndHash.
func (mr *MockCodeGeneratorMockRecorder) CompareSecretAndHash(secret, hashedSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareSecretAndHash", reflect.TypeOf((*MockCodeGenerator)(nil).CompareSecretAndHash), secret, hashedSecret)
}

// GenCodeWithHash mocks base method.
func (m *MockCodeGenerator) GenCodeWithHash() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenCodeWithHash")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenCodeWithHash indicates an expected call of GenCodeWithHash.
func (mr *MockCodeGeneratorMockRecorder) GenCodeWithHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenCodeWithHash", reflect.TypeOf((*MockCodeGenerator)(nil).GenCodeWithHash))
}

// HashedSecret mocks base method.
func (m *MockCodeGenerator) HashedSecret(secret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashedSecret", secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashedSecret indicates an expected call of HashedSecret.
func (mr *MockCodeGeneratorMockRecorder) HashedSecret(secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashedSecret", reflect.TypeOf((*MockCodeGenerator)(nil).HashedSecret), secret)
}
